### ISSUE TITLE
Can't use `f.input` with `country_select`

### ISSUE THREAD

**Issue by victorbstan** [plataformatec/simple_form#1017]
When I use country_select, on input columns of name :country, or :country_code, I get an error: `wrong number of arguments (4 for 1..3)`.

Instead of using `f.input`, I have to use `f.country_select`. However, the documentation doesn't specify this.

I am using gem 'country_select', :git => "https://github.com/stefanpenner/country_select.git" -- which is version 2 branch.

**Comment by Samda** [comment]
Many thanks Edslocomb that is so useful.

**Comment by feliperenan** [comment]
It's been while since this issue was open and I don't know if it's an issue yet. By now, I'm gonna close this, but we can reopen if you still are facing it on the last Simple Form version.

Thanks

**Comment by chmich** [comment]
@edslocomb Thanks! 2024, country_select v8, simple_form v5 and its working!
