### ISSUE TITLE
Support array of inputs type

### ISSUE THREAD

**Issue by ka8725** [plataformatec/simple_form#1124]
Rails 4 supports PostgreSQL array type out of the box. It would be great to have the appropriate input in simple form to generate an array of inputs.

[This blog](http://railsguides.net/simple-form-array-text-input/) post will describes what I'm proposing.

**Comment by feliperenan** [comment]
I gonna close this issue because we don't have plans to support this feature at Simple Form. If you want to have it, you can create a custom input in our application.

Thank you.
