### ISSUE TITLE
Make possible to register custom components.

### ISSUE THREAD

**Issue by rafaelfranca** [plataformatec/simple_form#1176]
Right now to register custom components people have to use private API like:

``` ruby
SimpleForm::Inputs::Base.send(:include, MyCustomComponent)
```

I'd like to introduce a public API to make this easier and document this feature.

**Comment by feliperenan** [comment]
Does it still make sense @rafaelfranca ?

**Comment by feliperenan** [comment]
Resolved by https://github.com/plataformatec/simple_form/pull/1556
