### ISSUE TITLE
Datetime looks weird in rails 4.1 and bootstrap 3

### ISSUE THREAD

**Issue by allenwq** [plataformatec/simple_form#1186]
I installed simple_form with default bootstrap cofiguration: <code> rails generate simple_form:install --bootstrap </code>

And I have something like this in my code
<code><%= f.input :start_at, as: :datetime %> </code>

But the result is:
![screen shot 2015-01-05 at 9 06 15 pm](https://cloud.githubusercontent.com/assets/4983239/5613439/29befe92-951f-11e4-9cef-536b449f0a37.png)

Which looks weird, they are supposed to be in the same line right ?  however, bootstrap2 was fine.

**Comment by emilesilvis** [comment]
Also seeing this.

**Comment by simonini** [comment]
+1

**Comment by dgilperez** [comment]
+1
