### ISSUE TITLE
association with HABTM was taking to much time

### ISSUE THREAD

**Issue by passalini** [plataformatec/simple_form#1188]
Guys I'm trying to optimize an rendering view here, and for some reason the `f.association` with HABTM is increasing in almost 1,000 ms the rendering. I did a work around but I want to know why it happens.

Old code (~ 1,000 ms):
```ruby
# drafts_controller.rb
def update
  @draft = Draft.find(params[:id])
end
```
```slim
/ _draft_form.html.slim
= simple_form_for @draft, remote: true do |f|
  = f.association :mentions
```

New code (~ 80 ms):
```ruby
# drafts_controller.rb
def update
  @draft = Draft.includes(:mentions).find(params[:id])
end
```
```slim
/ _draft_form.html.slim
= simple_form_for @draft, remote: true do |f|
  = f.association :mentions, collection: @draft.mentions
```

ps: My real code have more things but I omitted them because they didn't change to much the rendering time.

**Comment by rafaelfranca** [comment]
It is because for each mention Rails is doing a new query. What you did is not a work around but the proper way to write that code when you have a collection association and need to read any information of it.
