### ISSUE TITLE
Not adding "required=required" attribute

### ISSUE THREAD

**Issue by Libranner** [plataformatec/simple_form#1189]
When indicating presence: true on model, simple form is not adding the required attribute. Also i tried putting "required:true" on my view, but isn't working.

I'm using rails 4.2 and ruby 2.1.5.

Thanks in advance!

**Comment by nashby** [comment]
@Libranner hey, what ORM are you using?

**Comment by Libranner** [comment]
@nashby active record, also i noticed is adding a novalidate attribute to my forms, and i forgeto to say im using rails composer

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by Libranner** [comment]
@nashby  here it is: https://github.com/Libranner/SGE
Just access the path: /cities/new  there is a form.

**Comment by nashby** [comment]
@Libranner thanks for the test app. As I can see you have `browser_validations` disabled in your simple_form.rb. To make html5's required attributes work you need to enable it.

**Comment by Libranner** [comment]
Thanks, my bad :) @nashby
