### ISSUE TITLE
collection_radio_buttons create two radio buttons

### ISSUE THREAD

**Issue by schatteleyn** [plataformatec/simple_form#1190]
So I'm using the example of the doc for collection_radio_buttons, but it display two radio buttons. After inspection of the generated HTML, it seems that there is a <label> that shouldn't exist that wrap the normal tags.

```
<label for="user_challenge_emails_true">
  <input id="user_challenge_emails_true" name="user[challenge_emails]" type="radio" value="true">
  <label class="collection_radio_buttons" for="user_challenge_emails_true">Yes</label>
</label>
```

And here is my HAML code

```
.row#longer
  = f.label "Receive an email when:"
    %ul
      %li A challenge starts
      %li A new step starts
      %li A step is about to end
%p.centered-text.no-margin Do you want to receive these emails?
.radio-yes-no
  = f.collection_radio_buttons :challenge_emails, [[true, 'Yes'] ,[false,'No']], :first, :last, checked: resource.challenge_emails
```

![capture d ecran 2015-01-08 a 18 14 39](https://cloud.githubusercontent.com/assets/626924/5666832/e1aa2686-9762-11e4-978d-d89f98e7f9bb.png)

If I manually remove the wrapping label tag, everything goes back to normal, but I can only do it in "inspect element" mode. Any solutions ?

**Comment by calebthompson** [comment]
I'm having the same issue: before the update, with `SimpleForm.boolean_style == :nested`, the HTML output from a custom input built upon `collection_radio_buttons` was (cleaned for clarity)

```html
<div class="preference__group yesno optional user_is_public">
  <input checked="checked" class="yesno optional" id="user_is_public_true" name="user[is_public]" type="radio" value="true">
  <label class="collection_radio_buttons" for="user_is_public_true">Yes</label>
  <input class="yesno optional" id="user_is_public_false" name="user[is_public]" type="radio" value="false">
  <label class="collection_radio_buttons" for="user_is_public_false">No</label>
</div>
```

And after upgrading (3.0.2 => 3.1.0) we now have each item nested within a second label:

```html
<div class="preference__group yesno optional user_is_public">
  <label for="user_is_public_true">
    <input class="yesno optional" id="user_is_public_true" name="user[is_public]" type="radio" value="true">
    <label class="collection_radio_buttons" for="user_is_public_true">Yes</label>
  </label>
  <label for="user_is_public_false">
    <input checked="checked" class="yesno optional" id="user_is_public_false" name="user[is_public]" type="radio" value="false">
    <label class="collection_radio_buttons" for="user_is_public_false">No</label>
  </label>
</div>
```

Given the `:nested` setting, it almost seems like this may have been a bug that has been fixed, but it would be useful to have a confirmation of that.

The custom input effectively defaults these options on `collection_radio_buttons`:

```ruby
{ item_wrapper_tag: nil, item_wrapper_class: nil, label: false, required: false }
```

Meaning that a simplified proof of this problem would be:

```erb
<%= f.input :accept_terms, as: :collection_radio_buttons, item_wrapper_tag: nil, item_wrapper_class: nil, label: false %>
```

The most likely change that effected this is #944, which refactored a lot of the `collection_radio_buttons` code and specifically changed how wrappers work.

**Comment by artemave** [comment]
@calebthompson +1 I also observe extra label (that wraps up whatever a block argument to collection_radio_buttons/collection_check_boxes outputs) after upgrading from 3.0 to 3.1.

**Comment by feliperenan** [comment]
It's been a long time since that this issue was open and I don't if it is an issue yet, so I'm closing it. Feel free to reopen it if it's necessary.
