### ISSUE TITLE
password input should by default add html argument autocomplete="off"

### ISSUE THREAD

**Issue by equivalent** [plataformatec/simple_form#1191]
Hi, just a security suggestion. Should the simple form password input  by default set the `autocomplete="off"` argument on password input ?

There is no real point not disabling it by default as newer browsers (Internet Explorer > 11, Mozilla Firefox > 30, Google Chrome > 34) no longer support HTML 'autocomplete' on password field

* http://msdn.microsoft.com/en-us/library/ie/ms533486
* https://bugzilla.mozilla.org/show_bug.cgi?id=956906
* http://googlechromereleases.blogspot.ro/2014/04/stable-channel-update.html

...and it's just risk for old browsers

I can create Pull request for this if agreed.

**Comment by rafaelfranca** [comment]
@equivalent it is a awesome idea, but we should implement it at Rails itself.

**Comment by equivalent** [comment]
good point @rafaelfranca  I agree, thank you for this https://github.com/rails/rails/issues/18453

**Comment by equivalent** [comment]
https://github.com/rails/rails/pull/18463

**Comment by nashby** [comment]
@equivalent thank you! Closing this in favour of PR to rails.

**Comment by equivalent** [comment]
Just to complete the story, this turn out to be a horrible idea and will not be implemented in Rails. There is a reason for Password managers, there is reason why Modern browsers ignore `autocomplete=off`
