### ISSUE TITLE
Browsers don't remember values

### ISSUE THREAD

**Issue by nadeemja** [plataformatec/simple_form#1192]
I have this code:

          = simple_form_for :entry, url: '/check', method: :get, remote: true do |f|
            .row
              .col-sm-4.col-sm-offset-4.col-xs-11
                = f.input :email_or_code, input_html: { class: 'input-lg form-control has_tooltip text-center'}, label: false, placeholder: 'Epost eller kodeord', id: 'entry_input'
                %hr.visible-xs

            .row.visible-xs 

              .col-xs-11.text-center
                = f.submit 'Go!', class: 'btn btn-lg', id: 'commit'

In this input, you can either write your email or a code ("happy rabbit"). 
But whatever I write in this field, it's never remembered for next time. There's no dropdown menu of previously inputted emails or codes.

What could be the problem?

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
