### ISSUE TITLE
Unable to force input value

### ISSUE THREAD

**Issue by simo2409** [plataformatec/simple_form#1196]
Hi,
I have an integer field (in which I store money amount so "10.34" becomes "1034"), when I edit my model I have a form like this:
````
<%= f.input :original_amount, as: :string, value: incoming_invoice.original_amount_to_s %>
`````
(incoming_invoice.original_amount_to_s returns something like "10.34")
As you can see I forced it to be a :string but with this line I'm getting a text field (correct) but with "1034" as content (wrong).

Am I missing anything or something doesn't work as expected?

Thank you

**Comment by nashby** [comment]
Hi,
It's ```<%= f.input ..., input_html: { value: incoming_invoice.original_amount_to_s} %>```

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
