### ISSUE TITLE
Checkbox unchecked_value must be a string

### ISSUE THREAD

**Issue by Linuus** [plataformatec/simple_form#1197]
Hi

I tried the example using checked_value and unchecked_value as stated in the readme:

```
<%= f.input :accepts, as: :boolean, checked_value: true, unchecked_value: false %>
```

However, specifying `unchecked_value: false` makes the unchecked input not show up at all which means the input is always true.

If you want the values to be true and false you must use strings:
```
<%= f.input :accepts, as: :boolean, checked_value: "true", unchecked_value: "false" %>
```

This made me a bit confused at first. If this is by design, I guess the readme should be a bit clearer on that :)

**Comment by nashby** [comment]
hey, what rails and SF versions are you using?

**Comment by nashby** [comment]
I think it was [fixed](https://github.com/rails/rails/commit/a872ac9d6f7ed441507bf2a60fac44399c8abea6) in Rails 4+. Feel free to ping me if it still doesn't work for you.
