### ISSUE TITLE
Materialize Generator

### ISSUE THREAD

**Issue by acburst** [plataformatec/simple_form#1198]
I'm a contributor to the new http://materializecss.com/ Material Design framework. I'm also helping a University Ruby on Rails class that wants to use the framework. Is there anyway I could help or advise an install for Materialize? Having simple form run for this framework would be really helpful for us.

**Comment by rafaelfranca** [comment]
Thank you for the suggestion/ We don't plan to add any new generator to Simple Form. In fact I already thought many times to remove the currently included generators to new gems.

**Comment by acburst** [comment]
Do you have any recommendations on how we can use simple form but still customize it some way?

**Comment by rafaelfranca** [comment]
All Simple Form configurations for frameworks are just wrappers. I believe you will have to create wrappers for the framework components in your Simple Form initializer.

**Comment by xamenrax** [comment]
Cheers! So, will it be a good practice to make a separate gem with css_framework-specific generator and load it as dependency ot smth like that?
