### ISSUE TITLE
Reuse i18n translations?

### ISSUE THREAD

**Issue by mhuggins** [plataformatec/simple_form#1199]
Hi there,

I'd like to reuse the `SimpleForm::Inputs::Base#translate_from_namespace` method for translating attribute labels.  However, I'd like to avoid calling `t('simple_form.labels.model_name.attribute_name')` (among other variations [as seen here](https://github.com/plataformatec/simple_form/blob/v3.1.0.rc2/lib/simple_form/inputs/base.rb#L180)).

Is there an easy way to reuse this implementation to grab a translating string for a model's attribute label (or other namespace translations)?

**Comment by georgeguimaraes** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by mhuggins** [comment]
Will do, thanks.
