### ISSUE TITLE
Checkbox with explicit type (bug or feature?)

### ISSUE THREAD

**Issue by rusikf** [plataformatec/simple_form#1200]
It looks that checkbox with explicit type doesn't works:
```ruby
= f.input :active, as: :checkbox
```
Output:
```
No input found for checkbox
```
But without it , like this:
```ruby
= f.input :active
```
It works. It is a bug or feature ?
I am tried on last stable release and also on current git master.

**Comment by carlosantoniodasilva** [comment]
The "checkbox" input type is called `boolean`, so the last example is the same as calling with `as: :boolean`. Hope that helps.

**Comment by rusikf** [comment]
@carlosantoniodasilva , thanks a lot ! :smile:
