### ISSUE TITLE
How to retrieve form's id attribute from custom input

### ISSUE THREAD

**Issue by knagode** [plataformatec/simple_form#1202]
I am trying to retrieve form's id attribute from custom input method:
```
  class DatepickerInput < SimpleForm::Inputs::StringInput
    def input
      ...
      get_form_id # !!! how to?
    end
  end
```

It is easy to retrieve input's options via input_html_options, but how can I access form's properties?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
