### ISSUE TITLE
Wrapper

### ISSUE THREAD

**Issue by noahjerreel** [plataformatec/simple_form#1206]
I'm having a problem with the following code below:

![image](https://cloud.githubusercontent.com/assets/3905566/6182895/7e540dcc-b387-11e4-9aff-0db8df7b1ea1.png)

this is the error:

![image](https://cloud.githubusercontent.com/assets/3905566/6182904/9b3480a2-b387-11e4-9cf8-c49c2284106e.png)

What I want to do is to display the collection on the select box with wrapper for bootstrap select.

Please help me, thank you!

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
