### ISSUE TITLE
Custom error doesn't work

### ISSUE THREAD

**Issue by shir** [plataformatec/simple_form#1208]
In Errors component there is no checking if custom error was provided for not full error:

``` rn
      def error(wrapper_options = nil)
        error_text if has_errors?
      end

      def full_error(wrapper_options = nil)
        full_error_text if options[:error] != false && has_errors?
      end
```

but in `error_text` it check if custom error was provided:

``` rb
      def error_text
        text = has_custom_error? ? options[:error] : errors.send(error_method)

        "#{html_escape(options[:error_prefix])} #{text}".lstrip.html_safe
      end
```

I think the `error` method should looks like same as `full_error`:

``` rb
      def error(wrapper_options = nil)
        error_text if has_custom_error? || has_errors?
      end
```

**Comment by carlosantoniodasilva** [comment]
It seems to make sense, have you tried using it, then what happens?

And would you like to send a pull request to fix the issue?

**Comment by shir** [comment]
@carlosantoniodasilva have just tested in my custom input and found that just changing `error` method doesn't work properly. It shows error text but doesn't mark field as having error. So I just redefined `has_errors?` method in my custom input for my purposes. May be `has_error?` method should include checking for custom error like this:
```rb
      def has_errors?
        has_custom_error? || (object && object.respond_to?(:errors) && errors.present?)
      end
```
But not sure if it will work properly. Will try to test and prepare PR later when will get enough time for it.

**Comment by nashby** [comment]
Hey guys, as I can see it make made on purpose - https://github.com/plataformatec/simple_form/commit/23294b5d67943e2fdda47f50ebad56285fbd3514 As for me it makes sense to check if there's actual error on the attribute before using custom error message.

**Comment by makkrnic** [comment]
I have forked the repo and reverted the changes introduced in 23294b5 as I need to use that option. It is available at https://github.com/makkrnic/simple_form.
As far as I understood it the reason for introducing custom error messages was exactly because not all use cases need models in a way that was thought of here. E.g. https://github.com/plataformatec/simple_form/pull/975#issuecomment-33408137
