### ISSUE TITLE
Can we have a support for mongoid Hash inputs.

### ISSUE THREAD

**Issue by pkrawat1** [plataformatec/simple_form#1210]
Example class
```ruby
Class Test
  include Mongoid::Document
  field :todo_list, type: Hash, default: {}
end
```
Requirement
```ruby
= f.input :todo_list, keys: ['cycling', 'study', 'outing']
```
This should be generated as.
```ruby
= f.fields_for :todo_list  do |list|
 = list.input :cycling
 = list.input :study
 = list.input :outing
```
It could also generate fields like checkbox, radio button fields 
depending upon the argument passed in as 'as: :checkboxes'

Labels could also be passed as in case of collections 
like [['cycling', 'Cycling with friends'], ['outing', 'trek to hills']],

**Comment by carlosantoniodasilva** [comment]
If I got it right, it seems you're proposing a shortcut for something we can already do using fields_for, is that it?

If that's the case, I think we're better off being explicit with the inputs we want.
