### ISSUE TITLE
Label only option

### ISSUE THREAD

**Issue by benjaminwood** [plataformatec/simple_form#1213]
I love simple_form, thanks everybody for your hard work here. 

I know this isn't the place for questions, so I want to preface by saying that I'm researching this subject because I'd like to attempt a pull-request if the feature doesn't exist and if somebody can validate its usefulness. I'd like to make sure I'm not missing something before moving forward.

SO: Is there an option to display a fields label only? I know that I can do this:

`<%= f.label :username %>`

But if my understanding is correct, that just uses rails standard label form helper. My use case is that I need to separate the label from the actual input group that simple_form generates, but I need the label to be highlighted when the field has errors. When using rails form helper, the label element isn't wrapped in simple_forms markup, and therefore doesn't carry the error class defined in my configuration when the field has errors. 

My work around right now is to create a custom wrapper which only contains the label:

```ruby
config.wrappers :label_only, :class => :label,
  :hint_class => :field_with_hint, :error_class => :field_with_errors do |b|
  b.use :label
end
```

This works well and allows me to do things like this:

```haml
%table
  %tbody
    %tr
      %td= form.input :construction_complete, wrapper: 'label_only'
      %td= form.input :construction_complete, as: 'radio', collection: [['Complete', true], ['Not Complete', false], ['N/A', '']], label: false
      %td= form.input :construction_complete_on, include_blank: true
```

While the above is a decent workaround, is there a better way to do this? I've read the documentation and looked for anything along the lines of:

- `input: false`
- `as: 'label'`

As far as I know, neither of those options exist. Would it be a valid request to add such an option? If so, I'd like to take a stab at it myself and create a pull request. I just wanted to get some feedback here first.

Thanks!

**Comment by georgeguimaraes** [comment]
Since it seems like an edge case for Simple Form, going with custom wrappers seems the way to go. I'd do it myself too in any app in this context. :)

**Comment by benjaminwood** [comment]
Cool, thanks @georgeguimaraes. That was the feedback I was looking for. Wrappers are great and are working fine for my use.

Thanks again!

**Comment by semirenko** [comment]
Thanks a lot, @georgeguimaraes. This is exactly what I was looking for.

**Comment by georgeguimaraes** [comment]
@semirenko you're welcome! :)

**Comment by maebeale** [comment]
@benjaminwood - thanks for asking abt this! just what i was looking for!

**Comment by benjaminwood** [comment]
Great, no problem! :smiley:
