### ISSUE TITLE
How to create form when column type is JSON

### ISSUE THREAD

**Issue by stevepm** [plataformatec/simple_form#1214]
Hi, I have a model (FooBar) with three columns:
Foo -> String
Bar -> JSON
Baz -> String

I want to create a form for this model

Bar has default attributes of: {zing: {}, zaz: {}, laz: {}}

I would like to have the following inputs:

f.input :foo
f.input :zing
f.input :zaz
f.input :laz
f.input :baz

I tried to do this using fields_for and passing in each key and converting it to a symbol:

bar.each do |k,v|
f.input k.to_sym
end

but the error I'm getting is that FooBar has undefined method of :zaz

Any ideas would be appreciated, thanks.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by cgarvis** [comment]
StackOverflow question: http://stackoverflow.com/questions/28797648/rails-simple-form-create-form-when-column-type-is-json
