### ISSUE TITLE
HTML5 browser_validations is false by default not true

### ISSUE THREAD

**Issue by aliaksandrb** [plataformatec/simple_form#1216]
Hi guys!
First of all thanks for the great gem, it makes development process much easier and faster! :+1: 

By the way, I've faced strange behavior recently and believe that it is a bug. Let me describe it.

I am using  simple_form for foundation via `rails generate simple_form:install --foundation`.

The documentation says :

> If you want to have all other HTML 5 features, such as the new field types, you can disable only the browser validation:
>   SimpleForm.browser_validations = false **# default is true**

But if we check it, than we see that  `SimpleForm.browser_validations = false` by default, not true

I found only two places where it could be changed:
[initializers/simple_form.rb](https://github.com/plataformatec/simple_form/blob/749c926140ee383e8249f15d1846f5287c5a4c46/lib/generators/simple_form/templates/config/initializers/simple_form.rb#L121)

``` ruby
config.browser_validations = false
```

and
[lib/simple_form.rb](https://github.com/plataformatec/simple_form/blob/749c926140ee383e8249f15d1846f5287c5a4c46/lib/simple_form.rb#L119)

``` ruby
mattr_accessor :browser_validations
@@browser_validations = true
```

And I suspect the problem is in the generator for `simple_for`installation
[install_generator.rb](https://github.com/plataformatec/simple_form/blob/749c926140ee383e8249f15d1846f5287c5a4c46/lib/generators/simple_form/install_generator.rb#L18)

It generates both files `simple_form.rb` and `simple_form_foundation.rb` (or bootstrap) even we chose only for Foundation.
Then Rails is loading initializers in alphabetical order, so browser_validations became false because of `initializers/simple_form.rb` and then this option used it foundation initializer because there is not override there.

So few questions:
- should the `browser_validations` be set to true in `initializers/simple_form.rb` (and both foundation and bootstrap initializers) ? - this is according to the README. Or update the README appropriately.
- what is the reason for generating `initializers/simple_form.rb` when we installing `simple_form` for Foundation/Bootstrap? Maybe it's fine to not doing it and duplicate common options in each initializer if any?
- Want I send an PR ? :blush:

**Comment by jedschneider** [comment]
@aliaksandrb does this seem like a similar issue? https://github.com/plataformatec/simple_form/issues/1178 I have a PR I'm working on, but can't seem to get support for a valid test case.

**Comment by aliaksandrb** [comment]
@jedschneider I'm not sure if it's related but looking for your test here: https://github.com/plataformatec/simple_form/issues/1178#issuecomment-69396642 I suspect that problem could be in the small typo:

the wrapper created with
```ruby
b.use :label_text, required: true
```
but test overrides and looking for input, not label:
```ruby
with_concat_form_for(@user) do |f|
  concat f.input :name, required: false
end
assert_no_select 'input[type=text][required]'
```

Correct me if I'm wrong, never wrote tests for `simple_form` yet :)

**Comment by feliperenan** [comment]
It's been a long time since that this issue was open and I don't if it is issue yet, so I'm closing it. Feel free to reopen it if it's necessary.
