### ISSUE TITLE
Inconsistent use of leading space in checkbox labels

### ISSUE THREAD

**Issue by willkoehler** [plataformatec/simple_form#1219]
#1008 introduced an inconsistency between the label for a single boolean input checkbox and the labels in a collection of checkboxes. The label for a single boolean input checkbox now has a leading space but the labels in a collection of checkboxes don't have a leading space. Basically a repeat of the situation reported in #492.

My preference is to not have a leading space in the labels. I think spacing between labels and form elements should be defined in css and not with whitespace. This allows more precise control of the layout and is compatible with checkbox labels elsewhere in my application. But I understand that Bootstrap compatibility it a big driver in this decision.

**Comment by willkoehler** [comment]
Looking into this more, radio button labels never have a leading space. Whatever decision is ultimately made with checkbox labels should also be applied to radio button labels since they are often styled with the same css rules.

**Comment by feliperenan** [comment]
I don't know if it's an issue yet since it's been a long time since it was opened. So, I'm closing this issue, feel free to reopen it if necessary.
