### ISSUE TITLE
Id of hidden created by boolean field

### ISSUE THREAD

**Issue by ownadi** [plataformatec/simple_form#1220]
Is there a way to set it? It breaks w3c validations (input without id).

**Comment by nashby** [comment]
@ownadi hey, there's no way of setting it right now. Also I just tested input without id with [w3c validator](http://validator.w3.org) and looks like it's valid html5. Can you please elaborate on your problem?

**Comment by ownadi** [comment]
I've figured out i got this error because it was nested in label with for attribute. Thanks for answer anyway.
