### ISSUE TITLE
Not getting errors to appear with simple_form / foundation

### ISSUE THREAD

**Issue by glappen** [plataformatec/simple_form#1222]
Hello,

We are just starting a new project with Zurb/Foundation and using simple_form as well.  Our first form is working, but we cannot get errors to appear.  Here's the code:

    <%= simple_form_for :asset, url: company_assets_path do |f| %>
      <%= f.input :name %>
      <%= f.input :value %>
      <%= f.button :submit %>
    <% end %>

When I submit the form and it is re-rendered, no error classes or wrapper elements appear.  But if I print out the validation errors, I get ["Name can't be blank", "Value can't be blank"].  Can anyone tell me what I'm doing wrong?  Thanks!

Greg

**Comment by nashby** [comment]
@glappen hi, you have to pass your object to the `simple_form_for` call if you want your errors to appear. 

```erb
<%= simple_form_for @assets do |f| %>
  ...
```

**Comment by glappen** [comment]
Ugh, it was even in the documentation that way!!!!  Thanks for the help, works perfectly now!
