### ISSUE TITLE
Item wrapper tag not behaving as documented

### ISSUE THREAD

**Issue by jurglic** [plataformatec/simple_form#1224]
Configuration option item_wrapper_tag is always applied. The [README](https://github.com/plataformatec/simple_form/commit/6e35bec1dca35a768073c70c63393c4cf2716929) says item_wrapper_tag is not used when boolean_style is set to :nested. The reasons for this behaviour  are [discussed here](https://github.com/plataformatec/simple_form/issues/685).

This behaviour changed when upgrading from SimpleForm 2.x to 3.0. Consequently if using default configuration when upgrading, all items of collection of radio/check boxes are now wrapped with additional span element. This is easily remedied with setting item_wrapper_tag to nil.

I think we can update the README to reflect the new (and better) behaviour.

This is really a minor issue in this greatly useful piece of software - keep up the good work :+1:

**Comment by nashby** [comment]
@jurglic hey, good catch. Could you please send us a pull request? Thanks!

**Comment by jurglic** [comment]
@nashby Sure, done.
