### ISSUE TITLE
Implement wrapper sets instead of mappings

### ISSUE THREAD

**Issue by heaven** [plataformatec/simple_form#1229]
https://github.com/rafaelfranca/simple_form-bootstrap/blob/master/app/views/examples/_horizontal_form_sf.html.erb#L3

This looks more like a hack, instead there could be an ability to bound wrappers with a "set" or a "style" (e.g. set named :horizontal). So in views users would simply do something like:

``` haml
= simple_form_for @model, wrapper: :a_custom_wrapper, set: :horizontal
```

So devs would be able to override the wrapper and specify a set name so simple_form does know which wrappers to use for field types.

Inside the config this could look like:

``` ruby
config.wrappers :horizontal_boolean, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
  b.set :horizontal # set name
  b.map :boolean # field type

  #...
end
```

The approach with wrapper_mappings could be useful in some specific situations, but is not very convenient to use it more often.

**Comment by feliperenan** [comment]
It's been a long time since that this issue was open and I don't if it is issue yet, so I'm closing it. Feel free to reopen it if it's necessary.
