### ISSUE TITLE
SimpleForm::FormBuilder#Input_field produces a non styled input when using with twitter bootstrap

### ISSUE THREAD

**Issue by heaven** [plataformatec/simple_form#1230]
Example code:

``` haml
= f.input :start_at, :label => "Start/End dates" do
  = f.input_field :start_at, :as => :date_picker
  = f.input_field :end_at, :as => :date_picker
```

Results in:
![simple_form](https://cloud.githubusercontent.com/assets/126732/6818391/523d4eb4-d2e1-11e4-8f45-030e05185072.jpg)

To achieve the expected result I had to do:

``` haml
= f.input :start_at, :label => "Start/End dates" do
  = f.input_field :start_at, :as => :date_picker, :class => "form-control pull-left"
  = f.input_field :end_at, :as => :date_picker, :class => "form-control pull-left"
```

Which doesn't seem right to me since I have to repeat bootstrap-specific class name each time.

Seems like a bug to me.

**Comment by heaven** [comment]
Adding `pull-left` is okay, users may use additional html there anyway to place the inputs in right positions, but `form-control` should be taken from the wrapper, as well as other input options, specified there.

**Comment by carlosantoniodasilva** [comment]
What's the `date_picker` input, is that a custom you wrote or from some other external gem? It doesn't seem like a default from Simple Form, and that might be the culprit, maybe it's not picking the wrapper options we're passing down when rendering the input.

For example, this is what our [date time input does with the wrapper options](https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/inputs/date_time_input.rb#L4-L5) (and pretty much every input Simple Form has).

Also please make sure to post which Simple Form version you're working with. Thanks.

**Comment by heaven** [comment]
Hi, the `date_picker` input is pretty simple:
```ruby
module SimpleForm
  module Inputs
    class DatePickerInput < StringInput
      def input(wrapper_options = nil)
        super
      end
    end
  end
end
```

It only adds a class name to the input so we can attach a js handler to the input. Results are the same even with the built in text input, seems `input_field` does not add default classes (`.form-control` in particular) to the field, specified in wrapper's config.

**Comment by carlosantoniodasilva** [comment]
Right, I see it, I don't think `input_field` is applying any options from the wrapper, seems like a bug. I've [attempted a fix here](https://github.com/plataformatec/simple_form/compare/ca-fix-input_field-wrapper), lets see what the build says, and maybe if you could try it, that'd be nice too.

Thanks.

**Comment by heaven** [comment]
Hi, I tried to use this ref:
```
gem 'simple_form', :git => "git://github.com/plataformatec/simple_form.git", :branch => "ca-fix-input_field-wrapper", :ref => "8842c2f23015c62ed44d8c746a30376504f3a336"#'3.1.0'
```

I have the next un my config:
```ruby
config.wrappers :horizontal_form, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
  b.use :html5
  b.use :placeholder
  b.optional :maxlength
  b.optional :pattern
  b.optional :min_max
  b.optional :readonly
  b.use :label, class: 'col-sm-3 control-label'

  b.wrapper tag: 'div', class: 'col-sm-9' do |ba|
    ba.use :input, class: 'form-control input-sm'
    ba.use :error, wrap_with: { tag: 'span', class: 'help-block' }
    ba.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
  end
end

config.default_wrapper = :horizontal_form
```

And none of these worked:
```haml
= f.input :start_at, :label => "Start/End dates" do
  = f.input_field :start_at, :as => :date_picker
  = f.input_field :end_at, :as => :date_picker

= f.input :start_at, :label => "Start/End dates" do
  = f.input_field :start_at, :as => :date_picker, :wrapper => :horizontal_form
  = f.input_field :end_at, :as => :date_picker, :wrapper => :horizontal_form
```

In both cases `form-control input-sm` classes are missing from the input

**Comment by heaven** [comment]
Am I doing something wrong?

**Comment by carlosantoniodasilva** [comment]
I think it's because of the wrapper + input, it might not be finding the input due to that, I'll take a look using a similar custom wrapper.

**Comment by feliperenan** [comment]
I don't know if it's an issue yet. I'm closing it by now, but feel free to comment or reopen if necessary.
