### ISSUE TITLE
Option to have aria-required attribute when html5 mode is off

### ISSUE THREAD

**Issue by jmuheim** [plataformatec/simple_form#1235]
Although browser validations of html5 are cool, they still aren't very accessible in combination with screenreaders. Because of this, I have disabled them.

But I'd still like to have the `aria-required` attribute to be set to `true` for required inputs. Other than stated [here](https://github.com/plataformatec/simple_form/issues/1103#issuecomment-49230172), in my opinion, `aria` and `html5` are not the same thing and must be enabled/disabled separately.

**Comment by rafaelfranca** [comment]
To disable browser validations you don't need to disable html5, just use the option that disable it. Is this sufficient?

**Comment by jmuheim** [comment]
While `aria-required` seems to be depending on `config.browser_validations = true`, the HTML5 `required` attribute doesn't.

In my case, `required` is enough, so this is OK for me.

**Comment by jmuheim** [comment]
> While aria-required seems to be depending on config.browser_validations = true, the HTML5 required attribute doesn't.

I think I was wrong about this. Anyway, I'm relying on non-aria and non-html5 ways to announce required fields until browser validations are better implemented to be used with screenreaders.
