### ISSUE TITLE
Nested fields rendering is very slow in Rails 4.2.1

### ISSUE THREAD

**Issue by tanraya** [plataformatec/simple_form#1237]
Just switched to Rails 4.2.1 and found an performance issue with `simple_filelds_for` rendering.

In Rails 4.1.6 it works fast enough:

`Rendered shared/_phone_fields.html.erb (59.0ms)`

However, in Rails 4.2.1 it works quite slowly:

`Rendered shared/_phone_fields.html.erb (226.1ms)`

In both rails versions the code is the same (simplified):

```erb
  <%= f.simple_fields_for :phones, f.object.phones do |b| %>
    <%= f.input :city_code %>
    <%= f.input :phone %>
  <% end %>
```

If I change the code to default rails form helpers, it works without performance drops.

Here's the ruby-prof stats for Rails 4.2.1 http://pastebin.com/NSXwCBEU and for 4.1.6 http://pastebin.com/4waUaveA

Any suggestions or ideas?

**Comment by carlosantoniodasilva** [comment]
Interesting, did anything else change besides the Rails version? For example, I18n, or any other gem. Also, which Ruby version are you using?

We may need to try to isolate that into a new app somehow to figure out what could be causing this. Thanks for your report.

**Comment by tanraya** [comment]
I will create isolated rails app today and try to find an issue.

**Comment by tanraya** [comment]
Hmm. It seems it is an issue with one of gems in the app. I'll continue researching, then put results here.

**Comment by tanraya** [comment]
Whew. I found the reason. It was `binding_of_caller` gem (the `better_errors` requirement).

This happens in `Rails 4.2.1` and `Ruby 2.1.1` on `Linux Ubuntu 14.10`.

Beware of using it until its developers didn't fix this bug.
Hope it will help someone to save time.

**Comment by carlosantoniodasilva** [comment]
Awesome, thanks for reporting back :heart:, glad it's not a Simple Form issue :).

**Comment by alextakitani** [comment]
Had the same problem. 

Rails 4.2.1, Ruby 2.16 and Ruby 2.2.2

disabling binding_of_caller didn't solved for me, disabling webconsole did.

**Comment by carlosantoniodasilva** [comment]
`web-console` relies on `binding_of_caller`, perhaps it was still being activated?

**Comment by alextakitani** [comment]
After more tests:

On Ruby 2.2.2, disabling web-console, but maintaining better_errors and binding_of_caller solves the problem.

On Ruby 2.1.6 only by diabling them all solves it.

@carlosantoniodasilva, any tips on how can I investigate it further?

**Comment by carlosantoniodasilva** [comment]
Interesting.. but this happens on development, or production? (and if it is production, why having those gems in there?)

I don't have any idea really, but maybe you could start by creating a sample app that shows and isolates the problem as much as possible, so that someone can try to help more easily.

**Comment by alextakitani** [comment]
Develoment ( i have those gems enabled only on dev ).

**Comment by mib32** [comment]
@tanraya how do you think, that was related to RubyVM::DebugInspector ?

**Comment by diegorv** [comment]
Same here and I don't use any of this gems
```
Rendered shared/theme/_form_div_small.html.erb (0.7ms)
  Rendered client/contracts/_payment_fields.html.erb (43.2ms)
  Rendered shared/theme/_form_div_small.html.erb (0.9ms)
  Rendered client/contracts/_payment_fields.html.erb (42.2ms)
  Rendered shared/theme/_form_div_small.html.erb (0.8ms)
  Rendered client/contracts/_payment_fields.html.erb (44.3ms)
  Rendered shared/theme/_form_div_small.html.erb (0.7ms)
  Rendered client/contracts/_payment_fields.html.erb (43.9ms)
  Rendered shared/theme/_form_div_small.html.erb (0.7ms)
  Rendered client/contracts/_payment_fields.html.erb (49.8ms)
  Rendered shared/theme/_form_div_small.html.erb (0.7ms)
  Rendered client/contracts/_payment_fields.html.erb (41.8ms)
  Rendered shared/theme/_form_div_small.html.erb (0.8ms)
  Rendered client/contracts/_payment_fields.html.erb (47.3ms)
  Rendered shared/theme/_form_div_small.html.erb (0.8ms)
  Rendered client/contracts/_payment_fields.html.erb (48.7ms)
  Rendered shared/theme/_form_div_small.html.erb (0.7ms)
  Rendered client/contracts/_payment_fields.html.erb (71.9ms)
  Rendered shared/theme/_form_div_small.html.erb (0.7ms)
  Rendered client/contracts/_payment_fields.html.erb (81.5ms)
  Rendered shared/theme/_form_div_small.html.erb (0.7ms)
  Rendered client/contracts/_payment_fields.html.erb (65.7ms)
  Rendered shared/theme/_form_div_small.html.erb (0.8ms)
  Rendered client/contracts/_payment_fields.html.erb (58.4ms)
  Rendered shared/theme/_form_div_small.html.erb (0.8ms)
  Rendered client/contracts/_payment_fields.html.erb (44.0ms)
  Rendered shared/theme/_form_div_small.html.erb (0.8ms)
  Rendered client/contracts/_payment_fields.html.erb (43.6ms)
  Rendered shared/theme/_form_div.html.erb (0.5ms)
  Rendered client/contracts/_payment_box.html.erb (773.2ms)

**Comment by diegorv** [comment]
Maybe related with #1227?

**Comment by darryn02** [comment]
Using Ruby 2.2.2, I also had the issue and resolved by removing web-console from Gemfile. Rendering times went from 700-1800ms to 40-70 ms. Whew!

I had found #1227 first and the suggestions there didn't help me.

**Comment by gregblass** [comment]
Seriously thank you for posting this. I was battling with a huge performance hit because of this bug. Somehow a google of "rails nested fields performance" turned this up first (Thanks, Google!). Removing better errors and binding of caller shaved a whole 3 seconds and got my page load down to 250ms.

**Comment by awong-dev** [comment]
See https://github.com/plataformatec/simple_form/issues/1227#issuecomment-138198992.  I think the root cause is actually in simple_forms, not in binding_of_caller.
