### ISSUE TITLE
Bootstrap Horizontal Form Wrapper Issue.

### ISSUE THREAD

**Issue by Jo5h** [plataformatec/simple_form#1238]
The div wrapper (form-group) for the horizontal form is not passing the row class.  This causes some responsive issues with the layout.  The first being on that on large screens there is no bottom-margin on the div.  The second being that if a label spans over two lines it will readjust layout at certain widths to have the label for the next row at the right of the form-group prior. Adding the row class via wrapper_html: { class: 'row' } fixes both these issues, and conforms to Bootstraps best practices of having cols reside within rows.

![screenshot from 2015-04-07 08 20 28](https://cloud.githubusercontent.com/assets/4196382/7022943/08cadd32-dcff-11e4-85e2-178d0f27a7cc.png)

![screenshot from 2015-04-07 08 26 41](https://cloud.githubusercontent.com/assets/4196382/7023038/dfd4ad94-dcff-11e4-81ec-3fa3c73e55fa.png)

**Comment by carlosantoniodasilva** [comment]
Quoting [bootstrap horizontal forms docs](http://getbootstrap.com/css/#forms-horizontal):

> Use Bootstrap's predefined grid classes to align labels and groups of form controls in a horizontal layout by adding `.form-horizontal` to the form (which doesn't have to be a `<form>`). Doing so changes `.form-groups` to behave as grid rows, so no need for `.row`.

This tells us the `row` class shouldn't be necessary, so there might be something else going on on your form. I'm giving this a close, please use the mailing list if you need help, if we end up figuring it's a real Simple Form issue, we can reopen later. Thanks!
