### ISSUE TITLE
Missing doc for `selected` option for select inputs

### ISSUE THREAD

**Issue by PikachuEXE** [plataformatec/simple_form#1249]
I tried to put `selected` option in `input_html` option
But actually it should be passed in directly
There is no doc mentioning available options and where to put them

**Comment by rafaelfranca** [comment]
Yes. Could you submit a pull request?

**Comment by PikachuEXE** [comment]
#1250 opened

**Comment by feliperenan** [comment]
I'm closing this issue since it was resolved.
