### ISSUE TITLE
Setting a data attribute in country select overrides selected Update: this only happens when field is in a hidden div on pageload

### ISSUE THREAD

**Issue by kitation** [plataformatec/simple_form#1253]
Hello!

We have a country field as so

```
=f.input :venue_country, as: :country, selected: 'GB', input_html: {data: {'js-toggle-clear' => 'xx'}}
```

The select field appears with all the countries but 'GB' is not selected. If we remove the input_html or swap out 'data' for 'class', GB is selected as expected. I haven't tried it with a normal select box however.

**Comment by kitation** [comment]
We have a similar issue with booleans.

```
=f.input :venue_accessible_toilet, as: :boolean, input_html: {class: 'js-toggle-clear'}
```

The value of this when checked saves as nil in the database.

**Comment by carlosantoniodasilva** [comment]
Can you try with another data attribute instead? I'm starting to wonder if
your issue isn't related to this js-toggle-clear which seems to be enabling
some sort of Javascript component. If other data attribute works, it'd mean
it's unrelated to simple form. Thanks.

Carlos Antonio da Silva - via celular

**Comment by kitation** [comment]
The js-toggle-clear attribute is ours, and we haven't hooked it into any javascript yet as we are still building the form.

**Comment by carlosantoniodasilva** [comment]
Ok. Can you try to provide a sample app that reproduces the issue? That would help to pinpoint the problem, otherwise someone might try to take a look when possible. Thanks.

**Comment by feliperenan** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please open up a new issue and make sure to fill in all the information requested in the template shown inside the text box. Thank you!
