### ISSUE TITLE
simple_form_for tag with symbol does not properly sync with model.

### ISSUE THREAD

**Issue by yoongkang** [plataformatec/simple_form#1262]
After looking at the code, I realise this is more of a feature request than a bug report, but this was slightly surprising behaviour for me at first.

Let's say we have a form where `bar` (text field) is required, but `baz` (text area) is optional:

```ruby
simple_form_for @foo do |f|
  f.input :bar
  f.input :baz
  f.button "Submit"
end
```

I would expect if you replace `@foo` with a symbol with the same name as the model, say:

```ruby
simple_form_for :foo do |f|
  f.input :bar
  f.input :baz
  f.button "Submit"
end
```

..to correctly sync with the model. However, in this case both fields are marked as required, and `baz` becomes a text field by default.

**Comment by carlosantoniodasilva** [comment]
Simple Form does not use the symbol to try to lookup the object name. If you have the object you can just pass it in instead.

In fact, I recommended deprecating this behavior in Rails, and it's likely that it will be, as it's more confusing than helpful.

Thanks!
