### ISSUE TITLE
Label 'for' attribute does not point to correct id if id is overridden on the input_html level

### ISSUE THREAD

**Issue by yourtallness** [plataformatec/simple_form#1263]
e.g. haml:

= f.input :options, as: :check_boxes, collection: SOME_OPTIONS, include_hidden: false, input_html: { id: SecureRandom.hex }

The label should match the input's id so that the label is clickable but the following happens:

    <label for="my_model_options_first_option"><input id="0614f7eb3ff371aa64a899e958ceb90f" class="check_boxes optional" type="checkbox" value="first_option" name="my_model[options][]">Do stuff</label>

It appears the label **for** attribute will reference model_name + attribute_name + value regardless of the user specified id.

There is also no way (that I know of) to disable the **for** attribute for the check-box label. Without a **for** attribute in the label, the nesting of the input within the label would allow for clicking on it.

I have noticed the generate_label_for_attribute? method, but it's a global configuration setting and I would like to be able to fix this on the individual form level.

I suppose this functionality in **/lib/simple_form/components/labels.rb** also related:

      def label(wrapper_options = nil)
        label_options = merge_wrapper_options(label_html_options, wrapper_options)

        if generate_label_for_attribute?
          @builder.label(label_target, label_text, label_options)
        else
          template.label_tag(nil, label_text, label_options)
        end
      end

      def label_target
        attribute_name
      end

The label_target does not take the target's id into account.

Please advise.

**Comment by nashby** [comment]
First of all when you're input_html: { id: something } with `check_boxes` input type you'll get a list of inputs with the same id and that is not a valid html. So probably you want to use something like 

```erb
<%= f.input :options, as: :check_boxes, collection: [['Option 1', 2, {id: SecureRandom.hex}], ['Option 2', 2, {id: SecureRandom.hex}]] %>
```

But right now it won't fix your issue either. I sent a pull request to rails fixing it though https://github.com/rails/rails/issues/20482

Not really sure about the way you can fix it for now and not waiting for the Rails fix. @carlosantoniodasilva any idea?

**Comment by yourtallness** [comment]
@nashby A way to disable the **for** attribute would also be handy.

There is no need to have a **for** attribute if the input is nested within the label.

**Comment by carlosantoniodasilva** [comment]
We should be able to go with the Rails fix I think @nashby, I'll try to take a look there, still catching up with oss emails :).

**Comment by rafaelfranca** [comment]
The fix was applied in Rails at https://github.com/rails/rails/commit/3570cc0a278d3f1457984db2624a2e0ac048521b#commitcomment-13961458

**Comment by alejorivera** [comment]
Hello! Ran into this same issue and haven't been able to find a fix for it. Is there anyway to "propagate" the input's id to the label, or to namespace an input so that it doesn't conflict with others with the same id on the same page?

**Comment by alejorivera** [comment]
Nevermind! Just learned you can namespace forms and that solved it. Thanks anyways!
