### ISSUE TITLE
undefined method `extending' for #<Class:0x007fa19bde80e8>

### ISSUE THREAD

**Issue by kyledecot** [plataformatec/simple_form#1264]
It seems as though simple_form doesn't play nicely with associations that use [association extensions](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html). 

I have the following `Observation` model:

```
class Observation < ActiveRecord::Base
  has_many :observation_students

  has_many :students,
    -> { extending(ExcludeByObjectsOrIds) },
    class_name: 'PS::Student',
    through: :observation_studets
  ...
```

Then in my form partial I have:

```
= simple_form_for [activity, observation] do |f|
  = f.association :students, as: :check_boxes
```

I am able to call `Observation.new.students.excluding([someId])` from the rails console so I know that everything is wired up properly. The problem is when I render the form:

![screen shot 2015-06-09 at 11 58 32 am](https://cloud.githubusercontent.com/assets/192464/8062688/08e72e84-0e9f-11e5-915f-cdfe65ce4551.png)

**Comment by alkalinecoffee** [comment]
I ran into this problem too.  The `#extending` call is found [here](https://github.com/rails/rails/blob/718468e1c9666ee8d58ae2a446e865a1e1e1fc4e/activerecord/lib/active_record/associations/builder/collection_association.rb#L73).  The caller from Simple Form is [here](https://github.com/plataformatec/simple_form/blob/e81af052f4bbe9e17e38c668116cd1846c6d275c/lib/simple_form/form_builder.rb#L454-L471).

In my polymorphic example, I pass a block to my `has_many` association, which is effectively the same as passing a proc as the second argument, as in @kyledecot's example.

```ruby
has_many :partners, through: :abilities, source: :ability, source_type: Partner do
  # ...
end
```

It appears that Rails treats an extension very similarly to a scope, of which I'm not sure I agree with.

Nevertheless, we can work around this by simply passing our own `collection` value to simple form's `association` method, ie:

```ruby
= f.association :partners,
  as: :check_boxes,
  collection: Partner.all
```

**Comment by feliperenan** [comment]
Hi @kyledecot 

I don't know if it's an issue since it's been a long while. 

Now we have an issue template that helps you provide more information about the issue. Please, if that's the case, open a new issue and make sure to fill in all the information requested by the template shown inside the text box. 

Thank you!
