### ISSUE TITLE
How can make phone input filed with 3 input fields?

### ISSUE THREAD

**Issue by say8425** [plataformatec/simple_form#1265]
![u9opp](https://cloud.githubusercontent.com/assets/3258867/8100390/1375e856-1046-11e5-8712-5d596961ab00.png)

The default phone fields of Simple_form is example 1.

But I want to make like example 2.

Is is possible? Thanks.

**Comment by carlosantoniodasilva** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
