### ISSUE TITLE
collection_check_boxes renders labels twice when using default configuration initializer

### ISSUE THREAD

**Issue by aaronmcadam** [plataformatec/simple_form#1266]
[Here's an example app](https://github.com/aaronmcadam/simple_form_custom_labels/tree/haml), there's 2 branches. `master` uses erb and works as expected. `haml` uses Haml with the default configuration initializer and renders labels twice.

**Comment by aaronmcadam** [comment]
It looks like it's caused by the default initializer the generator installs. If I comment it out, it works fine when using haml.

**Comment by nashby** [comment]
@aaparmeggiani yeah, that's how `boolean_style: :nested` config work I guess. Since you want it to be inline (because you're making it nested by yourself) you need to use `boolean_style: :inline` config: 

```ruby
= simple_form_for(@form, url: "/", method: :patch) do |f|
  = f.input(:option_ids, |
    error: false,        |
    label: false,        |
    as: :check_boxes) do |
    = f.collection_check_boxes :option_ids, @options, :id, :label, boolean_style: :inline do |b|
      = b.label(class: b.object.exclusive && "exclusive" || nil) {         |
          b.check_box(data_exclusive: b.object.exclusive) + b.object.label |
        }                                                                  |
  = f.submit("Complete")
```

**Comment by aaronmcadam** [comment]
@nashby ah, thanks a lot for looking! I'll close this then :smile:

**Comment by nashby** [comment]
@aaronmcadam hope it helped!

**Comment by johncalvinyoung** [comment]
@nashby This is extremely not-obvious, thanks so much for the solution. Would be nice to add a note to the `collection_check_boxes` documentation...the example shows a pattern like this, but no `boolean_style: :inline` to make it generate the markup the example implies.
