### ISSUE TITLE
[Question] Bind error class to manually created haml wrapper

### ISSUE THREAD

**Issue by Kamilius** [plataformatec/simple_form#1267]
Hi. I have next group of controls:

```haml
.control-group.string.required.user_name
  = f.input_field :name, required: true, class: 'form-control'
  = f.label 'User Name'
  = f.error :name
```
Is there any way to bind '.control-group' to it's child input, so if input is invalid, wrapper will get class ".error" added? (Preferably without creation of separate components)

Thanks

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
