### ISSUE TITLE
Release 2.1.3

### ISSUE THREAD

**Issue by huerlisi** [plataformatec/simple_form#1271]
Please consider a release 2.1.3. It looks like the issue with Ruby 2.2 regarding circular argument reference has been fixed in the v2.1 branch.

Rails has a released version supporting ruby 2.2 since the release of 3.2.22.

**Comment by edsimpson** [comment]
+1

**Comment by carlosantoniodasilva** [comment]
I've just pushed v2.1.3, I hope that will help everyone under Rails 3.2 and Ruby 2.1/2. Please let us know about any other issue, thanks.

**Comment by huerlisi** [comment]
Thanks a lot! Will give it a try.
