### ISSUE TITLE
bootstrap2.3 rails4.2 simple_form3.x?

### ISSUE THREAD

**Issue by dudo** [plataformatec/simple_form#1273]
Hey there. I'm stuck using bootstrap 2 on a project that i'm upgrading to rails 4. If I use the latest build of simple_form I have issues with my wrappers and whatnot. Specifically around checkboxes showing up in a span instead of a label.

If I lock simple_form to 3.0.2, all is well, but I have all the deprecations with rails 4.2. Thoughts?

**Comment by carlosantoniodasilva** [comment]
Which issues are you seeing? Have you generated the default bootstrap initializer - which is for bootstrap v3, that might conflict? Have you tried tweaking the wrappers more? Which deprecations you're seeing?

Please try to provide some more information, and some example code / results. I'm not sure there's much we can do in terms of v3.0.2, though, lets see. Thanks!

**Comment by speckins** [comment]
I have encountered what seems to be the same issue while upgrading a Rails 3 project to Rails 4.2.  We're using Bootstrap 2.

This is produced in Rails 3 with simple_form 2.1.1:

```html
<div class="control-group check_boxes optional _action_action_state_types">
    <label class="check_boxes optional control-label">Action state types</label>
    <div class="controls">
        <label class="checkbox">
            <input checked="checked" class="check_boxes optional" id="_action_action_state_type_ids_1" name="_action[action_state_type_ids][]" type="checkbox" value="1" />Value #1
        </label>
        <label class="checkbox">
            <input checked="checked" class="check_boxes optional" id="_action_action_state_type_ids_2" name="_action[action_state_type_ids][]" type="checkbox" value="2" />Value #2
        </label>
        <input name="_action[action_state_type_ids][]" type="hidden" value="" />
    </div>
</div>

```

This is produced in Rails 4 with simple_form 3.4.0:

```html
<div class="control-group check_boxes optional _action_action_state_types">
    <label class="check_boxes optional control-label">Action state types</label>
    <div class="controls">
        <span class="checkbox"><!-- THIS IS NEW -->
            <label for="_action_action_state_type_ids_1">
                <input class="check_boxes optional" type="checkbox" value="1" name="_action[action_state_type_ids][]" id="_action_action_state_type_ids_1" />Value #1
            </label>
        </span>
        <span class="checkbox"><!-- THIS IS NEW -->
            <label for="_action_action_state_type_ids_2">
                <input class="check_boxes optional" type="checkbox" value="2" name="_action[action_state_type_ids][]" id="_action_action_state_type_ids_2" />Value #2
            </label>
        </span>
        <input type="hidden" name="_action[action_state_type_ids][]" value="" />
    </div>
</div>
```

This is the code used to render it:

```erb
<%= f.association :action_state_types, :as => :check_boxes, :collection => @action_state_types %>

```

config/initializers/simple_form*.rb are unchanged from when they were originally generated with simple_form 2.1.1.

I'm guessing that a new wrapper has been added to simple_form.  TBH, I've always found the simple_form setup API to be a bit confusing, and I'd appreciate a pointer in the right direction if you could.  Is there a way to turn off that <span> wrapper?

**Comment by speckins** [comment]
Adding `item_wrapper_tag: false` causes the span tag to be omitted.  Adding `item_label_class: 'checkbox'` returns the "checkbox" class to the label tag.

I still need to figure out how to add this to the default configuration so it doesn't need to be added to every collection of checkboxes.
