### ISSUE TITLE
merge_wrapper_options - missing keys

### ISSUE THREAD

**Issue by unijewski** [plataformatec/simple_form#1278]
Maybe it's just a misunderstanding but I've figured out something wrong with `merge_wrapper_options` based on this pull request: https://github.com/hughevans/pagedown-bootstrap-rails/pull/11 As you can see we lost the keys after using the method. Shouldn't we consider this case?

Comments are welcome.

**Comment by rafaelfranca** [comment]
Indeed it is a bug. Thank you for reporting
