### ISSUE TITLE
disabled: false disables the second value in a radio buttons input

### ISSUE THREAD

**Issue by GeorgeDewar** [plataformatec/simple_form#1282]
Hi there,

Given the following code (where "disabled" is a variable that may be true or false):

`f.input :my_boolean_field, as: :radio_buttons, disabled: disabled`

If disabled is equal to `true`, both Yes and No are disabled, while if disabled is set to `false`, the No option is still disabled. If the disabled option is not present, neither option is disabled (which is what I expect if disabled is set to `false`).

I have worked around the issue with the following, to omit the disabled key entirely if it is false:

`f.input :my_boolean_field, { as: :radio_buttons }.merge(disabled ? { disabled: true } : {})`

I am using version 3.1.0.

**Comment by carlosantoniodasilva** [comment]
It seems related to #1257 and the readonly option, please take a look at the conversation there to get some background on this. Thanks!

**Comment by GeorgeDewar** [comment]
Ah, thanks very much!

**Comment by brendon** [comment]
Just encountered this. It does seem similar to the `readonly` issue except that I've disabled that in my config and this still happens. @GeorgeDewar, I know it was 7 years ago but do you remember what you ended up doing, or did you continue to work around?

**Comment by brendon** [comment]
Ok, so the solution was pretty simple, I just passed the `disabled` attribute in `input_html: { disabled: false }`. That seems to make it down to the individual radio buttons instead :)

Still looks like a bug though :)
