### ISSUE TITLE
Access eager loaded attributes in association fields?

### ISSUE THREAD

**Issue by screenager** [plataformatec/simple_form#1285]
Hello, I'm very new to Rails and this gem,
but say you have checkboxes built this way
```
= f.association :recipes, as: :check_boxes, input_html: { class: 'test' }
```

is it possible to instead of 'test', render an attribute of my recipes model (eager loaded) ?

Or do I have to build it myself like in https://github.com/plataformatec/simple_form/issues/609  ?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
