### ISSUE TITLE
f.button uses I18n scope of pl.helpers.submit.update instead of model based update

### ISSUE THREAD

**Issue by duart** [plataformatec/simple_form#1288]
Example:
pl.helpers.submit.update
instead of 
pl.helpers.submit.user.update
Code from bootstrap examples  mixed with my own (see different texts on buttons):

pl.yml (properly nested, it only looks like same level here):
  helpers:
    select:
      prompt: Proszę wybrać
    submit:
      create: Utwórz %{model}
      submit: Zapisz %{model}
      **update: Aktualizuj %{model}**
      user:
        create: Utwórz nowe konto
        submit: Zapisz konto
        **update: Aktualizuj konto**

form view code:
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading"></div>
    <div class="panel-body">
      <%= simple_form_for [:admin, @user], as: 'user_horizontal', html: { class: 'form-horizontal' },
        wrapper: :horizontal_form,
        wrapper_mappings: {
          check_boxes: :horizontal_radio_and_checkboxes,
          radio_buttons: :horizontal_radio_and_checkboxes,
          file: :horizontal_file_input,
          boolean: :horizontal_boolean
        } do |f| %>
          <%= f.input :email, placeholder: 'email' %>
          <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

<div class="clearfix"></div>
<div class="panel panel-info">
  <div class="panel-heading"></div>
  <div class="panel-body">
    <%= form_for [:admin, @user], :html => { :class => "form-horizontal" } do |f| %>
      <div class="form-group">
        <%= f.label :email, :class => 'col-sm-3 control-label' %>
        <div class="col-sm-4">
          <%= f.text_field :email, :class => 'form-control' %>
        </div>
        <%= error_span(@user[:email]) %>
      </div>
      <%= f.submit nil, :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>
![rails](https://cloud.githubusercontent.com/assets/2326490/8941638/f97e3e58-3570-11e5-8b0b-7ad79fba34c2.jpg)

**Comment by carlosantoniodasilva** [comment]
The `submit` helper is provided by Rails, not Simple Form. Our `button` implementation just delegates to Rails (and I see you're using just `f.submit`, so it's the bare Rails helper, it does not go through Simple Form).

According to [their docs](http://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-submit), it should work, but maybe your [`object_name`](https://github.com/rails/rails/blob/9f44aa08636dfbba9261f4350ec14684425c4b7b/actionview/lib/action_view/helpers/form_helper.rb#L1884) is not just `:user`, but something like `'admin/user'`? Try printing out the value of `f.object_name` for instance, and you'll see.

Hope that helps.

**Comment by duart** [comment]
Yo are right - as: "..." in form_for overwrites model name (in input names in html) and that was the reason.
Thanks for help!!!
