### ISSUE TITLE
Gem release

### ISSUE THREAD

**Issue by arturoherrero** [plataformatec/simple_form#1297]
Can you do a new gem release, please? The last one is from 25th November 2014
https://rubygems.org/gems/simple_form

Thank you.

**Comment by lucasmazza** [comment]
There wasn't much activity on the repo to require a new release right away, but I guess that what we have on `master` right now could be a nice `3.1.1`. Any thoughts @rafaelfranca @carlosantoniodasilva? I can cut the release later today.

**Comment by carlosantoniodasilva** [comment]
Sounds good to me :+1:

**Comment by lucasmazza** [comment]
`3.1.1` is out :heart:
