### ISSUE TITLE
[Feature Request] Be able to have custom input with block

### ISSUE THREAD

**Issue by PikachuEXE** [plataformatec/simple_form#1298]
In [`SimpleForm::FormBuilder#find_input`](https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/form_builder.rb#L500)
The built-in `BlockInput` is **always** picked when a block is given
So if I am trying to create a custom input class that accepts a block, it will never be picked up even I specify the name in option `as`.
Can `#find_input` respect the value in `as` first, then pick `BlockInput` if `as` is not provided & block given?

**Comment by rafaelfranca** [comment]
Could you explain what are you trying to do with a custom input class that accepts a block? The way simple form as designed is that if you provide a block to the input call the wrapper for the input is going to be used but the content is rendered with the code that is used in the block. Changing this will be a huge backward incompatible change.

**Comment by PikachuEXE** [comment]
Already forgot what I am trying to do
Closing this
Thanks for looking at this anyway ;)
