### ISSUE TITLE
Simpleform is too slow, when i18n is not used

### ISSUE THREAD

**Issue by JelF** [plataformatec/simple_form#1299]
I18n is good and powerfull thing, but also is a bottleneck for simpleform. When no translations given, it realy slows down simpleform.

We swithced to simpleform with a forms, that have a huge amount of inputs in admin panel, but without i18n translations. On development version, it took 1200 ms to render. With profiler we found a bottleneck with about 1600 calls to `ActionView::Helpers::TagHelper#translate`. After disabling `Simpleform::Inputs::Base#translate_from_namespace`, render speeded up to 300 ms

I can suggest solution by caching translate_from_namespace with key 
```
"simpleform-translate_from_namespace-#{joined_model_names}-#{lookup_action}-#{reflection_or_attribute_name}"
```
or something similar

**Comment by brocktimus** [comment]
I ran into this same issue. There is already some discussions and potential debug / fixing going on at #1227 so see if any of that helps you too!

**Comment by carlosantoniodasilva** [comment]
Closing in favor of #1227, please feel free to post any relevant information in there. Thank you.
