### ISSUE TITLE
Install hangs when project name has a dash (ex: project-name)

### ISSUE THREAD

**Issue by tostasqb** [plataformatec/simple_form#1302]
When starting a new project, if the the project name has a dash in the name (ex: project-name) running `rails generate simple_form:install` will hang forever.

Using latest gems and ruby version.

Had a ball with this one

**Comment by tostasqb** [comment]
actually this is not a pattern...figuring this one out still

**Comment by tostasqb** [comment]
got ahead of myself, restarting terminal session for some reason unblocked this

**Comment by cimm** [comment]
FYI: I had the same problem. Restarting terminal did the trick.
