### ISSUE TITLE
Can't get images to display

### ISSUE THREAD

**Issue by yifeiwu** [plataformatec/simple_form#1306]
Using Rails 4.1 

The upload is fine but the view code does not work.

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by yifeiwu** [comment]
To reproduce, I followed the instructions on the readme.

**Comment by rafaelfranca** [comment]
Which instructions? There are a lot of instructions on readme but none of them are related to images.

**Comment by yifeiwu** [comment]
oops my mistake please ignore. Posted in wrong window/project
