### ISSUE TITLE
Predefined attributes (`type`, `required` etc.) are lost when `Base#input_html_options` is modified from within the `app/inputs`

### ISSUE THREAD

**Issue by jibiel** [plataformatec/simple_form#1308]
Greetings, gentlemen.

I'm DRYing up my forms and noticed that my email fields are obtaining `type="text"` rather than `type="email"` after that:

``` ruby
class StringInput < SimpleForm::Inputs::StringInput
  def input_html_options
    case input_type
    when :email
      super.reverse_merge autofocus: true
    else
      super
    end
  end
end

```

So I need to explicitly define it again:

``` ruby
super.merge(type: :email).reverse_merge autofocus: true
```

I wasn't able to find any notes on that and am wondering if that's an expected behavior.

```
rails (4.2.4)
simple_form (3.2.0)
```

**Comment by jibiel** [comment]
The same goes for `required="required"` (it disappears), I'm guessing it's not a correct way to specify attribute defaults in the `app/inputs`?

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
