### ISSUE TITLE
Future support for _html translations?

### ISSUE THREAD

**Issue by oniofchaos** [plataformatec/simple_form#1310]
My app uses these translations in multiple places for simple form. I noticed in the latest (3.2.0) version, support for this was removed. Is support going to be added back in? I don't want to miss out on future updates :cry:

**Comment by josevalim** [comment]
It won't be added back because it was responsible for a drastic performance hit in Simple Form and your app was probably being way slower than it was supposed to. You will have to explicitly pass t("...") for the fields you need html support.
