### ISSUE TITLE
Reapply 'Translate the attributes prefixed with _html to keep the html markup.'

### ISSUE THREAD

**Issue by timoschilling** [plataformatec/simple_form#1311]
My benchmarks showing that #1024 don't slowing down the rendern since @josevalim switched from `t` to `I18n.t` in 6ba68fc42efcdf3290d3fd4bcc2fa3ab769b6e89.
So I think #1024 can be reapplyed.

**Comment by rafaelfranca** [comment]
Could you share the benchmarks? `_html` only works with `t` and don't work with `I18n.t` so if we want to reapply this behavior we will need to change to `t` what I think will re-add the performance regression.

**Comment by timoschilling** [comment]
Ok, I don't have test the functionality of `_html` with `I18n.t` only the speed if the key exists.
