### ISSUE TITLE
Submit button doesn't work with label which contains non-english characters

### ISSUE THREAD

**Issue by szekelyadam** [plataformatec/simple_form#1313]
Hi

Recently I noticed, that if I use non-english characters in a submit button label, than it won't work. It doesn't get any errors or something, just doesn't work. 
For example:

```
<%= f.submit %>
```

It's okay, works perfectly.

```
<%= f.submit 'Mentés' %>
```
This one renders correctly, but nothing happens.
If I correct it to this
```
<%= f.submit 'Mentes' %>
```
than it's perfect again.

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by szekelyadam** [comment]
Sorry it was something with turbolinks, and nothing with simple form or special characters.
