### ISSUE TITLE
SimpleForm leaks the formatting function into HTML

### ISSUE THREAD

**Issue by trevorplant** [plataformatec/simple_form#1314]
When overriding the `label_text` per input like so:

```
form.label :name, label_text: proc { |label_text, required, _| "#{label_text} #{required}" }
```

The generated HTML has:

```
<label label_text="#<Proc:0x007fe268b21ce8@/Users/foo/boo/_new_form.html.slim:4>" class="string required" for="user_attributes_name">Name <abbr title="required">*</abbr></label>
```

As you can see it includes the full path to the custom proc function location which is a security issue.

This happens with versions `3.1.0` and `3.1.1.`

\cc @dnagir

**Comment by rafaelfranca** [comment]
Yeah, we should fix this one.
