### ISSUE TITLE
 Simple Form throws error when running Rake task on directory of Suspenders gem

### ISSUE THREAD

**Issue by Fourfingerz** [plataformatec/simple_form#1316]
This is a crossover issue from Simple Form running it from the Suspenders gem (SimpleForm is included in that package). 

When I ran rake on the suspenders directory, I saw this error message produced 11 times:

> "Simple Form is not configured in the application and will use the default values. Use rails generate simple_form:install to generate the Simple Form configuration."

Running rake on a fresh suspenders generated Rails directory doesn't throw the aforementioned simple form error. It is only when I run rake on the cloned repo that throws that error. 

I'm just trying to isolate this issue and see to the bottom of it if it's a bug in Simple_form or with Suspender.  @tute

**Comment by rafaelfranca** [comment]
It is an issue in your cloned repository. Simple Form warns about the absent of the `config/initializer/simple_form.rb` file, but it is not an error. You can continue your program even if you see that message, but we recommend you to create that file.

**Comment by Fourfingerz** [comment]
@tute I think that's a good clue to walk with you through tonight to fix it for the suspenders gem. 
@rafaelfranca Thanks for the tip! This will help us fix this issue for suspenders.

**Comment by tute** [comment]
@rafaelfranca: the surprising thing with this warning is that it's shown even when running `rails generate simple_form:install` which copies that file. It's weird that it warns you to do what you are now doing, and that looks like a bug to me.

**Comment by rafaelfranca** [comment]
:+1: that is indeed a bug.

**Comment by tute** [comment]
@Fourfingerz what are you waiting to fix it! :smiley: :+1:

**Comment by Fourfingerz** [comment]
Yes! Thank you @tute

**Comment by Fourfingerz** [comment]
After some brief exploration of the Simple_Form repo, I believe that the origin of that error message comes from these two places.

 simple_form/lib/simple_form/components/label_input.rb:
```
   21          method = method(namespace)
   22  
   23:         if method.arity == 0
   24            ActiveSupport::Deprecation.warn(SimpleForm::CUSTOM_INPUT_DEPRECATION_WARN % { name: namespace })
   25  
```

 simple_form/lib/simple_form/wrappers/leaf.rb:
```
   12          method = input.method(@namespace)
   13  
   14:         if method.arity == 0
   15            ActiveSupport::Deprecation.warn(SimpleForm::CUSTOM_INPUT_DEPRECATION_WARN % { name: @namespace })
```

Perhaps a condition can be add that if ```rails generate simple_form:install``` is run and everything is a go, we can have these two Deprecation warnings turned off?

**Comment by rafaelfranca** [comment]
The place where that message is generated is at https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/railtie.rb#L9. Yes, we need a way to detect if the command is generator so we don't print the warn.

**Comment by feliperenan** [comment]
Is this still an issue?

**Comment by feliperenan** [comment]
I'm gonna close this PR since it has been while and I don't know if it still is an issue.

Thanks
