### ISSUE TITLE
Default empty string in SimpleForm::Inputs::Base.translate_from_namespace breaks Rails I18n

### ISSUE THREAD

**Issue by mvastola** [plataformatec/simple_form#1322]
[This](https://github.com/plataformatec/simple_form/blob/e81af052f4bbe9e17e38c668116cd1846c6d275c/lib/simple_form/inputs/base.rb#L185) line of code is problematic if the variable `default` is not otherwise defined and thus defaults to an empty string while the `i18n` gem is in use. 

If this is the case, the following partial stacktrace will result and an `ArgumentError` will occur within (current) version 0.7.0 of the `i18n` gem if no translations/localizations exist yet for the placeholder and locale in question.
```
I18n::ArgumentError - I18n::ArgumentError:
  i18n (0.7.0) lib/i18n.rb:152:in `translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:69:in `translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:39:in `translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:39:in `translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:39:in `translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:39:in `translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:39:in `translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:39:in `translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:39:in `translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
  actionview (4.2.5) lib/action_view/helpers/translation_helper.rb:39:in `translate'
  simple_form (3.1.1) lib/simple_form/inputs/base.rb:191:in `translate_from_namespace'
  simple_form (3.1.1) lib/simple_form/components/placeholders.rb:12:in `placeholder_text'
  simple_form (3.1.1) lib/simple_form/components/placeholders.rb:6:in `placeholder'
  simple_form (3.1.1) lib/simple_form/wrappers/leaf.rb:19:in `render'
  simple_form (3.1.1) lib/simple_form/wrappers/many.rb:28:in `block in render'
  simple_form (3.1.1) lib/simple_form/wrappers/many.rb:26:in `render'
  simple_form (3.1.1) lib/simple_form/wrappers/root.rb:15:in `render'
  simple_form (3.1.1) lib/simple_form/form_builder.rb:116:in `input'
```

`ActionView::Helpers::TranslationHelper`, in an attempt to find a translation for the placeholder, will attempt to look up each of the translation keys in the array named `lookup` (defined in `SimpleForm::Inputs::Base.translate_from_namespace`) in order, until it finds a match. If it reaches the final value in the array though -- an empty string -- [L152 in `i18n.rb`](https://github.com/svenfuchs/i18n/blob/b1200f0289a59ba0368f800473d8ac79f713bc26/lib/i18n.rb#L152), however, states `raise I18n::ArgumentError if key.is_a?(String) && key.empty?`.

**Comment by mvastola** [comment]
FYI: This workaround does it for me. Can't speak to if it breaks anything else though.
```
require 'simple_form/inputs/base'
module I18n
  module SimpleFormFix
    def translate_from_namespace(namespace, default = nil)
      super(namespace, default)
    end
  end
end
SimpleForm::Inputs::Base.prepend(I18n::SimpleFormFix)
```

**Comment by nashby** [comment]
@mvastola hmm, that's strange. IIRC 
```ruby
I18n.t("blah", default: [""])
```

won't raise any exception. Exception will be there only if you pass empty string to the `t` method directly, not in the default array. So I'm not really sure why it happens to you since there are always something in the `lookups` array besides empty string. Can you please provide simple application that reproduces this error? Thanks!

**Comment by mvastola** [comment]
@nashby The issue is that the version of SimpleForm I was using didn't scope the I18n module directly and instead just called the method `t` which was defined in the `ActionView::Helpers::TranslationHelper` module. `ActionView::Helpers::TranslationHelper#translate`, in turn, calls `I18n.t`.

I'm just noticing now that commit 6ba68fc, tagged for release 3.2.0 changes this behavior. I had `gem 'simple_form', '~> 3.1.0'`in my `Gemfile` so I'll upgrade SimpleForm and see if the issue persists. 

(I had searched for similar issues before creating this one, but I'm guessing the commit was made before anyone had this issue. Either that or I can't search -- a perfectly likely scenario.)

**Comment by mvastola** [comment]
@nashby Ok. Yea. Upgrading to SimpleForm v3.2.0 did the trick, so I'll close this out.
Thanks a ton for your help!

**Comment by nashby** [comment]
@mvastola nice, I'm glad I was able to help!
