### ISSUE TITLE
HH : MM : AM/PM time select, in 3 select boxes?

### ISSUE THREAD

**Issue by gregblass** [plataformatec/simple_form#1328]
I can't believe there is no information about this in google at all, let alone just in simpleform. I get why the default for time_select is to output in military time (most of the world uses this). But, pass in the ampm option and it is formatted like: HH PM : MM, with the AM/PM included in the first select box. 

This bewilders me as to why someone would program it like that. I've never seen this, ever, at least not in the USA. Is this a normal design pattern in other countries? It certainly is not in the USA.

I just want my time select to be like HH (blank padded, like 3 or 12, not 03) : MM : AM/PM - in 3 separate select boxes.

![time](https://cloud.githubusercontent.com/assets/279927/11564897/913d2d16-99a9-11e5-81de-c93efb9c9f45.png)

But I rest my case as to the rails core - back to simpleform: Is there a way to output a time select in that format?

**Comment by gregblass** [comment]
I was able to accomplish this manually (without simpleform) with the following code (if the form object is 'derp'):

    <div class="timepicker">
		<select class="hour form-control" name="derp[hour]">
			<option value="1">1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
			<option value="6">6</option>
			<option value="7">7</option>
			<option value="8">8</option>
			<option value="9">9</option>
			<option value="10">10</option>
			<option value="11">11</option>
			<option value="12">12</option>
		</select>
		<span class="colon">:</span>
		<select class="minute form-control" name="derp[minute]" >
			<option value="00">00</option>
			<option value="15">15</option>
			<option value="30">30</option>
			<option value="45">45</option>
		</select>
		<select class="meridiem form-control" name="derp[meridiem]" >
			<option value="AM">AM</option>
			<option value="PM">PM</option>
		</select>
	</div>

Then in the derp model:

    attr_accessor :hour, :minute, :meridiem

    after_validation :parse_time

    def parse_time
		if hour and minute and meridiem
			self.time = DateTime.parse("#{hour}:#{minute}#{meridiem}") 
		end
	end

I have to make the values stick on an edit still.

**Comment by stonewallthomas** [comment]
Thanks for posting your solution and saving me some time.  It's absolutely crazy the way **ampm: true** behaves.  The time input should be fully customizable in Rails, just like the date is.
