### ISSUE TITLE
get form id withing custom input field definition

### ISSUE THREAD

**Issue by knagode** [plataformatec/simple_form#1329]
In custom input field I would like to get a reference to the table (id attribute of form element).  Is this possible?

    class DistanceInput < SimpleForm::Inputs::StringInput
      def input
        textfield_id = input_html_options[:id]
        form_id = ????????
        ...
      end
    end

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
