### ISSUE TITLE
Using :full_error in wrapper causes empty divs for f.error and f.full_error

### ISSUE THREAD

**Issue by jeremysmithco** [plataformatec/simple_form#1330]
I noticed that if I have a wrapper using :full_error instead of :error, and I then call f.error or f.full_error in my form, the form builder will add an empty div in the markup when first rendering the form.

If I switch back to using :error in my wrapper, calling f.error or f.full_error in the form does not add empty divs. (Empty divs wouldn't be a huge deal, except that I add a class to them with margins set, and that adds extra space when they are empty.)

Here's a how to reproduce it:

SimpleForm config:

```
SimpleForm.setup do |config|
  config.wrappers :default do |b|
    b.use :label_input
    b.use :full_error, wrap_with: { tag: :span }
  end

  config.default_wrapper = :default
end
```

A form which will render errors on base and the full_error on email:

```
<%= simple_form_for @user do |f| %>
  <%= f.error :base %>

  <%= f.input :email %>
  <%= f.full_error :email %>

  <%= f.button :submit %>
<% end %>
```

This will render the following markup:

```
<form accept-charset="UTF-8" action="/users" class="simple_form new_user" id="new_user" method="post">
  <div style="display:none">
    <input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="fN+dzDMck0PT1MzL9DdVLVdjsVTrEXc7y2VvNq27hMo=" />
  </div>
  <div></div>

  <div class="email required user_email">
    <label class="email required" for="user_email"><abbr title="required">*</abbr> Email</label>
    <input class="string email required" id="user_email" name="user[email]" type="text" />
  </div>
  <div></div>

  <input class="button" name="commit" type="submit" value="Create User" />
</form>
```

If I switch the :default wrapper to `b.use :error`, the problem will go away. (And when errors are rendered, they will be within span tags, as specified in `:wrap_with`.)

**Comment by feliperenan** [comment]
I don't know if it's an issue yet, so I'm closing it. Feel free to reopen it if necessary.
