### ISSUE TITLE
Add generator for bootstrap4

### ISSUE THREAD

**Issue by tordans** [plataformatec/simple_form#1336]
Bootstrap 4 will be there soon and some form related things changes.
For a list of changes see http://v4-alpha.getbootstrap.com/migration/#forms

Please add a new generator for bootstrap4. 

Maybe as a new option `rails generate simple_form:install --bootstrap4`? Also a note/warning at the end of the default "--bootstrap" call would be got, something like "You just generated the form styles for bootstrap3. Should you require bootstrap4 styles, re-run the generator with rails "generate simple_form:install --bootstrap4 --force"."
# Update:

I started the work over here, please feel free to pick it up https://github.com/plataformatec/simple_form/pull/1337

**Comment by tordans** [comment]
There is new information about one of the open details at https://github.com/twbs/bootstrap/issues/18705#issuecomment-168248128

> class="form-group" should be changed to class="form-group row"

**Comment by casey-stinnett** [comment]
Is this going to be added as an option? I would like to see this made as Bootstrap 4 is very nice with flexbox additions.

**Comment by djforth** [comment]
As bootstrap 4 is officially released would seem like a good time to update bootstap generator?

**Comment by wakiki** [comment]
+1 Bootstrap 4 official version is now released. 

Are there plans to support this or has anyone done this already? New to simple_forms as been using formtastic, but a bit surprised that BS4 isn't supported already. I could potentially do this but looking at previous comments it looks like some changes to simple_form internals are required to support the changes...

**Comment by cspshadx** [comment]
any updates on this?

**Comment by fleck** [comment]
This would be great to have bootstrap 4 support. Booleans currently don't render correctly.
<img width="386" alt="screen shot 2018-02-07 at 9 51 56 pm" src="https://user-images.githubusercontent.com/1706321/35953145-44e74d8a-0c51-11e8-812f-e41e1902e71e.png">

**Comment by tegon** [comment]
The direction we intend to follow is to decouple simple form from any CSS framework, so that specific gems can be created to support them better.
Please take a look at https://github.com/plataformatec/simple_form/pull/1337#issuecomment-350709787

**Comment by feliperenan** [comment]
Closing it since we won't add support to Bootstrap 4.

We are working on [simple_form-boostrap](https://github.com/rafaelfranca/simple_form-bootstrap/pull/56) to update to Bootstrap 4 and making Simple Form flexible to support it. Feel free to join to us.

Thanks

**Comment by tordans** [comment]
@feliperenan its great to see progress in this other repo. However, I still think this Repo should have an open issue that people can find and understand whats going on. This repo still needs to be updates about bootstrap 4, eg:
- Update readme https://github.com/plataformatec/simple_form#bootstrap about Bootstrap 4.
- Make it clear somewhere, what the new policy about code changes to simple_form for other frameworks is.
- Remove or rename the 'bootstrap' generator which is misleading.

Also, https://github.com/rafaelfranca/simple_form-bootstrap/pull/56 seems to be depending on some special version of simple form (see https://github.com/rafaelfranca/simple_form-bootstrap/pull/56/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R72). So are there plans now to merge external changes into simple_form? In one of those open tickets the questions was answered with 'no'.

**Comment by m5o** [comment]
> Also, rafaelfranca/simple_form-bootstrap#56 seems to be depending on some special version of simple form (see https://github.com/rafaelfranca/simple_form-bootstrap/pull/56/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R72).

This is just temporary and for demo purposes, including a feature request (https://github.com/plataformatec/simple_form/pull/1559) about having `valid_class` on input elements also which now has it's own PR.

![valid_class](https://user-images.githubusercontent.com/26371/37863917-cbb4ee70-2f66-11e8-9908-2dc89bba6719.gif)

**Comment by m5o** [comment]
Looking forward to see a PR from you. Open source also means reacting and not complaining. ✌️

**Comment by technodrome** [comment]
Excuse me, gentlemen, for commenting in a closed topic but I (and I believe many other users) will find this situation highly confusing. What is the best course of action here? I use Bootstrap 4 in my app. This will not change. Can I use just helper methods from simple_form (e.g. simple_form_for) to leverage simplified field generation but wrap the generated code in my manually written Bootstrap 4 code in views - that means no initializers?

Sorry for asking probably an obvious question but I do not see any straightforward answer. Thank you.

**Comment by feliperenan** [comment]
@tordans  For me, the issue (Add generator for Bootstrap 4) was resolved so we can keep it closed.

I agree with you, we have some work to do about Bootstrap and I include the Foundation as well. IMHO we can remove the initializers and definitely remove the support for it, but I want to see other opinions about it. I will open another issue explaining the motivations and we can discuss it there.

@technodrome  You can use Simple Form with Bootstrap 4 but some things maybe will not work, we are working on it - making Simple Form flexible enough to work with any CSS framework. When we talk about don't support Bootstrap anymore, we are talking about Simple Form generating the configuration out-of-the-box.
