### ISSUE TITLE
f.association doesn't work

### ISSUE THREAD

**Issue by RisuToriso** [plataformatec/simple_form#1338]
Hi! 
I'm new to RoR and desperate. I don't know why my association doesn't work... I get this error : "Association :adaptation not found"
I have two models : Book and Adaptation.

Here's my code :

Book.rb :
class Book < ActiveRecord::Base
	has_many :adaptations
end

Adaptation.rb :
class Adaptation < ActiveRecord::Base
	belongs_to :book:
end

Book > index.html.erb
<td><%= book.adaptations %></td>
Book > _form.html.erb
 <%= f.association :adaptation %>       (I tried with :adaptations with no consequence)

Adaptation > index.html.erb
<td><%= adaptation.book %></td>
Book > _form.html.erb
 <%= f.association :book %>

I create a migration :
class AddBookToAdaptation < ActiveRecord::Migration
  def change
    add_column :adaptations, :book, :has_many
  end
end

thanks for your time and help :)

**Comment by ESouza** [comment]
were you able to run this migration?

**Comment by RisuToriso** [comment]
I can't gist my actual migration/models because I am in bitbucket and I don't know how to change...

For the migration I run this : $ bundle exec rails g migration AddAdaptationToBook adaptation:belongs_to

And my models are :

Book.rb :
class Book < ActiveRecord::Base
has_many :adaptations
end

Adaptation.rb :
class Adaptation < ActiveRecord::Base
belongs_to :book
end

**Comment by ESouza** [comment]
ok and I am assuming you did run rake db:migrate correct?

**Comment by RisuToriso** [comment]
Yes, the migration worked (but not the association), but new problem... I tried many things and deleted this migration, I recreated it but this time I have an error in my console :
 == 20151229221055 AddAdaptationToBook: migrating ==============================
-- add_reference(:books, :adaptation, {:index=>true, :foreign_key=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: duplicate column name: adaptation_id: ALTER TABLE "books" ADD "adaptation_id" integer/Users/alicetrinh/CineBook/db/migrate/20151229221055_add_adaptation_to_book.rb:3:in `change'
ActiveRecord::StatementInvalid: SQLite3::SQLException: duplicate column name: adaptation_id: ALTER TABLE "books" ADD "adaptation_id" integer
/Users/alicetrinh/CineBook/db/migrate/20151229221055_add_adaptation_to_book.rb:3:in `change'
SQLite3::SQLException: duplicate column name: adaptation_id
/Users/alicetrinh/CineBook/db/migrate/20151229221055_add_adaptation_to_book.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

I don't understand a thing...

**Comment by ESouza** [comment]
Ok you deleted the migration without rolling back. So now when you try running the migration again is complaining that the adaptation_id column already exists on your database. 

Revert your deleted file back and run rake db:rollback.

**Comment by carlosantoniodasilva** [comment]
@RisuToriso @ESouza if you don't mind, I'm gonna ask you to move this conversation to the mailing list, as it seems not to be a SF issue so far (also there will be more people there to help). If you determine that's a real issue, I'm happy to reopen the issue here if you can provide some steps to reproduce, or a sample app that shows the problem. Thanks!

**Comment by ESouza** [comment]
Yes I was going to suggest that. Thanks
