### ISSUE TITLE
Horizontal Foundation Label Alignment

### ISSUE THREAD

**Issue by cavpollo** [plataformatec/simple_form#1339]
The classes used for the horizontal_form' label are `right inline`
https://github.com/plataformatec/simple_form/blob/master/lib/generators/simple_form/templates/config/initializers/simple_form_foundation.rb#L32

But according to the Foundation documentation (http://foundation.zurb.com/sites/docs/forms.html#label-positioning) it should be using the class `text-right` instead of `right`

**Comment by feliperenan** [comment]
It looks like you are right. Feel free to open a pull-request with this change :)
