### ISSUE TITLE
Collection Across Multiple Columns

### ISSUE THREAD

**Issue by colinramsay** [plataformatec/simple_form#1343]
When using collections or associations, for example like this:
```
<%= f.association :property_attributes, as: :check_boxes %>
```

If there are a lot of `property_attributes` then you end up with a really long list. I'd like to split these across multiple columns, but it's not immediately clear how I could do that. Is there a built-in way, or would it be a case of creating a custom input?

**Comment by lucasmazza** [comment]
> Is there a built-in way, or would it be a case of creating a custom input?

There isn't a built-in way. You can achieve this through the Wrapper API configuration and some CSS to set specific dimensions for each entry of the list.

**Comment by colinramsay** [comment]
Fair enough, thanks.

**Comment by joshm1204** [comment]
Any examples of this?
