### ISSUE TITLE
Form's class in html is a Ruby array 

### ISSUE THREAD

**Issue by peterlouis** [plataformatec/simple_form#1348]
Version: 3.2.1

In form_helper.rb, the method simple_form_for seems to be missing a "join" after the "compact" call.

        if options[:html].key?(:class)
          options[:html][:class] = [SimpleForm.form_class, options[:html][:class]].compact
        else
          options[:html][:class] = [SimpleForm.form_class, SimpleForm.default_form_class, simple_form_css_class(record, options)].compact
        end

The consequence is that in the html, you end up with something like this:

  &lt;form accept-charset="UTF-8" action="/account/signup" class="[:simple_form, &quot;new_user&quot;]" id="new_user" method="post"&gt;

**Comment by carlosantoniodasilva** [comment]
Rails handles converting the array form to a joined string in this case, so I think that's ok. Which Rails version are you using?

**Comment by peterlouis** [comment]
You're right. It turned out to be an interference by another gem called Ziya. Thanks.
