### ISSUE TITLE
Foundation 6 support

### ISSUE THREAD

**Issue by garshyn** [plataformatec/simple_form#1349]
I'm a fan of foundation 5 support by simple_form.
As long as foundaiton-rails gem is out supporting the major release, are you planning to support Foundation 6?

**Comment by josevalim** [comment]
If someone submits a pull request, we would likely accept it. After all, it is mostly supporting a new generated initializer file.

**Comment by yanyingwang** [comment]
maybe I'll do the foundation 6 pull request later.

**Comment by jensb** [comment]
Any news on Foundation 6 support? What would need to be done?

**Comment by dgilperez** [comment]
Any updates?

**Comment by sigu** [comment]
Foundation 6 support? Still not available  :disappointed:

**Comment by atainton** [comment]
Any update?

**Comment by untidy-hair** [comment]
Still no official supports for Foundation 6?

**Comment by untidy-hair** [comment]
OK, looks like they stopped the support for css frameworks in general: https://github.com/plataformatec/simple_form/pull/1492
