### ISSUE TITLE
Duplicated html classes in radio button input

### ISSUE THREAD

**Issue by nazarok** [plataformatec/simple_form#1352]
If the option `SimpleForm.browser_validations = true` and we have code such as:

```
<%= simple_form_for(:aaa, url: 'aaa', method: :post) do |f| %>
  <%=  f.input(:reason, as: :radio_buttons, collection: [[2,3], [3,4], [5,6]]) %>
<% end %>
```

we get:

```
<div class="input radio_buttons required aaa_reason">
  <label class="radio_buttons required">
    <abbr title="required">*</abbr>
    Reason
  </label>
  <span class="radio radio radio">
    <label for="aaa_reason_3">
      <input class="radio_buttons required" required="required" aria-required="true" type="radio" value="3" name="aaa[reason]" id="aaa_reason_3">*
    </label>
  </span>
...
</div>
```

duplicating classes:

`<span class="radio radio radio">`

because the method `apply_default_collection_options!` (https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/inputs/collection_radio_buttons_input.rb#L24) is performed 3 times

**Comment by malavikareddy2653** [comment]
<div class="input radio_buttons required aaa_reason">
  <label class="radio_buttons required">
    <abbr title="required">*</abbr>
    Reason
  </label>
  <span class="radio">
    <label for="aaa_reason_3">
      <input class="radio_buttons required" required="required" aria-required="true" type="radio" value="3" name="aaa[reason]" id="aaa_reason_3">*
    </label>
  </span>
...
</div>

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
