### ISSUE TITLE
Collection as grouped select order option

### ISSUE THREAD

**Issue by aalvarado** [plataformatec/simple_form#1353]
I was trying to create a select with `as: :grouped_select` and my options show up as how they get retrieved from the database. 

I was reviewing the code and seems there's no way to order the options from the markup, you would either need to create a scope with the right order or rely on something else like rails `option_groups_from_collection_for_select`. 

it would be nice to be able to send a method that would also sort them.

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
