### ISSUE TITLE
rails 4.2: input with association has wrong value string

### ISSUE THREAD

**Issue by philsmy** [plataformatec/simple_form#1354]
I've just upgraded an app to rails 4.2 (specifically 4.2.5.1) from 4.1.14.1.
I'm seeing odd behaviour with a hidden field on a form that I am using to stash an array of associated items.
Here's the code:
`<%= f.hidden_field :item_ids, :multiple => true %>`

On Rails 4.1.14.1 it produces this html:
`<input type="hidden" value="[21, 23, 49, 776]" name="email_template[item_ids][]" multiple="multiple" id="email_template_item_ids">`

under rails 4.2.5.1 it produces:
`<input type="hidden" id="email_template_item_ids" name="email_template[item_ids][]" value="21 23 49 776" multiple="multiple">`

As you can see, the value field is different.

perhaps this is a 'known' feature change. I can't see any difference in rails - both 4.1 and 4.2 produce an array:

``` ruby
2.1.5 :003 > email_template.item_ids
 => [21, 23, 49, 776] 
```

I 'fixed' it in my code by doing the following:
`<%= f.hidden_field :item_ids, multiple: true, value: "#{@email_template.item_ids}" %>`

I guess I am curious as to the cause of this and if indeed it is a bug.

**Comment by nashby** [comment]
hey @philsmy. Thank you for the detailed bug report. I'm afraid it's Rails issue though. I tracked it down to this PR https://github.com/rails/rails/pull/15654/. @rafaelfranca any thoughts on this? Not really sure if it's correct behaviour for Rails.

**Comment by Benjamin-Dobell** [comment]
I'm seeing:

```
= f.input :related_tag_ids, collection: relatable_tag_id_titles, label: 'Linked brand snap'
```

which is in a nested form, rendered as:

```
<select class="select optional" name="tag[related_tag_ids]" id="tag_related_tag_ids"><option value=""></option>
                  <option value="5332b103be332f7f3c00028f">Blah</option>
                  <option value="5356107abe332f40850001bf">Blah Blah</option>
                  <!-- etc. -->
</select>
```

When that's submitted I'm getting:

```
foo=bar&tag%5Brelated_tag_ids%5D=&bar=foo
```

Which when accessed in Rails in the params `Hash` it's a `String` instead of an `Array`.

Is this the same bug?

**Comment by Benjamin-Dobell** [comment]
Hmm, nope, something has changed but I don't believe it's the same thing. I had to migrate to:

```
f.association :related_tags, collection: relatable_tag_id_titles, label: 'Blah', as: :select
``

**Comment by feliperenan** [comment]
I don't know if it's an issue since it's been along time. I'm closing it but feel free to comment or reopen if necessary.
