### ISSUE TITLE
Simple Form Country Select always optional?

### ISSUE THREAD

**Issue by randomizor** [plataformatec/simple_form#1355]
I am using Foundation's abide validation for a form, which looks for the presence of the required attribute. However it appears that the country input doesn't allow you to set the attribute. Is there a particular reason for this? It's inconvenient as a number of validation plugins/frameworks utilise that attribute. 

I'd prefer to use the country select than building my own with countries, so the priority option can be set.

**Comment by carlosantoniodasilva** [comment]
As far as I remember, the `required` option for selects has a few rules, including having an empty option as its first option on the list. Check [this post](http://maxdesign.com.au/articles/select-required/) for some explanation. Simple Form [tries to honor that](https://github.com/plataformatec/simple_form/blob/ac63da0f0b38df82385493f25f649e320b0acb4a/lib/simple_form/inputs/collection_input.rb#L39-L41), so you either need to pass `include_blank` or a `prompt` option for the `required` option to be enabled.

Let us know if that answers your question. Thanks!

**Comment by randomizor** [comment]
I read through that and understand that. However, for the priority inputs it doesn't seem to adhere to those rules?
```
module SimpleForm
  module Inputs
    class PriorityInput < CollectionSelectInput
      
      ...

      def has_required?
        false
      end

      ...

    end
  end
end
```
