### ISSUE TITLE
integrating with refile

### ISSUE THREAD

**Issue by chrishough** [plataformatec/simple_form#1356]
Has anyone integrated with refile https://github.com/refile/refile/issues/434?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by chrishough** [comment]
In case anyone comes across this, here is the SO Post: http://stackoverflow.com/questions/35285939/refile-simple-form-undefined-method-attachment-field/
