### ISSUE TITLE
Problem generating correct custom wrapper

### ISSUE THREAD

**Issue by eoliphan** [plataformatec/simple_form#1357]
Hi, I'm using simple form with the Semantic UI framework.  I grabbed a simple form initializer for semantic from github that's doing most of what I need.  However, I'm running into an issue with generating the correct HTML for a required checkbox, and my fiddling with the initializer isn't getting the desired result.  

This is basically what I need to generate:

```
<div class="required inline field">
      <div class="ui checkbox">
        <input type="checkbox" tabindex="0" class="hidden">
        <label>I agree to the terms and conditions</label>
      </div>
    </div>
```

This is what's getting generated:
```
<div class="inline field boolean required investor_profile_terms_ack">
   <div class="ui checkbox">
      <input name="investor_profile[terms_ack]" type="hidden" value="0" />
      <input class="boolean required" type="checkbox" value="1" name="investor_profile[terms_ack]" id="investor_profile_terms_ack" />
      <label></label>
   </div>
   <label class="boolean required" for="investor_profile_terms_ack">Read Investor Terms &amp; Disclosures?</label>
</div>
```

By this custom wrapper
```
config.wrappers :semantic_checkbox, tag: 'div', class: "inline field", error_class: 'error', hint_class: 'with_hint' do |b|
    b.use :html5
    b.wrapper tag: 'div', class: 'ui checkbox' do |input|
      input.use :input
      input.wrapper tag: 'label' do |box| end
    end
    b.use :label
  end
```

My problem is getting the Label with the actual label text, inside the 'ui checkbox' div.  I tried modifying the wrapper as follows:
```
config.wrappers :semantic_checkbox, tag: 'div', class: "inline field", error_class: 'error', hint_class: 'with_hint' do |b|
    b.use :html5
    b.wrapper tag: 'div', class: 'ui checkbox' do |input|
      input.use :input
      b.use :label
    end
    
  end
```
That weirdly, got rid of the empty label, but then put the correct label _before_ the 'ui checkbox' div.   I've been over the api docs a few times, but not sure why I'm getting that behavior.   Any suggestions?

**Comment by rafaelfranca** [comment]
You code seems incorrect since you are using `b.use :label` instead of `input.use :label` inside your block. This is why it is being generated before the 'ui checkbox' div. I hope this helps.
