### ISSUE TITLE
Changing input label when attribute has error

### ISSUE THREAD

**Issue by Draiken** [plataformatec/simple_form#1359]
Hi there! I'm using Materialize css, and they have kind of an unique way of marking inputs as erroneous: they add `data-error` to the label with the string containing the error explanation

```
<div class="input-field col s12">
  <input id="email" type="email" class="validate">
  <label for="email" data-error="wrong">Email</label>
</div>
```

I couldn't find anything that alters other elements when errors happen, apparently errors either add classes, wraps html, but never adds html attributes.

Spent a bit of time reading through the inputs and the internals and couldn't find a good way to make this the default behavior.

I imagine if I subclass or override the `input` method on all inputs that should have this behavior to add the html attribute this should work, but I think that's not the best solution for this.

Any direction will help a lot. Thanks

**Comment by Draiken** [comment]
Solved by wrapping `label_html_options' method on `SimpleForm::Inputs::Base`

**Comment by barrymieny** [comment]
@Draiken would you mind sharing an example of what you did exactly?

**Comment by Draiken** [comment]
Yeah, I basically extended the internal method to add the invalid class if the attribute had an error and added the `data-error` with the error text

I'm not sure if this is the best solution, but I remember at the time I read quite a bit of the internal source code of SimpleForm and came to the conclusion that I had to do this, or create a whole new input type.

```
class SimpleForm::Inputs::Base
  def input_html_classes_with_error
    classes = input_html_classes_without_error
    classes << "invalid" if error
    classes
  end
  alias_method :input_html_classes_without_error, :input_html_classes
  alias_method :input_html_classes, :input_html_classes_with_error

  def label_html_options_with_error
    label_options = label_html_options_without_error
    error_text = error
    label_options['data-error'] = error_text if error_text.present?
    label_options
  end
  alias_method :label_html_options_without_error, :label_html_options
  alias_method :label_html_options, :label_html_options_with_error
end
```
