### ISSUE TITLE
:input_html broken in Rails 5.0.0.beta2

### ISSUE THREAD

**Issue by missioeric** [plataformatec/simple_form#1360]
The following code:

`<%= f.button :submit, input_html: { class: 'special' } %>`

creates the following html:

`<input type="submit" name="commit" value="Create dcycle" input_html="{:class="special"}" class="btn btn-primary" data-disable-with="Create dcycle">`

**Comment by rafaelfranca** [comment]
This is going to be handled in https://github.com/plataformatec/simple_form/issues/1395

**Comment by rafaelfranca** [comment]
`button` is not an wrapped component, you don't need to pass `input_html`. You can pass class directly to it:

```
<%= f.button :submit, class: 'special' %>
```

See https://github.com/plataformatec/simple_form#buttons
