### ISSUE TITLE
tooltip component on bootstrap input-group wrapper not showing

### ISSUE THREAD

**Issue by l0c0luke** [plataformatec/simple_form#1361]
Tooltip works fine on regular input.

`= f.input :size`

but if i use a wrapper following the default instructions for bootstrap and tooltips it does not work. I have to remove the `do` and use it without `f.input_field` to get it to work.

```
= f.input :peak_visibility, wrapper: :horizontal_input_group, label: 'Peak Audience Visibility' do
        = f.input_field :peak_visibility, class: 'form-control'
        %span{class: 'input-group-addon'} %
```

the tooltips are coming from a locale file thats why they are not explicitly shown here. 

the `horizontal_input_group` wrapper i modified is...

```
config.wrappers :horizontal_input_group, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.use :placeholder
    b.use :label, class: 'col-sm-4 control-label'
    b.use :tooltip

    b.wrapper tag: 'div', class: 'col-sm-8' do |ba|
      ba.wrapper tag: 'div', class: 'input-group col-sm-12' do |append|
        append.use :input, class: 'form-control'
      end

      ba.use :error, wrap_with: { tag: 'span', class: 'help-block' }
      ba.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
    end
  end
```

Is it possible to keep the tooltips and still have the input-groups?

**Comment by cireficc** [comment]
+1

**Comment by l0c0luke** [comment]
I created this as well to maybe get more exposure. http://stackoverflow.com/questions/35793164/simple-form-tooltip-component-on-bootstrap-input-group-wrapper-not-showing

**Comment by rafaelfranca** [comment]
What is the markup being generated and which markup should be generated?

**Comment by rafaelfranca** [comment]
Also I saw that tooltips are being generated by your custom code, so the problem may be there. If you could provide the markup being generated and the expected markup I could help with that.

**Comment by likelazyeyes** [comment]
Yes, nothing changes to html after tooltip. It's not generating any attibute in html tag. Are there anyone to fix and pr this.

**Comment by feliperenan** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please open up a new issue and make sure to fill in all the information requested in the template shown inside the text box. Thank you!

**Comment by francescor** [comment]
Tooltips, quick and dirty with bootstrap (config/initializers/simple_form_bootstrap.rb):

```
# app/helpers/application_helper.rb
  def add_tooltip_to_label(label, tooltip)
    result = "".html_safe
    result << label
    result << " <abbr title='".html_safe
    result << tooltip
    result << "'><span class='glyphicon glyphicon-question-sign'></span></abbr>".html_safe
    result
end
```
then, in form:

```
# replace 
:label => "This is the label","This is an example of a tooltip"
# with
:label => add_tooltip_to_label("This is the label","This is an example of a tooltip")
```
