### ISSUE TITLE
Form Yes/No radio buttons not being translated with I18n

### ISSUE THREAD

**Issue by guilhermearaujo** [plataformatec/simple_form#1363]
I have the following form in our ActiveAdmin application:
```ruby
  form do |f|
    f.semantic_errors
    f.inputs do
      # some inputs
      f.input :unlimited, as: :radio
      f.actions
    end
  end
```

That radio button labels will be "Yes" and "No", unless I change the collection like this (or any other hardcoded collection):
```ruby
f.input :unlimited, as: :radio, collection: SimpleForm::Inputs::CollectionInput.boolean_collection
```

Once I do that, I see the translated labels. It seems like the collection being used by default is not the same as `boolean_collection`.

I know I18n is working and set up correctly because it works when I run on the Rails console:
```
[1] pry(main)> SimpleForm::Inputs::CollectionInput.boolean_collection
=> [["Sim", true], ["Não", false]]
```

We're using active admin 1.0.0.pre1 and simple_form 3.2.1

**Comment by carlosantoniodasilva** [comment]
I have a question: where do `semantic_errors` and `f.inputs do` come from? This is not standard Simple Form, they look a lot like Formtastic (which [activeadmin depends on](https://rubygems.org/gems/activeadmin)), so maybe the translation you're looking for should come from it's API instead?

Let us know if that's not the case, and we'll gladly reopen.
