### ISSUE TITLE
A single select option cannot be disabled

### ISSUE THREAD

**Issue by davidmles** [plataformatec/simple_form#1365]
When creating a select field, I'm trying to disable an option this way:

`f.input_field :foo, label: false, as: :select, collection: Foo.all, disabled: 'bar'`

It is disabling the option with the 'bar' value, but it is also disabling the entire select.

**Comment by rafaelfranca** [comment]
We have a test to asset that this behavior works https://github.com/plataformatec/simple_form/blob/81b9d7d3439225c7613e570afb44596acfa97a76/test/inputs/collection_select_input_test.rb#L234-L240. Could you provide a way to reproduce the behavior you are describing?

**Comment by davidmles** [comment]
Sure. Just use any page in a Rails project to put a form:

```erb
<%= simple_form_for :model do |f| %>
  <%= f.input_field :attr_id, as: :select, collection: AttrModel.all, disabled: 1 %>
<% end %>
```

This will result in a disabled dropdown, with the option with ID=1 also disabled.

There is a way to make it working:
Use `input` instead of `input_field`, and add `label: false`: `<%= f.input :attr_id, label: false, as: :select, collection: AttrModel.all, disabled: 1 %>`

Should not the input_field behave the same way?
