### ISSUE TITLE
Incorrect "step" value for decimal inputs

### ISSUE THREAD

**Issue by mateuszgorniak** [plataformatec/simple_form#1367]
Hi!
I wanted to use decimal inputs and set value for `step` attribute. Example code:
```
  <%= f.input :workload,
    as: :decimal,
    html5: true,
    input_html: {
      'data-ng-model' => 'employment.workload',
      'pattern' => '[0-9]+([\.,][0-9]+)?',
      'step' => '0.5' },
    required: false %>
```

Returned output I've got:
```
<input data-ng-model="employment.workload" pattern="[0-9]+([\.,][0-9]+)?" step="any" type="number" class="string optional form-control ng-valid ng-dirty ng-valid-number ng-valid-pattern ng-touched" value="120.1" name="employment[workload]" id="employment_workload">
```

It looks like the value is not set correctly. The only working solution for me is:
```
  <%= f.input :workload,
    html5: true,
    input_html: {
      'data-ng-model' => 'employment.workload',
      'pattern' => '[0-9]+([\.,][0-9]+)?',
      'step' => 0.5,
      'type' => 'number' },
    required: false %>
```
Code looks fine for me https://github.com/plataformatec/simple_form/blob/e81af052f4bbe9e17e38c668116cd1846c6d275c/lib/simple_form/inputs/numeric_input.rb#L10 , don't know why the value is still `any` even when something else has been defined.
Looks like a bug but let me know if I'm doing something wrong.

**Comment by alissonbrunosa** [comment]
@mateuszgorniak if you look at [line 10](https://github.com/plataformatec/simple_form/blob/e81af052f4bbe9e17e38c668116cd1846c6d275c/lib/simple_form/inputs/numeric_input.rb#L10), you can see that **input_html_options** is a hash and it use symbols as keys. 
You can do this: 
```ruby
<%= f.input :workload,
    html5: true,
    input_html: {
      'data-ng-model' => 'employment.workload',
      'pattern' => '[0-9]+([\.,][0-9]+)?',
      :step => 0.5,
      :type => 'number' },
    required: false %>
```

**Comment by mateuszgorniak** [comment]
Thx for answer but still your solution uses type instead of `as: decimal`. I'll check it with this type of input too ;-)

**Comment by rafaelfranca** [comment]
Thank you for the issue. I just tested this in the test suite and it work as expected if you pass `:step` as a symbol and not string. See the linked commit.
