### ISSUE TITLE
Error messages of nested object's attributes are not displayed

### ISSUE THREAD

**Issue by PirunSeng** [plataformatec/simple_form#1370]
I'm having a nested model form in which some attributes of the nested object's are required. My problem is that the page is redirect back to the form since the validation is failed but there are no error messages displayed.
Any help please?
Thanks,

**Comment by qx** [comment]
+1

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
