### ISSUE TITLE
Using simple_fields_for with nested_attributes_for and strong parameters

### ISSUE THREAD

**Issue by abreckner** [plataformatec/simple_form#1371]
Hello, 
Regarding the documentation on https://github.com/plataformatec/simple_form/wiki/Nested-Models

I found that in order to get this to work with strong parameters, I had to do the following instead
```erb
<%= simple_form_for @machine do |m| %>
  <% @machine.parts.each do |part| %>
    <%= field_set_tag 'Part' do %>
      <%= f.simple_fields_for "parts_attributes[]", p do |pf| %>
        <%= pf.input :name %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
```
and in the controller

```ruby
def machine_params
  params.require(:machine).permit(:parts_attributes => [:name])
end
```

Note that I had to change the name of the simple_fields_for to parts_attributes[] to match the strong parameters specification.

**Comment by rafaelfranca** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
