### ISSUE TITLE
Adding simple_form breaks url helpers

### ISSUE THREAD

**Issue by koenpunt** [plataformatec/simple_form#1372]
I've added `simple_form` to my Rails project, and suddenly when running specs my url helpers are not defined.

So things like this previously worked:

```erb
<%= link_to 'Back', vacancies_path %>
```

And now it fails with: 

```
ActionView::Template::Error:
        undefined local variable or method `vacancies_path' for #<#<Class:0x007fa2b6e6bb98>:0x007fa2b4475208>
```

**Comment by koenpunt** [comment]
My question which I asked in the mailing list might be related: https://groups.google.com/forum/#!topic/plataformatec-simpleform/G1skYI-ZXO4

**Comment by rafaelfranca** [comment]
This is a interesting problem, never saw it. Simple Form should not change how URLs are generated since it is just a wrapper around `form_for`. Could you create an example application that reproduces this?

**Comment by koenpunt** [comment]
I've setup a example application: https://github.com/koenpunt/simple-form-test And a PR which solves the issue: https://github.com/plataformatec/simple_form/pull/1402
