### ISSUE TITLE
No way to provide custom inpit type for collection

### ISSUE THREAD

**Issue by hauleth** [plataformatec/simple_form#1373]
I have created custom collection input type named `CollectionRequirementsInput` and when I try to use it inside my form I encounter issue.

There are 2 problems:

* when I use `f.input :confirmations, collection: @submission.requirements, as: :collection_requirements` I get `NoMethodError: undefined method `collection_collection_requirements' for #<SimpleForm::FormBuilder:0x0055864d3fd300>`
* when I use `f.input :confirmations, collection: @submission.requirements, as: :requirements` I get `RuntimeError: No input found for requirements`

**Comment by coatezy** [comment]
@hauleth Did you find a solution for your problem?

**Comment by hauleth** [comment]
@coatezy even if, I cannot recall solution.

**Comment by coatezy** [comment]
@hauleth No problem. We are experiencing the same problem. Will open a new ticket if I cannot find a solution. 👍  Thanks for the reply! 🍺

**Comment by coatezy** [comment]
Okay, I have the answer.

You simply need to define an `input_type` method with a string of the input type you wish your custom input to use.

```
class CustomCheckBoxesInput < SimpleForm::Inputs::CollectionCheckBoxesInput
  def input_type
    'check_boxes'
  end
end
```

```
<%= f.input :role_ids, collection: @role_ids, as: :custom_check_boxes %>
```

It calls send on the builder by default using the type given (as: custom_check_boxes).

`@builder.send(:"collection_#{input_type}", `
