### ISSUE TITLE
as: :boolean option with include_hidden option

### ISSUE THREAD

**Issue by cristianogregnanin** [plataformatec/simple_form#1377]
Hy, I don't want to generate the hidden field when I create a custom check box with `as: :boolean` option.
Is possibile to do something like this?

`<%= f.input :my_custom_field_true, as: :boolean, include_hidden: false %>`

Using the standard Rails check_box helper it works: 
`<%= f.check_box :my_custom_field_true, include_hidden: false %>`
But I prefer to use simple form DSL.

Note: Rails 4 support `include_hidden: false` option. Is possible to force simple form to use it?

**Comment by colinross** [comment]
Your second code example is essentially the solution here.

In the context of simple_form, a boolean is just a checkbox input with a hidden input (to supply a value when the box is unchecked)

While you could build a custom, specific 'simple form' input type based on [`build_check_box_without_hidden_field`](https://github.com/plataformatec/simple_form/blob/ac63da0f0b38df82385493f25f649e320b0acb4a/lib/simple_form/inputs/boolean_input.rb#L49), I just don't see the point in adding the extra layer.

**Comment by rafaelfranca** [comment]
It is also possible to generate it like the standard Rails helper if you use the `:inline` boolean style:

```erb
<%= f.input :my_custom_field_true, as: :boolean, boolean_style: :inline, input_html: { include_hidden: false } %>
```

**Comment by ruinunes** [comment]
@colinross when mapping a wrapper to the boolean simple form input type, you can pass`include_hidden: false` as an option to said wrapper and the hidden field won't be rendered.
