### ISSUE TITLE
Do not ignore implicitly passed required option

### ISSUE THREAD

**Issue by shyjt** [plataformatec/simple_form#1380]
Simple form ignores implicitly passed required option when `browser_validations` is disabled. 
In simple form version 3 required option is always set to false for disabled `browser_validations` -  https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/components/html5.rb
In version 2 it was able to pass required option even for disabled `browser_validations` - https://github.com/plataformatec/simple_form/blob/v2.2/lib/simple_form/components/html5.rb

I think explicitly passed required option should work for disabled `browser_validations`. What are your thoughts on this?

**Comment by rafaelfranca** [comment]
Yeah, it makes sense. Could you send a PR  to fix it?

**Comment by jdurand** [comment]
For reference, this worked as expected in v3.1.0.
This bug was introduced in v3.1.1.

**Comment by rafaelfranca** [comment]
I think so.

**Comment by lucasmazza** [comment]
Fixed by #1416
