### ISSUE TITLE
Problems with placeholder in simple_form textarea

### ISSUE THREAD

**Issue by nononoy** [plataformatec/simple_form#1384]
`= f.input :description, as: :string, input_html: { placeholder: 'Placeholder', rows: 3}, label: false, required: true` provides me a placeholder

![43838ee8f3](https://cloud.githubusercontent.com/assets/5082711/15365808/45e54178-1d2a-11e6-8e2b-5598f6e78c22.png)

but, `= f.input :description, as: :text, input_html: { placeholder: 'Placeholder', rows: 3}, label: false, required: true` makes me feel sadness

![08219391e4](https://cloud.githubusercontent.com/assets/5082711/15365958/e9e61ea0-1d2a-11e6-94cb-843b5c7488d9.png)

**Comment by brilyuhns** [comment]
I cannot reproduce this issue for simple_form (3.2.1) on chrome. Please provide more information on Gem version, OS and browser. 

Also I found this:
http://stackoverflow.com/questions/10186913/html5-textarea-placeholder-not-appearing

The placeholder will not show even if the field has a space.

**Comment by nononoy** [comment]
I had already tried the stackoverflow solution. But I still here, unfortunatelly. I really have no ideas why this nested textarea can't display placeholder correctly.

_Simple_form (3.1.0)
Ubuntu 14.04
Chrome_

**Comment by letronje** [comment]
Unable to reproduce this with Simple Form 3.1.0, Ubuntu 14.04, Chrome  50.0.2661.102.

Which version of rails are you on ? 

Are you seeing this problem on another browser like Firefox ?

Can you push a sample rails application to github where this issue can be seen ?

**Comment by nononoy** [comment]
I realised that problem appears only on localhost. On my production server all is OK. Here is a files with the issue: 
[first [lines 44-48]](https://github.com/nononoy/utilities/blob/master/app/views/votings/new.html.slim)
[second](https://github.com/nononoy/utilities/blob/master/app/views/votings/_voting_question_fields.html.slim)
may be the problem in my gems versions compatibility. Problem appears in Firefox, Opera etc.

**Comment by rafaelfranca** [comment]
Thank you for the issue. Simple Form only generate the HTML and  the HTML is correct. How the placeholder is rendered is responsibility of the browsers.
