### ISSUE TITLE
remove outer label of checkbox in ruby

### ISSUE THREAD

**Issue by Nageshwari-p** [plataformatec/simple_form#1385]
Hi ,

I'm using ruby on my project . I need costume style for check boxes  .

please find below code

<%= f.input :category_ids, :as => :check_boxes do %>
  <%= f.collection_check_boxes :category_ids, Category.order(:name), :id, :name do |b|
    b.label { b.check_box + b.text }
  end %>
<% end %>

Using above code Im getting out like 

<label for="property_space_amenities_space_amenities_2"><input type="checkbox" value="2" name="property[space_amenities][space_amenities][]" id="property_space_amenities_space_amenities_2">Internet connectivity</label>

form this im not able give custom style for this

i want output like below

   <label class="control-label" for="user_login">Login</label>
  <input class="form-control" id="user_login" name="user[login]" type="text" />

Please help me in this

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
