### ISSUE TITLE
Is there a way to show only some time_zones?

### ISSUE THREAD

**Issue by g00dL00Ks** [plataformatec/simple_form#1387]
First off, I love simple_form!  Great gem!

Is there a way to only show US time zones?  We've tried using only:  but that doesn't seem to work. 
`        <%= f.input :time_zone, priority: /US/, only: /US/ %>`

I can't find it any documentation. thank you!

**Comment by carlosantoniodasilva** [comment]
You should be able to pass the collection you want, relying on `ActiveSupport::TimeZone.all` to get the full list.

You can read more about [time zone select in the Rails docs](http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-time_zone_select), which is what Simple Form uses for "priority" inputs. Hope that helps!
