### ISSUE TITLE
Option to disable include_blank

### ISSUE THREAD

**Issue by kirkas** [plataformatec/simple_form#1388]
Is there an option to disable the include_blank?

Something like:
```haml
= f.input :select_input, as: :select, include_blank: 'Select a car', disabled: [:blank]
```
Would generate
```html
<select>
  <option selected disabled>Choose a car</option>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
</select>
```

or maybe as a config?
```
config.disable_select_blank = true
```

**Comment by 3wille** [comment]
I'd like this feature, too, but as I far as I know, the ``include_blank`` option ist just passed to [ActionView::Helpers::FormOptionsHelper](http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html) which generates the blank object

**Comment by rafaelfranca** [comment]
Yes. This is a Rails feature and there is no support for that. Feel free to submit a pull request to Rails. Thank you for the issue.
