### ISSUE TITLE
How to do a 3 column horizontal dropdown ( for day of birth )?

### ISSUE THREAD

**Issue by rubytastic** [plataformatec/simple_form#1389]
Rails 4 latest versions how would one render horizontal date with 3 input dropdowns?

This results in a broken horizontal layout, what are we missing?:

```
    = f.input :dob, :as => :date,
                    :start_year => Date.today.year - 18,
                    :end_year => Date.today.year - 99,
                    :month => Date.today.month,
                    :order => [:day, :month, :year],
                    :label => "Day of Birth",
                    :prompt => "Select"
```

<img width="736" alt="screen shot 2016-05-30 at 1 41 36 pm" src="https://cloud.githubusercontent.com/assets/189632/15648659/442cc6a8-266c-11e6-9058-560b7581407d.png">

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is more related to the markup of your application. Simple Form doesn't deal with style and markups. It generates a default markup to use Bootstrap but if you want to do things differently of the markup it is out of scope of this gem.

**Comment by yoshie902a** [comment]
Reopen: Same issue here...
http://stackoverflow.com/questions/39816490/simpleform-dob-not-displaying-correctly

The Gem seems not to format date field correctly for bootstrap. I think it needs a template change specific to date field.

**Comment by feliperenan** [comment]
https://github.com/plataformatec/simple_form/issues/1433
