### ISSUE TITLE
Use datetime-local instead datetime

### ISSUE THREAD

**Issue by obsidienne** [plataformatec/simple_form#1394]
Hi,

When using **html5: true** for a datetime field, the input type generated is datetime. According to caniuse and https://github.com/whatwg/html/issues/336, it should be datetime-local.

I have created a custom input just for that, maybe change this directly in the gem code ?

Thanks

**Comment by rafaelfranca** [comment]
Yeah, unfortunately the HTML 5 spec changed to remove datetime fields. We need to change Rails to fix this issue.

**Comment by lucasmazza** [comment]
Fixed on rails/rails#25469
