### ISSUE TITLE
Desabilitando select association

### ISSUE THREAD

**Issue by AndreLGava** [plataformatec/simple_form#1399]
Quero que meu select association esteja desabilitado para seleção mas que o parametro que há nele seja gravado com o formulário, já tentei readonly: true e disabled: true e não funcionaram um deixa com classe desabilitada permitindo trocar o registro o outro mostra registro e não deixa editar porem no momento que eu vou gravar não grava no banco por que o campo em questão é obrigatório e o controler não recebe seu parametro.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
