### ISSUE TITLE
add stale object state to form class

### ISSUE THREAD

**Issue by matzke** [plataformatec/simple_form#1403]
it would be nice if the form class would add states for new & stale states

**Comment by rafaelfranca** [comment]
I believe simple form already generated a different class in the form if the object is new or it is already persisted. Is that sufficient?

**Comment by matzke** [comment]
Well, new or persisted is nice. And *stale* would be another state ... a special case for optimistic locking when another user changed the object meanwhile.

**Comment by rafaelfranca** [comment]
I see. You should be able to do that in your application. I don't think this is a common user case that can be included in this gem. Thank you for the suggestion

**Comment by matzke** [comment]
True ... I just asked, because optimistic locking is a rails core feature, so it might be consequent to implement all object states: new, persisted and stale. (principal of least surprise)
