### ISSUE TITLE
data-disabled-with attribute is rendred twice (minor bug)

### ISSUE THREAD

**Issue by alex-min** [plataformatec/simple_form#1405]
Hello,

I've upgraded my packages and noticed a new issue on the disable_with attribute.

This code:

``` ruby
  <%= f.submit_tag 'edit', data: { disable_with: 'test'}, class: 'btn btn-primary btn-lg' %>
```

is producing

```
 <input type="submit" name="commit" value="edit" data-disable-with="test" data-disable-with="test" class="btn btn-primary btn-lg" />
```

With two times `data-disable-with` attribute

Is the code generating this in simple_form ?
Apologies if that's not the case, you can close that issue :)
If you can redirect me to the right place to report it (and if I can find what is generating it, I can even create a PR for it) :)

Package versions:
simple_form: 3.2.1
rails: 5.0.0
jquery-rails: 4.1.1

**Comment by rafaelfranca** [comment]
I'm almost sure it isn't simple form since submit_tag is not a method of simple form. It can be rails. Are you able to reproduce this in a new application?

**Comment by sivagollapalli** [comment]
@rafaelfranca I just checked with current rails master. I think there is no issue. Shall I add a test case to rails to avoid any regression?

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
