### ISSUE TITLE
Added class is overwrote by form-control

### ISSUE THREAD

**Issue by Xosmond** [plataformatec/simple_form#1406]
I have a problem, when i add classes like this (to make a horizontal form), i see that form-control is after the class, so it overwrites the width.
Code

``` erb
<div class="col-xs-12">
  <%= simple_form_for(@client,html: {class: 'form-horizontal'}) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :name, wrapper_html: { class: 'col-xs-12' }, input_html: { class: 'col-xs-8' }, label_html: { class: 'col-xs-2' } %>
    </div>
</div>
```

Screenshot
![captura de pantalla 2016-07-16 a las 3 44 06 p m](https://cloud.githubusercontent.com/assets/11930063/16897076/30fa0dfa-4b6c-11e6-936b-7eedfed4a918.png)

Is there any way to solve it?

**Comment by rafaelfranca** [comment]
Could you post the generated HTML?

This form is being tested in the example application and it is working https://github.com/rafaelfranca/simple_form-bootstrap/blob/master/app/views/examples/_horizontal_form_sf.html.erb#L1.

Please make sure your form is being defined like that one.

**Comment by Xosmond** [comment]
Yes your code works, thank you,i will use it, but i think the way i did it should works too right? Here is the generated code of that.

```html
<div class="form-group string optional client_name col-xs-12">
<label class="string optional col-xs-2 control-label" for="client_name">Name</label>
<input class="string optional col-xs-8 form-control" type="text" name="client[name]" id="client_name">
</div>
```

As you can see, col-xs-8 is called before, so form-control overwrites the width rule.
