### ISSUE TITLE
Fields are not required by default when an object includes ActiveModel::Validations but has no presence validations

### ISSUE THREAD

**Issue by tjjjwxzq** [plataformatec/simple_form#1408]
There seems to be some bug in the logic for detecting whether form fields should be required. If I have an object which includes `ActiveModel::Validations`, but has no presence validations, I should expect all the form fields to be required by default. However it seems that once an object responds to `validators_on`, none of its fields will be required if it has no presence validations. This isn't the expected behvaiour I believe.

**Comment by rafaelfranca** [comment]
Yes, it is. Only attributes that have presence validation are required.

**Comment by tjjjwxzq** [comment]
Okay, perhaps this is intended behaviour, but then my take would be that the documentation is ambiguous, since it says

> By default all inputs are required. When the form object has presence validations attached to its fields, Simple Form tells required and optional fields apart. 

So, my object has no presence validations attached, but it includes `ActiveModel::Validations`, hence it responds to `validators_on` and by the logic for checking required fields now, this results in none of its fields being required.

Comparing this to what is described in the docs, this is clearly *not* expected behaviour. I have no presence validations, so I expect everything to be required by default.

I would suggest either clarifying the documentation or changing the logic.

**Comment by rafaelfranca** [comment]
> I would suggest either clarifying the documentation

Agree.

**Comment by rafaelfranca** [comment]
Fixed by #1419
