### ISSUE TITLE
File field getting hidden in simple_form with 2 file fields

### ISSUE THREAD

**Issue by ram619prasad** [plataformatec/simple_form#1413]
I have 2 file fields. One for uploading the build(apk/ipa) and the other for uploading the icon.
![proper_errors](https://cloud.githubusercontent.com/assets/8692347/17458078/ef0fdae4-5c25-11e6-8e54-65abe2f8f861.png)

I have validation for build content type.

Now when I submit the form with invalid content_type, the file field is getting hidden.I interchanged the build and icon positions, only the last input (file) is visible the first one is disappering on invalid form submission. 

![faulty_errors](https://cloud.githubusercontent.com/assets/8692347/17458091/3b0e883c-5c26-11e6-8129-25a2bf9b4266.png)

Please help

**Comment by Ashviniv** [comment]
@ram619prasad Can you share your simple form code?

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
