### ISSUE TITLE
In Rails 5 time zone values are saved to the db with html ampersands

### ISSUE THREAD

**Issue by fuzzygroup** [plataformatec/simple_form#1415]
Hi, 

Perhaps I'm using this wrong but our db now has values like:

select id, time_zone from users where time_zone like '%&%';
+-----+--------------------------------+
| id  | time_zone                      |
+-----+--------------------------------+
|  93 | Pacific Time (US &amp; Canada) | (this looks right but its actually & amp ; 
|  94 | Pacific Time (US &amp; Canada) |
|  95 | Pacific Time (US &amp; Canada) |
|  96 | Pacific Time (US &amp; Canada) |
|  97 | Pacific Time (US &amp; Canada) |

That's not actually a valid time_zone string.  The & amp ; needs to be &.

Just passing it on

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
