### ISSUE TITLE
derived input type for boolean fields does not work anymore

### ISSUE THREAD

**Issue by Nghi93** [plataformatec/simple_form#1425]
The boolean type in the database is not mapped correctly to a checkbox using:
`form.input :boolean_type_field_name`

In 3.2.1 it works fine, since 3.3.0 it renders an input text field with false as default value.
Haven't checked for other type mappings so far.

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
