### ISSUE TITLE
Devise error messages work with simple form?

### ISSUE THREAD

**Issue by raintears** [plataformatec/simple_form#1429]
Hi, I like to display my error messages inline with the textboxes. 

It was working fine for displaying full error messages using <%= devise_error_messages! %>. But I like to make it inline for each field i have.

I tried <%= f.error :name %> but it doesn't work. Do I need to do additional things to make it display inline?

Thanks!

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
