### ISSUE TITLE
Validation of serialized hash value

### ISSUE THREAD

**Issue by louis-she** [plataformatec/simple_form#1431]
I'm facing this problem in my **Rails 5** project with simple_form-3.3.1, it's a little bit hard to automatically show the error messages of a field which is in a serialized hash. A quick example:

Some model A:

```
class A
  ...
  serialize :options
  validates :name_in_options_must_be_present
  ...
end
```

And form partly goes like this

```
<%= simple_form_for @a do |f| %>
  <%= f.simple_fields_for :options, OpenStruct.new(@a.options) do |ff| %>
    <%= ff.input :name %>
    <%= ff.input :age %>
  <% end %> 
<% end %>
```

In this case, It seems that simple form can not automatically show the error message at the right place when the **name_in_options_must_be_present** validation failed. After digging into the source, I found I must add the errors like this in the **name_in_options_must_be_present** validation function:

```
    if options[:name].blank?
      options[:errors] = {
        name: ['please enter a name'],
        age: [], # must tell simple form age's error is blank array or it will trigger an exception if it is nil
      }
```

After this the error showed up, I'm not pretty sure if this is the right way to do this.

Another thing is, if I change `lib/simple_form/components/errors.rb:41` to this:

```
object.errors[attribute_name] || []
```

then I can get rid of `age: []` ( Imaging there are a lot of field in the options, it will save a lot of work)

Anybody can help with this one?

**Comment by hubertjakubiak** [comment]
#1448

**Comment by feliperenan** [comment]
Closing it in favor https://github.com/plataformatec/simple_form/pull/1448

**Comment by yourtallness** [comment]
Seems like this doesn't work anymore:

```
if options[:name].blank?
      options[:errors] = {
        name: ['please enter a name'],
        age: [], # must tell simple form age's error is blank array or it will trigger an exception if it is nil
      }
```

The errors will need to respond to `ActiveModel::Errors` methods like full_messages_on.

I tried to initialize the errors to an `ActiveModel::Errors` instance, but afterwards it still fails when trying to `read_attribute_for_validation` for the options.

Any ideas?

**Comment by yourtallness** [comment]
I ended up doing this:

```
options[:errors] ||= ActiveModel::Errors.new(extra_fields)
options[:errors].add(some_key, :blank)
```

and:

```
class HashWithIndifferentAccess
  extend ActiveModel::Naming

  def read_attribute_for_validation(attr)
    send(:[], attr)
  end

  def self.human_attribute_name(attr, options = {})
    attr
  end

  def self.lookup_ancestors
    [self]
  end

end
```

so that I can support errors on fields serialized as a hash.

Seems to be working OK, though I'm not that happy about having to monkey patch HashWithIndifferentAccess.
