### ISSUE TITLE
Possible path issues

### ISSUE THREAD

**Issue by MarcinCebula** [plataformatec/simple_form#1432]
Issue: Neither @client or @activity should add "super_admin_" to path (example below). How do you handle Model classes such as SuperAdmin::Client? 

Required URL: `super_admin_client_activity_path`
Url from Form: `super_admin_super_admin_client_super_admin_activity_path`
Form:   `<%= simple_form_for([:super_admin, @client, @activity], html: { id: 'object_form' }) do |f| %>`

```
class SuperAdmin::Client
  include Mongoid::Document
  has_many :activities, class_name: "SuperAdmin::Activity", dependent: :destroy
end

class SuperAdmin::ActivitiesController < SuperAdmin::ApplicationController
  belongs_to :client, class_name: "SuperAdmin::Client"
end


```

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
