### ISSUE TITLE
Overwrite wrapper class

### ISSUE THREAD

**Issue by siegy22** [plataformatec/simple_form#1436]
Hi guys

So I'm using simple_form with the bootstrap wrappers:

``` ruby
config.wrappers :horizontal_form, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.use :placeholder
    b.use :label, class: 'col-sm-3 control-label'

    b.wrapper :right_column, tag: 'div', class: "col-sm-9" do |ba| # < HERE
      ba.wrapper :input_wrapper, tag: 'div' do |input_wrapper|
        input_wrapper.use :input, class: 'form-control'
      end
      ba.wrapper :other_wrapper, tag: 'div' do |other_wrapper|
        other_wrapper.use :error, wrap_with: { tag: 'span', class: 'help-block' }
        other_wrapper.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
      end
    end
  end
```

Now.. As you can see my comment, there's a `class:` parameter/option passed.

Now how can I overwrite this class when I'm using the `f.input` function?

I tried it like this:

``` ruby
<%= f.input :something, right_column_html: { class: "col-sm-3" } %>
```

But this will just add up the classes which would then produce something like this:

``` html
<div class="col-sm-9 col-sm-3">
  <!-- input... -->
</div>
```

So how do I do this?

🍻 cheers

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by acjay** [comment]
@siegy22, did you figure it out? I had the same question, and this is the #1 hit on google for "right_column_html".

**Comment by siegy22** [comment]
@acjay I didn't ask on StackOverflow, I think I managed to get around it somehow. :man_shrugging: 
But good think it works now!

**Comment by AnwarShah** [comment]
How do I pass class to the div wrapping the input? I'm not talking about the wrapper which wraps both label and input. How do i do it?

**Comment by rashmiee** [comment]
Just use JavaScript after content loading. For example in my case i did the following.

```
document.addEventListener('DOMContentLoaded', function() {
  document.querySelectorAll('.alert.custom-warning .mb-3').forEach(function(element) {
    // Remove the "mb-3" class
    element.classList.remove('mb-3');
  });
});
```
