### ISSUE TITLE
update fields with check_box doesn't doesn't work

### ISSUE THREAD

**Issue by betelgeus13** [plataformatec/simple_form#1438]
hi 
after we upgraded ruby to ruby version 2.2.5 from 1.9.3, and rails to rails (3.2.22.5) from 3.2.22, while using simple_form (2.1.0) we can't make check_boxes fields set to false value anymore. 

for example we have a boolean attribute add_captcha with the following code: 

 <%= f.input :add_captcha,
                :label_html => { :style => 'width: auto;display: inline-block' },
                :wrapper_html => { :class => 'right' } %>

but with this after the upgrade we can set the attribute to true but if we want to set it back to false we can't anymore

we fixed it in this way 

  <%= f.check_box :add_captcha,
                :label_html => { :style => 'width: auto;display: inline-block' },
                :wrapper_html => { :class => 'right' } %>
 <%= f.label :add_captcha,
                    :label_html => { :style => 'width: auto;display: inline-block' },
                    :wrapper_html => { :class => 'right' } %>

So my question did we do something wrong or is a known issue? and is there any way to fix it without having to change all our inputs into check_box type and then adding an extra label field?

**Comment by dmitry** [comment]
@betelgeus13 what is the difference. In the fixed version you have added `label`?

**Comment by betelgeus13** [comment]
oh sorry the first one should have been f.input rather than f.check_box, i have edited the post

**Comment by dmitry** [comment]
> but with this after the upgrade we can set the attribute to true but if we want to set it back to false we can't anymore

When you are set `value` attribute to `false` it's not shown anymore?

**Comment by betelgeus13** [comment]
the attribute is still shown as true

**Comment by dmitry** [comment]
@betelgeus13 and `add_captcha` is a model attribute or how it's implemented?

**Comment by betelgeus13** [comment]
@dmitry  yes it is a model attribute

**Comment by dmitry** [comment]
Have you tried `v2.1.3` or `3.x`?

**Comment by betelgeus13** [comment]
yes I have tried 2.1.3, still doesn't work, nothing higher though

**Comment by dmitry** [comment]
@betelgeus13 tried with activerecord `3.2.22.2` and simple_form `v2.1.2`

**Comment by feliperenan** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.
Thank you
