### ISSUE TITLE
Add a wrapper for `fields_for`

### ISSUE THREAD

**Issue by doits** [plataformatec/simple_form#1440]
I'm trying to add a wrapper to a `fields_for` call, for example ...

```haml
= simple_form_for model do |f|
  = f.fields_for :associations do |ff|
    ...
```

... should wrap each association in a `div` tag with class `nested-field`:

```html
<form>
  <div class="nested-field">
    ...
  </div>
  <div class="nested-field">
    ...
  </div>
</form>
```

The inputs should still use the default `wrapper` of the form, so basically I simply want to add a `div` around each association. I played around with the `wrapper` option, but this changes the wrapper of each input and does not simply wrap the `fields_for`.

Using ...

```haml
= simple_form_for model do |f|
  = f.fields_for :associations do |ff|
    .nested-field
      ...
```

... nearly archives that, but the hidden id field of the instance is rendered outside of `.nested-field`.

Is this possible to have a wrapper for everything?

**Comment by dmitry** [comment]
@doits why not to use `simple_felds_for`?

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
