### ISSUE TITLE
Mongoid + countries with simple_form

### ISSUE THREAD

**Issue by netwire88** [plataformatec/simple_form#1441]
I found an odd bug, not sure if others are seeing this.
I'm using mongoid-5.1.1 + simple_form-3.3.1 + countries-1.2.5 + country_select-2.5.2

I have a field in a model as such:
```
field :country, type: ISO3166::Country, default: 'US'
```

However, when I show it in a simple_form, the values of country that gets saved is not selected when the form is redisplayed. I've tried multiple variations of the following
```
=f.input :country, label: t('city.country'), as: :country, priority: ['CA', 'US', 'AU', 'NZ']
=f.input :country, label: t('city.country'), as: :country
```

The only way this works is by changing Country type to string
```
field :country, default: 'US'
```

Any thoughts?

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
