### ISSUE TITLE
Prefill a simple_fields_for

### ISSUE THREAD

**Issue by Sashkan** [plataformatec/simple_form#1442]
Is it possible to prefill a ```simple_fields_for``` ?

I have a ```Users```, who has_one ```backpack```, which has_may ```pockets```, each ```pocket``` has_many ```items```.

I created a default backpack, and I would like to prefill my user form backpack fields with the datas from this default backpack. 

I tried everything I could think of:

1 - In my controller

``` rb
@default_backpack = Backpack.first
@backpack = @default_backpack.deep_clone include: [ :pockets, { pockets: :items } ]
@backpack.save
@user.backpack = @backpack
```
But this leads me to a ```Couldn't find Backpack with ID=597 for USer with ID=```

2- In my view

```
<%= f.simple_fields_for :ibackpack, @default_backpackdo |bkpk| %>
<%= render 'backpacks/form', f: bkpk %>
<% end %>
```

Which leads me to empty backpack fields. I start my form with a simple

```
      <%= simple_form_for @user do |f| %>
```

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
