### ISSUE TITLE
`form-inline` and `form-group` are flipped.

### ISSUE THREAD

**Issue by victorbstan** [plataformatec/simple_form#1443]
Bootstrap 3 http://getbootstrap.com/css/#forms shows that `form-inline` wraps `form-group` tags, but simple_form reverses the order. 

To reproduce create a simple form with `<%= simple_form_for(@resource, html: { class: "form-inline" }) do |f| %> ...`

And observe the difference compared to the documentation for inline forms on the Bootstrap page linked above.

**Comment by rafaelfranca** [comment]
I can't see the difference. For me the form-group elements and inside forn-inline. What are you getting?

**Comment by victorbstan** [comment]
<img width="811" alt="screen shot 2016-11-24 at 10 58 08 pm" src="https://cloud.githubusercontent.com/assets/315297/20614187/ac025e96-b299-11e6-9ceb-2206eb885c4f.png">

**Comment by victorbstan** [comment]
My ruby is: 

```ruby
<%= simple_form_for(@order, html: { class: "form-inline" }) do |f| %>
    <%= f.input :pick_up_date_time_start, label: "Start"  %>
    <%= f.input :pick_up_date_time_end, label: "End" %>
<% end %>
```

**Comment by rafaelfranca** [comment]
That seems correct. The form-inline class is on the form element wrapping the form-group elements

**Comment by victorbstan** [comment]
It's not correct, please compare my screenshot with the twitter bootstrap example for inline forms: 

Bootstrap example:
```
<form class="form-inline">
  <div class="form-group">
...
```

The screenshot shows that form-group wraps form-inline, which is reversed.
