### ISSUE TITLE
Improvement plan of README snippet.

### ISSUE THREAD

**Issue by suganami0510** [plataformatec/simple_form#1444]
I read `Usage` of `README.md` and tried to confirm the function with sample application.

Since there was a difficult part to understand, I propose an improvement plan of `README.md`.

I attempted to confirm the function with `Usage` of `README.md`.
https://github.com/plataformatec/simple_form#usage

I had a hard time preparing for README.md snippet.

### Cause
- Path of view file is ambiguous
- Unclear where to define instance variables such as @ user
- Unclear attribute definition of User model

### improvement plan
- Describe the command satisfying the prerequisite
Ex. `rails g scaffold Users ...`
- Describe prerequisites on each snippet

I think that checking in the environment for beginners can be done smoothly

**Comment by feliperenan** [comment]
HI @suganami0510 thanks for you report.

Feel free to send a pull-request with these improvements 😄
