### ISSUE TITLE
About specify the optional class for those non-required inputs

### ISSUE THREAD

**Issue by agustin** [plataformatec/simple_form#1445]
Hi guys! I searched within the issues and PRs and could not found any insight on this matter, so that's why I'm posting in here.

I was trying to avoid to clutter the markup with the `optional` class name that the builder puts in all non-required fields, but I could not found a config that allows that, so I fork it and commit a change for that feature, but maybe I'm missing something and also sure if you have thoughts on this topic.

The commit with the proposed changes is this **[feed29c](https://github.com/agustin/simple_form/commit/feed29c687ef3f21394b95a817dc0f7815f93ce8)** if you have the time and if you think that it's something that you will like to have in the gem, I'm happy to open a PR and discuss it over there.

Thanks a lot and don't hesitate to let me know what you think or any other idea or anything.

**Comment by rafaelfranca** [comment]
Thank you so much for the suggestion but we prefer to avoid to add new configs. Why do you need to remove the `optional` class?

**Comment by agustin** [comment]
The thing is that seems redundant that a boolean attribute includes a class name, with this what I meant is that a input could be required or not (hence optional), so if there is the feature to include the class `required` feels weird to also have the `optional` one. 

Is also a styling thing on the markup, and not ended up with HTML tags with multiple classes (trying to have a more semantic approach).

But completely understand the the idea of not including configs on-demand.

**Comment by rafaelfranca** [comment]
I see. In that case I believe what you want is to remove the input from the `generate_additional_classes_for` configuration. https://github.com/plataformatec/simple_form/blob/master/lib/generators/simple_form/templates/config/initializers/simple_form.rb#L114

Does that work for you?

**Comment by agustin** [comment]
Yeap! that definetly works for what I was expecting! sorry to not figure it out by myself, I look a lot in the configs but somehow I missed that.

Despite that still feels weird that to remove all the additional classes to prevent the `optional` one, but I also understand that on a semantic approach, that's exactly what you want/need, so for me is perfect! 😉 

Thanks for the time Rafael! and have a nice week, I'm going to close it if you are ok with that?

**Comment by rafaelfranca** [comment]
You are welcome! Thank you for the issue.
