### ISSUE TITLE
Ruby 2.4 support

### ISSUE THREAD

**Issue by chrisjeon** [plataformatec/simple_form#1450]
It seems that Fixnum and Bignum are deprecated in ruby 2.4 and was replaced by the Integer class.

Attached is the screenshot of the deprecation warnings

![screen shot 2016-12-28 at 9 43 10 am](https://cloud.githubusercontent.com/assets/2433941/21524181/2c002eae-cce2-11e6-8b08-2444a664ec90.png)

**Comment by oliverklee** [comment]
Related: #1452 #1451

**Comment by myacheg** [comment]
https://github.com/plataformatec/simple_form/pull/1456
