### ISSUE TITLE
Class attribute in config.wrappers and wrapper_class in input seems not to be merged

### ISSUE THREAD

**Issue by meliborn** [plataformatec/simple_form#1458]
I have a custom wrapper
```ruby
config.wrappers :unify_form, tag: 'div', class: 'section', error_class: 'state-error' do |b|
    b.use :html5
    b.use :placeholder

    b.wrapper tag: 'div', class: 'input' do |ba|
      ba.use :label, class: ''
      ba.use :input
      ba.use :tooltip
    end
    b.use :error, wrap_with: { tag: 'em', class: 'color-pink' }
    b.use :hint,  wrap_with: { tag: 'div', class: 'note' }
  end
```
As you might see, it has ```section``` class. But when I try to make input field with ```wrapper_class``` attribute it overrides ```section``` class.
```ruby
= f.input :room_count_eq, label: 'Rooms', required: false, wrapper_class: 'col-md-2', input_html: {type: :tel}
```
Produces ```col-md-2 string optional q_room_count_eq```. But when I remove wrapper_class, it adds ```section``` class. Have I missed something?

**Comment by feliperenan** [comment]
Sorry for the late response :(.

I don't know if it's an issue yet so I'm closing this one. You can open a new issue if necessary.

Thanks
