### ISSUE TITLE
"no implicit conversion of ActiveSupport::SafeBuffer into Array" if render simple_fields_for in trailblazer cell

### ISSUE THREAD

**Issue by havran** [plataformatec/simple_form#1459]
Hi. I use simple_form with cells and if i try use simple_field_for method in my cell i get error "no implicit conversion of ActiveSupport::SafeBuffer into Array". I create issue in Rails ActiveSupport https://github.com/rails/rails/issues/27725, but this is maybe problem with simple_form (read rails issue)?

**Comment by tegon** [comment]
Hi @havran, thanks for your report.
You need to give us more information on how to reproduce this issue, otherwise, there is nothing we can do. Please open up a new issue and make sure to fill in all the information requested in the template shown inside the text box. Thank you!
