### ISSUE TITLE
How can simple_form be directed to produce :button instead of  :submit

### ISSUE THREAD

**Issue by jpwynn** [plataformatec/simple_form#1462]
Is there a config setting that tells simple_form's generator to create forms with  

    = f.button :button   

instead of

    = f.button :submit    

In a Rails 5 app using simple_form for scaffolding, submit button are rendered like this:

    = f.button :submit 

which then gets rendered as  

    <input type="submit" ...

I ran into a problem when using a certain UI framework (materialize) the submit buttons only work if you click right on the text, but if you click off to the side the button css special effects activate but the button is not actually clicked.

**Comment by rafaelfranca** [comment]
Thank you for the report.

See https://github.com/plataformatec/simple_form/pull/1482#issuecomment-293965259
