### ISSUE TITLE
Displaying association checkboxes in table

### ISSUE THREAD

**Issue by mmahalwy** [plataformatec/simple_form#1463]
An example would be great!

**Comment by benjamreynolds** [comment]
Was looking for a similar example myself. The issue I am facing is that we are using bootstrap, and I cant seem to figure out how to use `f.association :something, as: :checkboxes` without every option getting wrapped in a `<span class="checkbox">`. Ive tried messing around with the custom wrapper configuration dsl but that particular wrapper _appears_ to be injected outside that configuration, BUT I could just be missing something.

**Comment by feliperenan** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please open up a new issue and make sure to fill in all the information requested in the template shown inside the text box. Thank you!
