### ISSUE TITLE
Add base error display alongside existing errors

### ISSUE THREAD

**Issue by bluefalcon26** [plataformatec/simple_form#1466]
The generator for forms should include error display for object base errors (errors that do not apply to a particular field).

**Comment by bluefalcon26** [comment]
![screenshot-dhcp interface - google chrome](https://cloud.githubusercontent.com/assets/5347387/23172622/fea20490-f81b-11e6-8dea-10507a23e80b.jpg)

**Comment by fabriziobertoglio1987** [comment]
Yes. I am experiencing the same problem and using custom code to solve it.

**Comment by bluefalcon26** [comment]
The relevant pull request is #1465

**Comment by fabriziobertoglio1987** [comment]
Thanks .. I will try this out right no.. Fabrizio

**Comment by feliperenan** [comment]
Close in favor https://github.com/plataformatec/simple_form/pull/1465
