### ISSUE TITLE
README.md - two (2) typo edit suggestions

### ISSUE THREAD

**Issue by VonTeacher** [plataformatec/simple_form#1468]
I have been using your gem in several applications I am building and am thankful for the work you've done. In a thorough review of the documentation, in this case README.md, I found two small grammatical errors:

(1)
`217: **Simple Form** accepts same options as their corresponding input type helper in Rails:`
--should be--
`217: **Simple Form** accepts the same options as the corresponding input type helper in Rails:`
--or (more explicitly)--
`217: **Simple Form** inputs accept the same options as their corresponding input type helper in Rails:`

(2) 
`1060: possible to help us fixing the possible bug....`
--should be--
`1060: possible to help us in fixing the potential bug....`

I am happy to fork and submit a pull request. I did see, however, another issue relating to small fixes that were handled internally. Let me know your preference and thank you for your consideration and review.

**Comment by nashby** [comment]
@VonTeacher hey, feel free to send a PR. Thanks!

**Comment by VonTeacher** [comment]
@nashby thanks. I'll get back to it on Monday.

**Comment by VonTeacher** [comment]
Changes committed and pull request submitted [here](https://github.com/VonTeacher/simple_form/pull/1).

**Comment by nashby** [comment]
@VonTeacher awesome! Can you please send the PR to this repository and not yours? :)
