### ISSUE TITLE
Failing to find a link (via href id) in Rspec/Capybara test of Rails + paperclip + factory_girl_rails + simple_form

### ISSUE THREAD

**Issue by sliute** [plataformatec/simple_form#1469]
Hi,

In Ruby (2.4.0) on Rails (5.0.1), I am using paperclip to add images to a Post model and factory_girl_rails to create posts with images. I also use simple_form. The actual app works just fine when tested locally in the browser. My Post model is:

```
class Post < ApplicationRecord
  validates :image, presence: true
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end
```

However, this Rspec/Capybara test fails:

```
scenario 'or via individual post pages linked from index' do
  post = create(:post)
  visit '/'
  find(:xpath, "//a[contains(@href,'posts/1')]").click
  expect(page.current_path).to eq(post_path(post))
end
```

The error message is:

```
Failure/Error: find(:xpath, "//a[contains(@href,'posts/1')]").click

     Capybara::ElementNotFound:
       Unable to find xpath "//a[contains(@href,'posts/1')]"
```

The post counter never resets to 0 on completion after the test is completed. I did a save_and_open_page and the actual link on the tested page is something like this:

`'posts/37'`

The number at the end increases every time I run my tests. I believe this is because:

1. some other tests before the one above actually fill in and submit forms (successfully).
2. simple_form somehow does not reset its id numbering to 0 and simply goes on. I got this impression from here: http://stackoverflow.com/questions/24853066/having-trouble-testing-upload-file-with-capybara-attach-file-method.

Any idea how to fix this? Is this a simple_form bug that I can circumvent? Or could I write the test in a different way to target that specific link?

Thanks!

**Comment by tegon** [comment]
I think you should try to use the `post.id` to find the correct link.
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
