### ISSUE TITLE
File Uploads Fail with Paperclip

### ISSUE THREAD

**Issue by ncino-cpezza** [plataformatec/simple_form#1473]
Since Converting to simple_form files will not upload. From what i can tell it is not sending the content-type in the call to the server which is causing PaperClip to error with a message of NoHandlerFound. 

I have included `multipart: true` and that did not resolve it.

my form looks the same in the inspect elements as is it does if I didn't use simple_form tag.

When using form_for I am able to upload successfully no error.

Any guidance here would be greatly appreciated.

**Comment by arivasvera** [comment]
Same here  :hand:

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
