### ISSUE TITLE
Implement an :error_class attribute for inputs

### ISSUE THREAD

**Issue by CharlieHawker** [plataformatec/simple_form#1475]
I've started to look at working on a Foundation 6 generator for SimpleForm, and one of the early stumbling blocks I've hit is the inability to set an error class on the actual input field; there is some chat (and workarounds) [over at StackOverflow](http://stackoverflow.com/questions/21559545/how-can-i-add-an-error-class-to-the-input-on-error-using-simple-form) but I don't see any open issues on the repository discussing this.

I believe this can be achieved fairly simply by adding the following code:

```
if wrapper_options.key?(:error_class) && has_errors?
  (wrapper_options[:class] ||= "").concat(" #{wrapper_options.delete(:error_class)}")
end
```

between [lines 192 and 193](https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/inputs/base.rb#L192-L193) of `lib/simple_form/inputs/base.rb`.

The above seems to work for me and passes all tests, so I'll raise a PR.

**Comment by remofritzsche** [comment]
I've tried your patch, and my inputs receive the :error_class even when there is no error (or no validation done at all). Debugging it I figured out that `has_errors?` in the context of `SimpleForm::Inputs::Base` appears to be `true` all the time in my case. Not sure if this is a general issue.

**Comment by remofritzsche** [comment]
I've tried out your patch and just experienced something very strange: When having the server freshly started and I open the the form, it works as expected. When I submit the form, it correctly shows all the error classes. But when I reload the page, reopen the form and show it again, all of the inputs have the defined `:error_class` and `has_errors?` returns `true` - but the object `my_model.errors.present` is `false` (validation is not even called when just opening the form).

Looks like some very weird caching issue, probably in SimpleForm?

**Comment by CharlieHawker** [comment]
Good spot, PR updated 👍

**Comment by remofritzsche** [comment]
Great, thanks :) As I've just noticed, this solution works for `input`, but not for `input_field`. Do you have an idea how we could fix both?

**Comment by CharlieHawker** [comment]
You're right, that's not ideal... I'll take a look and see if there's a nice solution.

**Comment by remofritzsche** [comment]
Have you had a chance to look into this matter yet? That would be awesome.

**Comment by CharlieHawker** [comment]
Hey @remofritzsche, will be taking a look either later today or tomorrow, sorry, I've been on other projects, and I made this modification with one in particular in mind 😄

**Comment by remofritzsche** [comment]
No worries, it's not that urgent but it would be nice for us to have this. Thanks a lot :)

**Comment by tschoppi** [comment]
Hey @CharlieHawker, may I ask what the status is on this issue?

**Comment by CharlieHawker** [comment]
@tschoppi there's an open PR (#1476), but it needs me to do as @remofritzsche [suggests above](#issuecomment-292915474) still...

**Comment by neumayr** [comment]
:postal_horn: Offtopic FYI – Created a proposal to rails/rails for specifying a hash of `html_options` used to merge into options of tags that refer to attributes **with errors**.
It didn't catch much attention yet, feel free to add comments if you like it.

```rb
config.action_view.field_error_html_options = { class: "is-invalid" }
```
```html
<!-- output: merged options after form submit on _invalid_ fields -->
<input type="email" class="is-invalid" value="foobar" />
```
:octocat: https://github.com/rails/rails/pull/31247

**Comment by feliperenan** [comment]
Closing in favor #1552
