### ISSUE TITLE
[BUG] Raw/html_safe issue

### ISSUE THREAD

**Issue by DagnisSlogis** [plataformatec/simple_form#1477]
I have come across small bug, which does not allow me to use raw() or .html_safe for the button value.

Code:
`= form.button :submit, raw(I18n.t("interface.button.start.level.basic.order", level: 5))`

Renders as:
`= form.button :submit,I18n.t("interface.button.start.level.basic.order", level: 5)`

**Comment by tordans** [comment]
@DagnisSlogis have you tried using *_html for your translations which – as far as I understand it – will result in the same thing as the raw-command.

```
= form.button :submit, I18n.t("interface.button.start.level.basic.order_html", level: 5)
```

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
