### ISSUE TITLE
Adding custom input components to preview uploaded file

### ISSUE THREAD

**Issue by foliwe** [plataformatec/simple_form#1480]
I followed the topic to create a  preview of the file uploaded  but the preview did not display properly, it displays a missing image icon. i used Rails 5 ,  carrierwave 1.0.0 and simple_form 3.4.0. 
Here is the link to the topic
[Adding custom input components](https://github.com/plataformatec/simple_form/wiki/Adding-custom-input-components).
Here is the code
#### <%= f.input :image , :as => :image_preview, :input_html => {:preview_version => :thumb} %>

Here is the screenshot for the edit page

![Image](https://raw.githubusercontent.com/foliwe/images/master/Selection_001.png)

I will appreciate any help

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by foliwe** [comment]
ok sorry for that
