### ISSUE TITLE
Translate error messages

### ISSUE THREAD

**Issue by sechix** [plataformatec/simple_form#1491]
I am not able to find the way to translate error messages as 'This field is required" and "Please enter a valid email address". 
I put this  in my es.yml but nothing

  simple_form:
    error:
        required: "Campo obligatorio"

**Comment by rafaelfranca** [comment]
simple_form use the Rails I18n to do that. See the 4.5.1 section here http://guides.rubyonrails.org/i18n.html

**Comment by sechix** [comment]
Hi @rafaelfranca, I know i18n, my problem is that I don't know route for errors in simpleform
