### ISSUE TITLE
Display full message for each field

### ISSUE THREAD

**Issue by lykourgosts** [plataformatec/simple_form#1493]
Lets say for example we have a form like this:
```
<%= simple_form_for :post do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.button :submit %>
<% end %>
```
The _title_ field in my example is required. So if I try and submit the form without any value in the :title, the validation fails and comes back with an error message, as expected. However the error I get by default is just this _can't be blank_. So in order to display the full message for this field I do something like this `<%= f.input :title, error: f.full_error(:title) %>`, however although this seems to work fine, I have to do it on every single field for every single form. 

I was wondering whether there's something like a "global" config setting I can use instead.

**Comment by jlw** [comment]
Try this solution: https://stackoverflow.com/questions/43996406/show-full-messages-on-simple-form

**Comment by rafaelfranca** [comment]
You can find this config inside your application in the simple_form config file https://github.com/plataformatec/simple_form/blob/f98b158a605f9a76dd0a4f60ae8549a3c5f863a5/lib/generators/simple_form/templates/config/initializers/simple_form.rb#L51-L55
