### ISSUE TITLE
Compatibility with Rails 5.1 form_with

### ISSUE THREAD

**Issue by pedroadame** [plataformatec/simple_form#1494]
Hi! Rails 5.1 introduced `form_with` which unifies `form_for` and `form_tag`, allowing great capabilities.

How will this be compatible with it?

**Comment by choonggg** [comment]
Would like to know this as well.

**Comment by Losangelo** [comment]
config/initializers/simple_form.rb:177:in `block in <top (required)>': undefined method `alias_method_chain' for SimpleForm::FormBuilder:Class (NoMethodError)

Já teria uma solução para esse erro?
Would you have a solution to this error?

**Comment by rafaelfranca** [comment]
@Losangelo yes. Make sure you are using latest simple_form

**Comment by rafaelfranca** [comment]
`form_with` uses different default that `form_for` and those defaults conflicts with simple form features. Things like generating ids for fields are disabled in `form_with` and this breaks basic premisses of simple form that expects the ids to be available so the labels works automatically. Because of this we don't plan to support the `form_with` syntax for simple form.

**Comment by coreyward** [comment]
@rafaelfranca Does [this](https://github.com/rails/rails/commit/d3893ec38ec61282c2598b01a298124356d6b35a) suggest you're revisiting this issue or will simple_form stop working once form_for is removed from Rails?

**Comment by rafaelfranca** [comment]
`form_for` will not be remove from Rails.

We could support form_with now in simple_form but since simple_form expects a form builder and `form_with` depending on the arguments doesn't provide one, it is going to require more work to support it than I'm willing to do.

**Comment by coreyward** [comment]
> `form_for` will not be remove from Rails.

You might know something I don't here; I'm just referencing @dhh's comments from his [original proposal for `form_with`](https://github.com/rails/rails/issues/25197) where he said he'd like to deprecate both `form_for` and `form_tag` by Rails 6, and “I would consider form_for soft-deprecated after we get form_with.”

There was also talk of rebuilding both to run on top of `form_with`, but I don't know if that work proceeded past conception. 

> it is going to require more work to support it than I'm willing to do.

Is this something you would fold in if someone else in the community did the legwork, or is it out of the question for you?

**Comment by rafaelfranca** [comment]
> Is this something you would fold in if someone else in the community did the legwork, or is it out of the question for you?

Of course! If someone wants to work on it I'd be happily accept.

**Comment by mariohmol** [comment]
> @Losangelo yes. Make sure you are using latest simple_form

Hi there! thanks for the support..
I've been with issues using that with rails 5.1 and simple_form 5.1 , any help in what release has the fix about  `undefined method alias_method_chain' for SimpleForm::FormBuilder:Class` ?

thanks!
