### ISSUE TITLE
Still possible to use with Sinatra, but via Cells 4?

### ISSUE THREAD

**Issue by sixtyfive** [plataformatec/simple_form#1495]
Hi! I'd like to use `simple_form` with Sinatra. There's a [blog post from 2012](https://apotonick.wordpress.com/2012/06/25/using-rails-gems-like-simple_form-in-sinatra-or-anywhere/) showing how to do so using Cells 3. I've now played around getting things to work, but all that ever happens is:

```
simple_form-3.5.0/lib/simple_form.rb:166:in `<module:SimpleForm>': undefined method `env' for Rails:Module (NoMethodError)
```

Any insight as to what I might be missing? Or is it futile?

**Comment by rafaelfranca** [comment]
It should be fixed on master

**Comment by sixtyfive** [comment]
Oh nice, now my forms can become a little prettier again :)
Thank you Rafael!

**Comment by rafaelfranca** [comment]
All credits to @etagwerker who fixed the issue 😄

**Comment by etagwerker** [comment]
@sixtyfive @rafaelfranca Two birds with one stone! 

BTW, this is the fastest anyone has merged one of my PRs. Thank you! 😄
