### ISSUE TITLE
Add support for disabling whole form

### ISSUE THREAD

**Issue by ondrejbartas** [plataformatec/simple_form#1500]
Hi,

I just came to problem with disabling whole form (eg. You are user who can only read data, but application has only forms, but you can view them in disabled state)

For that reason I have added:
`= simple_form_for some_records, disabled: true do |f|`

which in helper I am monkeypatching with:

```ruby
module FormHelper
  def simple_form_for(record, options = {}, &block)
    if options[:disabled]
      super(record, options) do |f|
        content_tag(:fieldset, disabled: true) do
          block.call(f)
        end
      end
    else
      super
    end
  end
end
``` 

Which will produce:

```html
<form>
  <fieldset disabled="disabled">
     <!-- rest of inputs and form -->
  </fieldset>
</form>
```

in not disabled it will produce normal form as expected.

I would like to hear your comments, and if you like this, pls write me and I will prepare PR.

**Comment by rafaelfranca** [comment]
Does not `<%= simple_form_for some_records, html: { disabled: true } do |f| %>` work for you?

**Comment by ondrejbartas** [comment]
I have tried it but form property has no disabled, but fieldset does:
https://stackoverflow.com/questions/3507958/how-can-i-make-an-entire-html-form-readonly-server-side-only-please  and selected answer

**Comment by ondrejbartas** [comment]
It will also disable all input type submit and buttons

**Comment by rafaelfranca** [comment]
I feel like this can be done without changing simple form adding the fieldset to the page:

```erb
<%= simple_form_for some_records do |f| %>
  <%= content_tag :fieldset, disable: true %>
  <% end %>
<% end %>
```

And I'd prefer to avoid making the gem more complicated that it is today.

**Comment by ondrejbartas** [comment]
No problem at all, I am adding guard to application with tens of forms so I will leave it in helper method.
