### ISSUE TITLE
Form doesn't send field if it's empty.

### ISSUE THREAD

**Issue by nowakov** [plataformatec/simple_form#1507]
I want simple_form to send me data like: `{ opens_at: '', closes_at: '' }`, but I get an empty hash instead. I've tried everything, and for now I do a reverse merge in controller layer. But is it possible to achieve this behaviour with simple_form?

**Comment by feliperenan** [comment]
Hi @nowakov,

Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
