### ISSUE TITLE
:preload options doesn't work for association

### ISSUE THREAD

**Issue by zomberg** [plataformatec/simple_form#1509]
Models:
```ruby
class Book < ApplicationRecord
  belongs_to :series
end

class Series < ApplicationRecord
  has_many :books
end
```

Form:
```ruby
<%= simple_form_for @book do |f| %>
    <%= f.association :series, preload: false %>
    <%= f.button :submit %>
<% end %>
```

I don't want to preload all series during generating select. I would like to load them via AJAX and autocomplete. But look like ':preload' option doesn't work.

I see in log:
```
Series Load (0.7ms)  SELECT "series".* FROM "series"
```

When I debug application I see that this query was executed before code which use this option (SimpleForm::FormBuilder#build_association_attribute):
```ruby
# Force the association to be preloaded for performance.
if options[:preload] != false && object.respond_to?(association)
  target = object.send(association)
  target.to_a if target.respond_to?(:to_a)
end
```
This SQL query executes inside SimpleForm::FormBuilder#input on line:
```ruby
wrapper.render input
```

Is there a way to prevent loading this data during generation of input?

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
