### ISSUE TITLE
Not passing association to fetch_association_collection for association input

### ISSUE THREAD

**Issue by heaven** [plataformatec/simple_form#1512]
Hi, found it useful to be able to override just `fetch_association_collection` but we need `association` parameter in there. So now we have to override the whole `#association` method to add it. Is it possible to send it by default like you do with `build_association_attribute(reflection, association, options)`?

https://github.com/plataformatec/simple_form/blob/f98b158a605f9a76dd0a4f60ae8549a3c5f863a5/lib/simple_form/form_builder.rb#L193

**Comment by feliperenan** [comment]
Hi @heaven 

> Hi, found it useful to be able to override just fetch_association_collection but we need association parameter in there. So now we have to override the whole #association method to add it.

I don't understand, why you need to override it? 🤔

**Comment by heaven** [comment]
Hi, we have custom inputs, e.g. `:ajax_select`, so there's an additional strategy:
```ruby
if options[:as] == :ajax_select and scoped.count > 50
  options[:xhr] = true
```

**Comment by feliperenan** [comment]
Sorry, I didn't get it yet 🙈 

Can you send to us a pull-request with the implementation and motivations? We can discuss it a little better there, what do you think?

**Comment by heaven** [comment]
@feliperenan I don't think it makes sense merging the implementation into the gem as the implementations would vary. If only make it more generic. We do add a new select type – `ajax select` that does not preload the entire collection and allows us to use `association` input on large collections.

Also, our patch respects cancan abilities when preloading collections. Previously there was just one huge method `association`, it was split into 3 then:
- association
- fetch_association_collection
- build_association_attribute
Giving us more flexibility on overriding those separately. But we still have to override all 3 due to missing arguments.

Our patch looks like this:
```ruby
module FormBuilderPatch
  def self.included(base)
    base.class_eval do
      include InstanceMethods

      def association(association, options = {}, &block)
        options = options.dup

        return simple_fields_for(*[association,
          options.delete(:collection), options].compact, &block) if block_given?

        raise ArgumentError, "Association cannot be used in forms not associated with an object" unless @object

        reflection = find_association_reflection(association)
        raise "Association #{association.inspect} not found" unless reflection

        options[:as]         ||= :select
        options[:collection] ||= fetch_association_collection(reflection, association, options)

        attribute = build_association_attribute(reflection, association, options)

        input(attribute, options.merge(reflection: reflection))
      end

      private

      def fetch_association_collection(reflection, association, options)
        scoped =
          (reflection.scope ? reflection.klass.class_exec(&reflection.scope) : reflection.klass.all).
            accessible_by(template.current_ability, :api_search)

         if options[:as] == :select and (options[:xhr] or (not options[:preload] and not options[:collection]))
           options[:as] = :ajax_select
         end

        if options[:as] == :ajax_select and scoped.count > 50
          options[:xhr] = true

          if options[:preload]
            scoped
          elsif %i[has_many has_and_belongs_to_many].include?(reflection.macro)
            object.persisted? ?
              object.send(association).accessible_by(template.current_ability, :api_search) :
                object.send(association)
          else
            [object.send(association)].compact
          end
        else
          options[:xhr] = false
          scoped
        end
      end

      def build_association_attribute(reflection, association, options)
        case reflection.macro
          when :belongs_to
            (reflection.respond_to?(:options) && reflection.options[:foreign_key]) || :"#{reflection.name}_id"
          when :has_one
            raise ArgumentError, ":has_one associations are not supported by f.association"
          else
            if %i[select ajax_select].include?(options[:as])
              html_options            = options[:input_html] ||= {}
              html_options[:multiple] = true unless html_options.key?(:multiple)
            end

            # Force the association to be preloaded for performance.
            if options[:as] != :ajax_select and options[:preload] != false and object.respond_to?(association)
              options[:collection].to_a if options[:collection].respond_to?(:to_a)
            end

            :"#{reflection.name.to_s.singularize}_ids"
        end
      end
    end
  end
end
```

**Comment by feliperenan** [comment]
@heaven Now I think I got it.

Are you suggesting something like `fetch_association_collection(reflection, _association, options)`?

**Comment by heaven** [comment]
I am not sure what is the best way, but a way to define custom `#fetch_` and `#build_` would be useful as I think many people do use ajax selects. And we, in particular, had to override the `#association` method just to pass that additional `association` parameter, but this changes the API.
