### ISSUE TITLE
server restart needed after rails generate simple_form:install

### ISSUE THREAD

**Issue by jstoebel** [plataformatec/simple_form#1514]
I'm new to this library but I _believe_ that you need to restart your web server after running `rails generate simple_form:install` is this right? If so would including a note to that effect in the README be useful.

**Comment by jasontorres** [comment]
Not necessarily. I believe `spring` just needs to be restarted but both should work.

**Comment by feliperenan** [comment]
HI @jstoebel 

Feel free to send a pull-request with this improvement, we will be appreciated.
