### ISSUE TITLE
Unable to include HTML formatting in errors via simple_forms

### ISSUE THREAD

**Issue by AJFaraday** [plataformatec/simple_form#1515]
My company uses uniqueness checks, and sometimes requires a link to the duplicated item.
However the HTML is escaped and the link does not render. I can't find a way to configure Simple Form to make this display the link instead of raw HTML.

Using:
* Rails 3.2.22
* Simple Form 2.1.3
* Bootstrap

Reproduction:
* `git clone https://github.com/AJFaraday/simple_form_issue_app`
* `rake assets:precompile`
* `rake db:create`
* `rake db:migrate`
* `rails s`
* Point a browser at localhost:3000
* Click 'New Doohickey'
* Type the name 'test'
* Click 'Create Doohickey'
* Click 'New Doohickey'
* Type the name 'test'
* Click 'Create Doohickey'

Observe: The error message contains an <a> tag, which is visible, and not rendered as a link.

![image](https://user-images.githubusercontent.com/237798/30317840-42b2efb0-97a3-11e7-87c0-cd123d06cab6.png)

I have tried:
* Wrapping the `input` call in a `raw` call.
* Looking for options for `/config/initializers/simple_form.rb` and `/config/initializers/simple_form_bootstrap.rb`

Is this a bug? Or is there some kind of config option I'm missing which would make this link display?

**Comment by feliperenan** [comment]
Hi @AJFaraday 

Thanks for the report 😄 

We only release security fixes for this version, try to update to the last version of simple form.

Thanks
