### ISSUE TITLE
Bootstrap 4 compatibility?

### ISSUE THREAD

**Issue by owenstrevor** [plataformatec/simple_form#1516]
Can anyone tell me if simple_form is compatible with the new Bootstrap 4 beta?

**Comment by wynksaiddestroy** [comment]
As far as I understand the issue, simple_form is **not** compatible at the moment. Particularly I see no way to add error classes like `is-invalid` directly to the input element.
There is an open pull request #1476 which addresses the problem, but hasn’t been merged yet.

**Comment by naysawn** [comment]
Yes - it's compatible. Just add an initializer.  

:ruby
SimpleForm.setup do |config|
  config.error_notification_class = 'alert alert-danger'
  config.button_class = 'btn btn-default'
  config.boolean_label_class = nil

  config.wrappers :vertical_form, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.use :placeholder
    b.optional :maxlength
    b.optional :minlength
    b.optional :pattern
    b.optional :min_max
    b.optional :readonly
    b.use :label, class: 'control-label'

    b.use :input, class: 'form-control'
    b.use :error, wrap_with: { tag: 'div', class: 'error-block' }
    b.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
  end

  config.wrappers :vertical_file_input, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.use :placeholder
    b.optional :maxlength
    b.optional :minlength
    b.optional :readonly
    b.use :label, class: 'control-label'

    b.use :input
    b.use :error, wrap_with: { tag: 'span', class: 'help-block' }
    b.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
  end

  config.wrappers :vertical_boolean, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.optional :readonly

    b.wrapper tag: 'div', class: 'checkbox' do |ba|
      ba.use :label_input
    end

    b.use :error, wrap_with: { tag: 'span', class: 'help-block' }
    b.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
  end

  config.wrappers :vertical_radio_and_checkboxes, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.optional :readonly
    b.use :label, class: 'control-label'
    b.use :input
    b.use :error, wrap_with: { tag: 'span', class: 'help-block' }
    b.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
  end

  config.wrappers :horizontal_form, tag: 'div', class: 'form-group row', error_class: 'has-error' do |b|
    b.use :html5
    b.use :placeholder
    b.optional :maxlength
    b.optional :minlength
    b.optional :pattern
    b.optional :min_max
    b.optional :readonly
    b.use :label, class: 'col-sm-3 control-label'

    b.wrapper tag: 'div', class: 'col-sm-9' do |ba|
      ba.use :input, class: 'form-control'
      ba.use :error, wrap_with: { tag: 'span', class: 'help-block' }
      ba.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
    end
  end

  config.wrappers :horizontal_file_input, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.use :placeholder
    b.optional :maxlength
    b.optional :minlength
    b.optional :readonly
    b.use :label, class: 'col-sm-3 control-label'

    b.wrapper tag: 'div', class: 'col-sm-9' do |ba|
      ba.use :input
      ba.use :error, wrap_with: { tag: 'span', class: 'help-block' }
      ba.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
    end
  end

  config.wrappers :horizontal_boolean, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.optional :readonly

    # b.wrapper tag: 'div', class: 'col-sm-offset-3 col-sm-9' do |wr|
    #   wr.wrapper tag: 'div', class: 'checkbox' do |ba|
    #     ba.use :label_input
    #   end
    #
    #   wr.use :error, wrap_with: { tag: 'span', class: 'help-block' }
    #   wr.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
    # end
  end

  config.wrappers :horizontal_radio_and_checkboxes, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.optional :readonly

    b.use :label, class: 'col-sm-3 control-label'

    b.wrapper tag: 'div', class: 'col-sm-9' do |ba|
      ba.use :input
      ba.use :error, wrap_with: { tag: 'span', class: 'help-block' }
      ba.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
    end
  end

  config.wrappers :inline_form, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.use :placeholder
    b.optional :maxlength
    b.optional :minlength
    b.optional :pattern
    b.optional :min_max
    b.optional :readonly
    b.use :label, class: 'sr-only'

    b.use :input, class: 'form-control'
    b.use :error, wrap_with: { tag: 'span', class: 'help-block' }
    b.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
  end

  config.wrappers :multi_select, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.optional :readonly
    b.use :label, class: 'control-label'
    b.wrapper tag: 'div', class: 'form-inline' do |ba|
      ba.use :input, class: 'form-control'
      ba.use :error, wrap_with: { tag: 'span', class: 'help-block' }
      ba.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
    end
  end
  # Wrappers for forms and inputs using the Bootstrap toolkit.
  # Check the Bootstrap docs (http://getbootstrap.com)
  # to learn about the different styles for forms and inputs,
  # buttons and other elements.
  config.default_wrapper = :vertical_form
  config.wrapper_mappings = {
    check_boxes: :vertical_radio_and_checkboxes,
    radio_buttons: :vertical_radio_and_checkboxes,
    file: :vertical_file_input,
    boolean: :vertical_boolean,
    datetime: :multi_select,
    date: :multi_select,
    time: :multi_select
  }

  # Set label
  config.label_text = proc { |label, required| "#{label}" }

end

**Comment by 6temes** [comment]
Such as?

**Comment by iz103** [comment]
I am guessing, by initializer, this means adding a bootstrap-4 file to 

/lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap_4.rb

add the same code form the simple_form_bootstrap.rb and change the selectors to the equivalent new ones.

Not sure, but I might give that a try.

**Comment by 6temes** [comment]
There's an issue with styling invalid fields. We are using this workaround:

```
.has-invalid {
  .invalid-feedback {
    display: block;
  }

  label {
    color: $form-feedback-invalid-color;
  }

  .form-control {
    background: rgba($form-feedback-invalid-color, .8);
    border-color: $form-feedback-invalid-color;
  }
}
```

**Comment by wynksaiddestroy** [comment]
As I already wrote in a previous https://github.com/plataformatec/simple_form/issues/1516#issuecomment-330211453, I see no way how to achieve Bootstrap 4 integration apart from workarounds like @6temes proposed. If @naysawn or @iz103 do have a working initializer, I will be pleased to see it.

**Comment by printercu** [comment]
Created sample app https://github.com/printercu/rails_sf_bs4 with online demo https://rails-sf-bs4.herokuapp.com/
Basic features works fine, while there are still some issues with highlighting invalid checkbox/radio collections and other complex input. This is known issue in bs and it may change a lot before release.

This is commit with changes from bs3: https://github.com/printercu/rails_sf_bs4/commit/29a6a8e0b819a207cb3dd1405fcdbed0380f37d9

**Comment by tordans** [comment]
JFYI, Current discussion on the topic can be found here: https://github.com/plataformatec/simple_form/pull/1337
