### ISSUE TITLE
Two forms with habtm association in same page breaks the habtm as check_boxes

### ISSUE THREAD

**Issue by mcpenchel** [plataformatec/simple_form#1518]
Hi guys,

Basically, if you have two forms for two different objects of the same class in the same page, and one of the inputs is a f.association :related_objects, as: :check_boxes , when you click on the checkbox it works normally, but if you click on the label of the checkbox of the second form, the checkbox of the first form will be ticked.

This is because, I think, the HTML of the label of these checkboxes is the same.

**Comment by feliperenan** [comment]
Thank you for your report.

Could you please provide more information? Like for example:
* Rails version
* Simple Form version
* Steps to reproduce the error

Will be even more helpful if you provide a sample application or a test case that reproduces the error.

**Comment by feliperenan** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please open up a new issue and make sure to fill in all the information requested in the template shown inside the text box. Thank you!
