### ISSUE TITLE
Wrong number of arguments for associations whose scope has an argument

### ISSUE THREAD

**Issue by mkamensky** [plataformatec/simple_form#1519]
I have something like

    class Wizard
      has_and_belongs_to_many :schools, ->(wizard) { where castle: wizard.castle }
    end

when I use

    <%= f.association :schools %>

in a form, I get a `wrong number of arguments (given 0, expected 1)` exception

**Comment by feliperenan** [comment]
Thank you for your report.

Could you please provide more information? Like for example:
* Rails version
* Simple Form version
* Steps to reproduce the error

Will be even more helpful if you provide a sample application or a test case that reproduces the error.

**Comment by mkamensky** [comment]
Hi,

Rails version 5.1.4, simple form version 3.5.0

The situation is: I have many castles, each castle has many schools and many wizards. Each wizard can belong to several schools, and each school can host several wizards, but only if the schools and the wizards belong to the same castle. So my models look as follows:

  class Castle < ApplicationRecord
    has_many :wizards
    has_many :schools
  end

  class School < ApplicationRecord
    belongs_to :castle
    has_and_belongs_to_many :wizards, ->(school) { where castle: school.castle }
  end

  class Wizard < ApplicationRecord
    belongs_to :castle
    has_and_belongs_to_many :schools, ->(wizard) { where castle: wizard.castle }
  end

The form for School looks as follows:

  <%= simple_form_for school do |form| %>
    <%= form.association :wizards %>

    <div class="actions">
      <%= form.button :submit %>
    </div>
  <% end %>

When I try to use it I get the above error

I attach the example. Thanks!
[kingdom.tar.gz](https://github.com/plataformatec/simple_form/files/1501545/kingdom.tar.gz)

**Comment by tegon** [comment]
Hi @mkamensky.
I tried to run your example but I got another error:
```ruby
Started GET "/schools/new" for 127.0.0.1 at 2017-11-24 11:49:00 -0200
Processing by SchoolsController#new as HTML
  Rendering schools/new.html.erb within layouts/application
  Rendered schools/_form.html.erb (18.2ms)
  Rendered schools/new.html.erb within layouts/application (20.4ms)
Completed 500 Internal Server Error in 62ms (ActiveRecord: 1.3ms)



ActionView::Template::Error (undefined method `castle' for nil:NilClass):
    1: <%= simple_form_for school do |form| %>
    2:   <%= form.association :wizards %>
    3:
    4:   <div class="actions">
    5:     <%= form.button :submit %>

app/models/school.rb:3:in `block in <class:School>'
app/views/schools/_form.html.erb:2:in `block in _app_views_schools__form_html_erb___2389557724941141719_70125971473920'
app/views/schools/_form.html.erb:1:in `_app_views_schools__form_html_erb___2389557724941141719_70125971473920'
app/views/schools/new.html.erb:3:in `_app_views_schools_new_html_erb__3871778820780610095_70125971575740'
```
Do you have some logic to build the associations for a new `School` record?

**Comment by mkamensky** [comment]
This is strange, maybe a different version somewhere? Not sure what you meant in the last question, normally I would want to build a Castle, then build wizards and schools in it, and attach them to each other

**Comment by feliperenan** [comment]
I think I found the bug. As we are using the `instance_exec` to execute the scope from the association, when the scope has a parameter, it's breaking. You can see it below:
https://github.com/plataformatec/simple_form/blob/46da2d1e60b01d3cd47a50d5f414831124589fcf/lib/simple_form/form_builder.rb#L464

I'm not sure about that, but I think that the scope's parameter always will be the instance of the own class, in this case, the instance of the `school` - maybe @rafaelfranca can confirm it. If it's true, we can fix it with something like that:

``` ruby
          if reflection.scope.parameters.any?
            relation = reflection.klass.instance_exec(object, &reflection.scope)
          else
            relation = reflection.klass.instance_exec(&reflection.scope)
          end
```

@tegon @mkamensky Let me know your thoughts, if I'm right, I can send the PR to fix it later.

**Comment by mkamensky** [comment]
This is definitely the situation in my case, and the only way I know of that this parameter is used.

**Comment by rafaelfranca** [comment]
sound like a plan to me
