### ISSUE TITLE
as: :radio_buttons not saving to database

### ISSUE THREAD

**Issue by Andrew-Bootsma** [plataformatec/simple_form#1525]
Here is my code that correctly saving to the database:
`= f.input :option`

When I try to override the default it no longer saves to my database:
`= f.input :option, as: :radio_buttons, collection: ['I choose yes' ,'I choose no'], label: "Please choose an option"`

This is the only difference I make in my code and it stops working.

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
