### ISSUE TITLE
Documentation - Provide generated HTML side by side with code

### ISSUE THREAD

**Issue by jin78** [plataformatec/simple_form#1536]
Hi,

like too many tools on the web, simple form has one major drawback: documentation with user friendly interface.

While the readme is readable, it's not user friendly documentation.

I mean since this tool is generating HTML, right?

So here's my example:

library code on the left > generated HTML on the right with syntax colors.

**Comment by feliperenan** [comment]
Hi @jin78

IMHO just have the generated HTML below the simple_form code like [this one](https://github.com/plataformatec/simple_form#collection-radio-buttons) is enough. But we don't have it in all examples. 

Feel free to open a pull-request to us with this improvement :)
