### ISSUE TITLE
Keeping file on error after submit.

### ISSUE THREAD

**Issue by hsyntnc** [plataformatec/simple_form#1537]
Hi,
I was wondering can we keep the file that user selected on error after submit.

For example, i have a form. I have couple columns and have 2 file fields. Lets say user selected 1 file and posted the form. If the record gets a validation error for the content it has, the file disappears after submit. Is there a way to keep that file? 
I guess i've found like f.input :file_cache, :hidden  but that doesnt work with simple form.
Thank you!

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
