### ISSUE TITLE
Errors with ransack and rails 5.2.0.rc1

### ISSUE THREAD

**Issue by StephaneRob** [plataformatec/simple_form#1542]
## Environment

- Ruby 2.5.0
- Rails 5.2.0.rc1
- Simple Form 3.5.0
- Ransack 1.8.6

## Current behavior

```
<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.button :submit %>
<% end %>
```

Raise an error `wrong number of arguments (given 0, expected 1)` on `<%= f.input :username %>` line.

Since this rails commit [530b5fea8f3e04c45a20ff3dcc8d473a6d25c1b4](https://github.com/rails/rails/commit/530b5fea8f3e04c45a20ff3dcc8d473a6d25c1b4#diff-1b43bc32bcc4987e19cfb3ba2c1c7733), simple_form doesn't work anymore with ransack installed.

The value of the input is computed in ransack due to the override of `actionview/lib/action_view/helpers/tags/base.rb` in https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/helpers/form_builder.rb#L9

This issue should be fixed soon on ransack https://github.com/activerecord-hackery/ransack/pull/868/files.

**Comment by feliperenan** [comment]
Hi @StephaneRob. Thanks for the report.

It looks like was merged. Can you take a look if it's working?

I'm closing it since it's not a Simple Form issue, but feel free to comment any news about it here.

**Comment by StephaneRob** [comment]
@feliperenan PR on ransack was merged, and it works normally with last ransack release.

Yes it's was not really a simple form issue, just reported because the error raised on simple_form input.
