### ISSUE TITLE
Parent child nested checkboxes, nested associatioin

### ISSUE THREAD

**Issue by kirykr** [plataformatec/simple_form#1550]
## Environment

- Ruby **[version]**
  `gem 'ruby', '~> 2.3.1'`
- Rails **[version]**
  `gem 'rails', '~> 5.0.2'`
- Simple Form **[version]**
  `gem 'simple_form',                  '~> 3.4'`

## Current behavior
```ruby
class SportCategory < ApplicationRecord
  has_many :children, dependent: :destroy, class_name: 'SportCategory', foreign_key: :parent_id
  has_many :submission_sport_lists
 accepts_nested_attributes_for :children, reject_if: :all_blank, allow_destroy: true
end
```
```ruby
class SportSubmission < ApplicationRecord
  has_many :submission_sport_lists, dependent: :destroy, inverse_of: :sport_submission
  has_many :sport_categories, through: :submission_sport_lists
end
```
```ruby
= simple_form_for [@game, @sport_submission] do |f|
      = f.input :validation, as: :hidden, input_html: { value: (@sport_submission.errors[:submission_sport_lists].first) }
      .row
        .col-xs-6
          = f.association :sport_categories, collection: SportCategory.sport_submission_collection, as: :check_boxes, required: true, label: t('.sport_categories'), input_html: { class: 'styled' } do |sport_sub|
            = sport_sub.association :children, collection: SportCategory.only_children, as: :check_boxes, required: true, label: t('.sport_categories'), input_html: { class: 'styled' }
```
Include code samples, errors, steps to reproduce the error and stacktraces if appropriate.
  `Association :children not found`
## Expected behavior
  to have nested children checkboxes under parent checkboxes

**Comment by kirykr** [comment]
I want to list the checkboxes that belongs to the parent. For Example:

- [ ] bootball
  - [ ] boy team
  - [ ] girl team

- [ ] basket ball
  - [ ] boy team
  - [ ] girl team

**Comment by feliperenan** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
