### ISSUE TITLE
Add Rails 5.2.X support

### ISSUE THREAD

**Issue by roberts1000** [plataformatec/simple_form#1567]
The current `simple_form.gemspec`  has

```ruby
s.add_dependency('activemodel', '> 4', '< 5.2')
s.add_dependency('actionpack', '> 4', '< 5.2')
```

which prevents people from using Rails 5.2.0.

**Comment by sam0x17** [comment]
Yeah this royally messed up my Gemfile after a simple `bundle update`

**Comment by feliperenan** [comment]
We released a new version of Simple Form just now 😄 

Closing in favor https://github.com/plataformatec/simple_form/issues
