### ISSUE TITLE
Add wrappers for "Semantic UI"

### ISSUE THREAD

**Issue by amingilani** [plataformatec/simple_form#1572]
Since simple_form ships with a support for popular CSS frameworks, we should extend that to support Semantic UI.

This was initially raised in #895 but that was closed without discussion.

## Current behavior

rails generate simple_form:install --bootstrap

```
rails generate simple_form:install --semantic-ui
Running via Spring preloader in process 98570
SimpleForm 3 supports Bootstrap and Zurb Foundation 5. If you want a configuration that is compatible with one of these frameworks, then please re-run this generator with --bootstrap or --foundation as an option.
      create  config/initializers/simple_form.rb
       exist  config/locales
      create  config/locales/simple_form.en.yml
      create  lib/templates/haml/scaffold/_form.html.haml
```

## Expected behavior

```
rails generate simple_form:install --semantic-ui
Running via Spring preloader in process 98720
      create  config/initializers/simple_form.rb
      create  config/initializers/simple_form_semantic-ui.rb
       exist  config/locales
      create  config/locales/simple_form.en.yml
      create  lib/templates/haml/scaffold/_form.html.haml
===============================================================================

  Be sure to have a copy of the Semantic UI stylesheet available on your
  application, you can get it on https://semantic-ui.com/.

  Inside your views, use the 'simple_form_for' with the Semantic UI form
  classes, '.form' as the following:

    = simple_form_for(@user, html: { class: 'form' }) do |form|

===============================================================================
```

**Comment by rafaelfranca** [comment]
https://github.com/plataformatec/simple_form/issues/895#issuecomment-25263581

**Comment by rafaelfranca** [comment]
Just to be clear, we, the simple form maintainers don't want to maintain integrations to more frameworks, that is why we closed the other issue and the that reason is still true today.

**Comment by amingilani** [comment]
@rafaelfranca would the maintainers be open to refactoring the third-party themes out to another gem? I mean, I'd be open to creating and maintaining a gem with all the popular themes and documentation on adding more if you guys want to get rid of theming support entirely.

**Comment by rafaelfranca** [comment]
For now we will keep the themes that we already have inside the gem. But people is welcome to create new integrations for the one's that are not officially supported.
