### ISSUE TITLE
Is there anything new we need to know with ActiveStorage support?

### ISSUE THREAD

**Issue by Schwad** [plataformatec/simple_form#1573]
Thanks for all the great work folks, really excited about the latest release and upgrading to 5.2.0 and 4.0.0 simple_form today.

I saw that there is now ActiveStorage support: https://github.com/plataformatec/simple_form/commit/46de30ac6db60458dd8542dfdae4ce7d5a0791cb

But was looking for a little more information, is there anything more we need to know about using simple_form 'with' active storage? Or will the use-cases look the same as all prior file uploads?

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by rafaelfranca** [comment]
The usage should be the same

**Comment by Schwad** [comment]
Thank you for your feedback @rafaelfranca
