### ISSUE TITLE
Please yank 4.0.0 and release 4.0.1 with fixed dependencies.

### ISSUE THREAD

**Issue by yemartin** [plataformatec/simple_form#1576]
Still running Rails 4.2, we unwittingly upgraded to `4.0.0` (CI passed after routine upgrades). Not sure how much would have been broken, but we immediately reverted to `3.5.1`.

The dependencies are already fixed in 9d8b99b3b74710568248934af28f3e37885ff3a6, but nevertheless, as long as 4.0.0 is published, this could bite others too.

Please yank 4.0.0 and release 4.0.1 with the dependency fix as soon as possible to save others the trouble.

**Comment by feliperenan** [comment]
The version 4.0.1 was released just now.

**Comment by yemartin** [comment]
Thank you @feliperenan for the release, but please reopen this issue, it is not done yet: just publishing `4.0.1` does not solve the problem on its own, `4.0.0` must also be [yanked](http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem).

To verify, I just tried to remove our manual version lock and `bundle update`: Simple Form still gets updated to `4.0.0` even though we are running Rails 4.2.

Please [yank](http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem) `4.0.0`, this version has wrong dependencies and should not have been published.

**Comment by rafaelfranca** [comment]
We are not going to yank the gem. We don't yank gems because they have bugs. This break a lot of setups like CIs and cause a lot of pain to a lot of people. yank is for when you publish your credentials or a gem with a wrong name, but for bugs, you just need to release a new gem.

**Comment by yemartin** [comment]
Hmm, thinking about it more, I am not sure the bumps are trouble-free either...

The nice thing about releasing the new version as `5.0.0` is that it makes it clear that `4.x` was botched and abandoned. But then there is this risk: if someone had declared their gem with

```
gem 'simple_form', '~>4.0'
```

currently on `4.0.1`, they would  be "upgraded" to `4.1.0` (effectively downgraded to `3.5.1`)...

To prevent this, we need to do only patch number bumps. Release the new (dependency-fixed) version as `4.0.3`, and the old `3.5.1` as `4.0.2`. Ideally (but I am not sure if it is possible), `4.0.3` would be released *before* `4.0.2`, to prevent any up-to-date user from  accidentally being "downgraded" to `4.0.2` while the gems are being published.

So by using patch number bumps, we solve the "unintended downgrade" issue, but we are left with that odd `4.0.2` (really `3.5.1`) version in the middle of `4.x`...

Without `gem hide`, no solution is perfect, and it is a matter of choosing the lesser evil. The patch number bumps sound like they would have the least impact, what do you think?

**Comment by lamont-granquist** [comment]
people won't wind up on 4.0.0 if 4.0.1 is available and fixes the dependency issue.  people use `~> 4.0` or `~> 4.0.0` as their constraints both of which will promote to `4.0.1`.  without support for 'hiding' a gem version this is the best you can do.  someone could perhaps wind up on 4.0.0 still but its unlikely.

**Comment by yemartin** [comment]
Just to be clear, as of now, people with Rails 4.2 do wind up on 4.0.0, even though 4.0.1 is available and fixes the dependency issue. Just verified it with this minimal Gemfile:

```ruby
source :rubygems
gem 'rails', '~>4.2'
gem 'simple_form'
```

The output of `bundle` is:

```
$ bundle
Fetching gem metadata from http://rubygems.org/..........
Fetching gem metadata from http://rubygems.org/.
Resolving dependencies....
[...]
Using rails 4.2.10
Using simple_form 4.0.0
Bundle complete! 2 Gemfile dependencies, 35 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by yemartin** [comment]
If 4.0.0 was utterly broken under Rails 4.2, I would agree entirely. Tests would catch it and we would not need to worry about this. But that's the thing: we *do* have extensive tests, and they all passed, so the routine upgrade went forward. Can you point out some things that should break with 4.0.0 under Rails 4.2?

**Comment by lamont-granquist** [comment]
oh i see now.  so yeah, you can do a 4.0.2 release with the 3.5.1 version of the code that allows rails 4.2 and then follow that up with a 4.0.3 release with the actual 4.x code and the proper gate on rails.

if you do not expect to be maintaining the 3.x branch that would work.

otherwise yeah it starts all getting very confusing.

you may have a use case here for doing a yank even though they suck.  better to have the hide feature, but that doesn't exist.

**Comment by yemartin** [comment]
@feliperenan I changed the title to reflect more correctly what the core of the issue is. With this improved title, it should be more apparent now that the issue is not resolved yet. Could you please reopen it? If anything, it can help alert other Rails 4.2 users about the current situation.

**Comment by rafaelfranca** [comment]
If all tests passed maybe there is no problem on using 4.0.0 with Rails 4.2? Or did you find issues in production?

**Comment by rafaelfranca** [comment]
The only two things that may break is the maxlength and the minlength if the length validator uses a tokenizer https://github.com/plataformatec/simple_form/commit/ffc13c9925da957c274c1f090f7fc80b65fda307.

That case is so uncommon that I'd say it is pretty safe to say that 4.0.0 works with Rails 4.2.

**Comment by yemartin** [comment]
@rafaelfranca This is great news! It means there may be one more, very clean course of action: temporarily restore Rails 4.x support.

Looking at ffc13c9925da957c274c1f090f7fc80b65fda307, it looks like the removal of Rails 4.x support is not a technical limitation, but about simplifying the code base... So, would simply reverting ffc13c9925da957c274c1f090f7fc80b65fda307 restore full Rails 4.x support? In that case, this is by far the cleanest solution:

- Release 4.0.2 with Rails 4.x support restored.
- Re-release 4.0.1 as 5.0.0, dropping (again, but properly this time) support for Rails 4.x.

I think this is pretty close to the perfect fix for this issue. What do you think?

PS: to answer your question: we did not find any particular issue. But even if CI passed, we decided to pull the upgrade after finding in the release notes that Rails 4.x support had been removed.

**Comment by rafaelfranca** [comment]
I'm not sure if we want to bump to 5.0 just because of this.

Probably 4.0.0 will never give Rails 4.2 users problems so the current state is good enough in my opinion.

4.0.0 drops support to Rails 4.2, it still can be installed, it still works, but it is not officially supported. 
The code in 4.0.1 also still works with 4.2, it is still not officially support, but the gem can't be installed.

Most users will not even install 4.0.0, and if they do they will not see any problem in development and production, so reverting the change and releasing 5.0.0 seems unnecessary to me.

**Comment by yemartin** [comment]
Yeah at this point I agree with you: the bumps may not be worth the effort...

How about a small documentation change then? Even though there was no bug in production, with [the current CHANGELOG for 4.0.0](https://github.com/plataformatec/simple_form/blame/1e35f201b4e934e3e58491659581bbc94cd370f5/CHANGELOG.md#L16), not knowing what may be broken, I had no choice but to call for an immediate pull of the update. To prevent sending others into panic mode, how about changing that line to something more specific? Something like:

- Remove tokenized length validator support from Rails 4.x.

If I had seen that, I would not have worried and pulled the update.
