### ISSUE TITLE
Invalid code in the config template

### ISSUE THREAD

**Issue by vill** [plataformatec/simple_form#1577]
Hi there. [In the code a comma is omitted, between the names of the methods](https://github.com/plataformatec/simple_form/blob/9d8b99b3b74710568248934af28f3e37885ff3a6/lib/generators/simple_form/templates/config/initializers/simple_form.rb#L136).

## Environment

- Simple Form **4.0.0**

## Current behavior

```ruby
config.file_methods = [ :mounted_as, :file?, :public_filename :attached? ]
```

## Expected behavior

```ruby
config.file_methods = [ :mounted_as, :file?, :public_filename, :attached? ]
```
or
```ruby
config.file_methods = %i[ mounted_as file? public_filename attached? ]
```

**Comment by feliperenan** [comment]
Hi @vill, thanks for the report.

Good catch. Are you willing to send a pull request for it?
