### ISSUE TITLE
Possible to default all forms to remote: true?

### ISSUE THREAD

**Issue by gregblass** [plataformatec/simple_form#1581]
Hey there. 

Question: Is it possible for me to add something to the simple_form.rb config file to default all my forms to be remote: true? I'm using turbolinks and I find myself writing it on every form I'm using. I checked the readme and the wiki, googled/searched stackoverflow, but couldn't find anything.

Thanks in advance!

**Comment by feliperenan** [comment]
No, Simple Form doesn't have this option.
