### ISSUE TITLE
Custom form builder how to set with error ?

### ISSUE THREAD

**Issue by Thomastar** [plataformatec/simple_form#1588]
Custom form builder how to set with error ?

def jxcat_form_for(object, *args, &block)
    options = args.extract_options!
    simple_form_for(object, *(args << options.merge(builder: JxcatFormBuilder)), &block)
 end
  delegate :content_tag, :link_to, :icon, :safe_join, :raw, to: :@template
  require 'time'

  def images_picker(attribute_name, options = {}, &_block)
    input(attribute_name, options) do
      content_tag :div, class: 'image-picker', data: options[:data] do
        icon_tag = icon('cloud-upload')
        link = link_to safe_join([raw(icon_tag), '上传图片']), 'javascript:;',
                       class: 'button hollow image-picker-button'
        spinner = content_tag :div, class: 'spinner-container' do
          content_tag :span, '', class: 'spinner'
        end

        value = object.send(attribute_name).to_json
        hidden = hidden_field attribute_name, class: 'image-picker-field', value: value

        list_panel =
          content_tag :div,
                      '',
                      class: 'image-picker-list-panel',
                      data: {
                        'mfp-modal': {
                          delegate: 'img',
                          type: 'image',
                          gallery: {
                            enabled: true
                          }
                        }
                      }
                              
        [link, spinner, hidden, list_panel].join&.html_safe
      end
    end
  end

**Comment by feliperenan** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
