### ISSUE TITLE
citext column type does not set HTML5 input type properly

### ISSUE THREAD

**Issue by brucew** [plataformatec/simple_form#1589]
## Environment

- Ruby 2.4.2
- Rails 5.1.1
- Simple Form 4.01

## Current behavior
A database column of type :citext renders the following html5 input (User.first_name example):
`<input class="string citext required" type="citext" value="" name="user[first_name]" id="user_first_name" data-validate="true">`
Note that the input type is citext, which I don't think is a valid HTML5 input type and in my case causes Foundation to fail to apply the proper CSS to the input.

## Expected behavior
Expected input example:
`<input class="string citext required" type="text" value="" name="user[first_name]" id="user_first_name" data-validate="true">`

## Potential Fix
Updating the string? method in SimpleForm::Inputs::StringInput seems to be the easiest fix:
```     
def string?
  input_type == :string || input_type == :citext
end
```

**Comment by feliperenan** [comment]
Hi @brucew, thanks for the report :)

Yeah, you are right, `citext` ins't a valid input type. Are you willing to open a pull-request?

**Comment by brucew** [comment]
Coming right up. I just wasn't sure if my fix fits simple_form's architecture properly.

**Comment by brucew** [comment]
Pull request: #1590
