### ISSUE TITLE
Add support for Bulma

### ISSUE THREAD

**Issue by unt0xication** [plataformatec/simple_form#1594]
Currently you support bootstrap and zurb foundation, but what about adding Bulma to the pack?

Example of generator:
```bash
$ rails generate simple_form:install --bulma
```

I know that Bulma isn't as popular as bootstrap is, but I think it's a good idea for the future.

**Comment by feliperenan** [comment]
Thanks for the issue :)

We don't want to maintain other themes beyond the ones that we already have. Simple Form should be flexible enough to support any other CSS framework though. If you find any issue that is not specific to Bulma, please, let us know.

Related: https://github.com/plataformatec/simple_form/issues/1572

**Comment by augnustin** [comment]
Anyone has written the wrappers by any chance?

**Comment by voordev** [comment]
I find writing custom wrappers a bit complicated:


How would write a custom wrapper that outputs ( this is in haml format )
```
     .control 
        %label.checkbox
           %input{:type => "checkbox"}/
           I agree to the
           %a{:href => "#"} terms and conditions    
```

I have this but not correct:

```
  config.wrappers :boolean, tag: 'div', class: 'control', error_class: 'has-error' do |b|
    b.wrapper label: 'div', class: 'checkbox' do |a|
      a.use :input, :class => 'checkbox'
      a.use :hint,  :wrap_with => {tag: 'p', class: 'help'}
    end
  end

```

**Comment by voordev** [comment]
@feliperenan 
I have a mostly working implementation for Bulma with some errors left to fix.
Is there interest in adding them to the repo as non-official templates?
So they are centralized and anyone can profit from it and improve upon.

**Comment by feliperenan** [comment]
@voordev We don't have the intention to maintain it here. Maybe we could have somewhere in our documentation a list for these non-official templates maintaining by other repositories. 🤔

**Comment by voordev** [comment]
> @voordev We don't have the intention to maintain it here. Maybe we could have somewhere in our documentation a list for these non-official templates maintaining by other repositories. 🤔

That Would be a good idea.
I have a Bulma implementation but its far from perfect.
I find simple_Form quite hard to override, not for the basic things but for example on associated models with a fields_for they won't work.

Perhaps just a wiki page would be more easy?

**Comment by voordev** [comment]
@feliperenan 
I created a wiki page since I saw there where wiki pages for other frameworks also, most easy.
https://github.com/plataformatec/simple_form/wiki/Bulma-integration

Would you mind to take a look at it? Perhaps you can help resolve the, what i think are last issues with the code. For example fields_for blocks are not rendered the correct html. I posted the issues with the initializer in the top of the wiki page. Kind regards. Hope this helps others as a starting point also.

**Comment by voordev** [comment]
@augnustin 
See my wiki page above for a starting point, any improvements are also welcome

**Comment by feliperenan** [comment]
Nice @voordev, thanks for this ❤️. Now others will be able to take advantage of this documentation and improve it if necessary.

**Comment by alissonviegas** [comment]
Hey @voordev see https://gist.github.com/JuanVqz/f8b4941ba627341ae6d298f64e576869
