### ISSUE TITLE
not an issue, but a newbie one suggestion

### ISSUE THREAD

**Issue by jerome-diver** [plataformatec/simple_form#1597]
# _custom input_ learning time
I get long time to try to understand simple_form customization, but maybe not because of simple_form way of doing things (that i think is nice), but because of my level and the explications provided who are for someone who know allready many things well.

After hours of reading and searching and digging deeper and deeper (i think i read all simple_form source code and rails helpers forms), and after playing inside the rails console, i finally start to understand something that seems to be unclear in explications and a strong prerogative before to customize:

- what is @builder 
- what is "template" 
- what is "object" 
- what is "input_html_options"
- how wrappers there intercat
- how to construct a template form

etc...
# need for implement: [acts_as_taggable_on gem](https://github.com/mbleigh/acts-as-taggable-on)
I  wanted to implement a custom field for input a acts_as_taggable_on tag_list from this tag_list array to a join(", ") string list.
(actually, i'm just start to understand, it is still not full clear in my mind)
Well... that is why i would like to get a link on a tutorial who clearly explain this deeply and i would like after to add a wiki page for explain all of this.
## fresh new *:tags* input
(tell me if there is something better or different to do for the same result... maybe wrappers ?)
```ruby
class TagsInput < SimpleForm::Inputs::StringInput
  def input(wrapper_options = nil)
    data = object.send(attribute_name).join(", ")
    input_html_options[:value] = data
    out = ActiveSupport::SafeBuffer.new
    out << @builder.text_field(attribute_name, input_html_options)
  end
end
```
### and use it like this
here is the concerned content of the model "Article":
```ruby
class Article < ApplicationRecord
  acts_as_ordered_taggable_on :interests
end
```
articles_controller.rb has a :interest_list param permit added
and the concerned form:
```ruby
f.input :interest_list, as: :tags, label: "Interêts"
```
## next step

I would like also to implement input for use with activestorage Rails-5.2 to be able render image uploaded view, and much more on images with activestorage (i didn't find any code shared around).
Maybe you would be interested by some pull request when i will have the correct knowledge to implement this fine ? tell me.

**Comment by rafaelfranca** [comment]
Hi. It is not clear what you need in this issue. Looks like you already implemented your input.

We don't want to support Active Storage out of the box given the design in the applications is going to be very specific and there is no standard of which HTML should be generated.

 The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
