### ISSUE TITLE
Custom Input TestCase?

### ISSUE THREAD

**Issue by eric-hemasystems** [plataformatec/simple_form#1607]
Is there interest in having a test case for custom inputs provided by simple_form? Something like `ActionView::TestCase` but geared a bit more towards testing custom simple_form inputs. Seems useful as well as might be useful even internally in `simple_form`.

Here is an example custom input I am testing:

```
class StaticInput < SimpleForm::Inputs::Base
  def input wrapper_options
    field_id = "#{@builder.object_name}_#{attribute_name}"
    value = @builder.object.public_send(attribute_name).to_s
    template.content_tag 'div', value, id: field_id, class: 'form-control-static'
  end
end
```

This field is not really a form field at all but just a div container with a static value (useful for read only "fields"). I am using rspec so I would ideally have a spec file that looks like:

```
require 'rails_helper'

describe StaticInput, type: :simple_form_input do
  let(:object) { build :organization, name: 'Acme' }

  subject { form.input :name, as: :static }

  it 'renders the value' do
    expect( subject ).to have_content 'Acme'
  end

  it 'wraps the content in a appropiately tagged container' do
    expect( subject ).to have_selector '#organization_name.form-control-static'
  end
end
```

To make the above work I created the following module:

```
# Conceptually the same as the `:helper` type only with some additional support
# to test simple form inputs. The test runs in the context of `form` which
# is a form build via `simple_form_for` against `object`.
concern :SimpleFormHelpers do
  include RSpec::Rails::HelperExampleGroup
  include Capybara::RSpecMatchers
  include SimpleForm::ActionViewExtensions::FormHelper

  included do
    around do |example|
      simple_form_for object, url: '#' do |form|
        @form = form
        example.run
      ensure
        @form = nil
      end
    end

    attr_reader :form
  end

  private

  def protect_against_forgery?
    false
  end
end
```

This hooked it into rspec with:

```
config.include SimpleFormHelpers, type: :simple_form_input
```

This works well for my project but may not be good enough for general purpose usage. Specifically:

* I assume we would want to make Minitest the first class citizen since that is what simple_form uses. Rspec support could still be provided much in the way it is with Rails (by having a `Behavior` module that defines the functionality of the test case and include that module in the test case as well as rspec).
* Having the entire test surrounded by a `simple_form_for` call and assuming we have a value defined named `object` is probably not general enough. Maybe just provide a `with_form(object)` method? Would make the tests a bit more verbose but probably also more explicit and easier to understand.

If there is interest in such an addition to SimpleForm I would like the flesh out the above ideas and submit a PR to get built-in support. If there is not interest I'll just stick with what I have and maybe at least this issue can guide someone else on rolling their own if they have the need.

**Comment by rafaelfranca** [comment]
Thank you for the proposal but we prefer to not include test assertions in this library because we don't want to be maintaining them.

**Comment by MilanJansenOGD** [comment]
Thanks for making this issue anyway, really helped me! 😘
