### ISSUE TITLE
How to completely overrule the generation of html generated for input fields?

### ISSUE THREAD

**Issue by voordev** [plataformatec/simple_form#1612]
I would like to make some modifications to simple_form output to support 3rd party framework.
The problem it is very hard to do basic things like placing a div inside another div.

How can I monkey patch inside my own initializer the output of a complete input field including the label, hint, etc?

I currently have this:
```
  class StringInput < SimpleForm::Inputs::StringInput
    def input(wrapper_options)
      template.content_tag(:div, super, class: 'control')
    end
  end
```

I want to be able to do something like this:
```
  class StringInput < SimpleForm::Inputs::StringInput
    def input(wrapper_options)
      < get here the complete html part that is outputted for <input> fields
    end
  end
```

The reason for this is be able to easily see the complete html blocks that are used to generate the input fields so i can easily modify without having to digg google or the documentation to find, very hard, the right params and hacks to get a basic html structure change..

**Comment by feliperenan** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
