### ISSUE TITLE
Boolean inputs and namespaces

### ISSUE THREAD

**Issue by Insood** [plataformatec/simple_form#1615]
## Environment

- Ruby: 2.4.0
- Rails: 4.2.10
- Simple Form: 3.5.1

## Current behavior

Issue seems to be related to #1161 

```
<%= form_for(@group, namespace: "test") do |f| %>
  <%= f.check_box :_destroy %>
<% end %>

```

produces:

```
<form...>
  <input name="group[_destroy]" type="hidden" value="0"
  <input type="checkbox" value="1" name="group[_destroy]" id="test_group__destroy">
</form>
```
Here the second input has an id, but the first doesn't.

On the other hand:
```
<%= simple_form_for(@group, namespace: "test") do |f| %>
  <%= f.input :_destroy, as: :boolean%>
<% end %>
```
produces:
```
<form ...>
  <div class="form-group ...">
    <div class="checkbox">
      <input value="0" id="test" type="hidden" name="group[_destroy]">
      <label class="boolean optional" for="test_router_component_group__destroy">
        <input type="checkbox" value="1" name="group[_destroy]" id="test__group__destroy">Destroy
      </label>
    </div>
  </div>
</form>
```

The generated HTML creates an id attribute with the same value as the namespace name. This is a problem if multiple elements are created - since they all get same id. Not super breaking, just not really standards compliant? 

I can't tell if this has been fixed in the latest version since I'm still stuck on rails 4.

**Comment by Insood** [comment]
Did some more testing - this time with a fresh Rails 5.1.6 and Simple Forms 4.0.1 install.

This issue appears _only_ if you've run _rails generate simple_form:install --bootstrap_ 

It appears to be an issue with one of the wrappers. I will poke around some more and see what it is.

**Comment by feliperenan** [comment]
Hi @Insood,

Are you still digging into this issue?

**Comment by Insood** [comment]
I've just been living with it :)

You get validation errors, but it doesn't affect functionality unless you're using jquery selectors.

**Comment by feliperenan** [comment]
So I'm gonna close this one. If this is still an issue we can reopen then.

Thanks
