### ISSUE TITLE
form-control-label class was removed from bootstrap

### ISSUE THREAD

**Issue by Abduvakilov** [plataformatec/simple_form#1616]
https://getbootstrap.com/docs/4.1/migration/#breaking says:

> Removed the unused .form-control-label class. If you did make use of this class, it was duplicate of the .col-form-label class that vertically centered a <label> with it’s associated input in horizontal form layouts.

So we should remove or replace `.form-control-label` from [`simple_form_bootstrap.rb`](https://github.com/plataformatec/simple_form/blob/master/lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb) where needed

**Comment by feliperenan** [comment]
Sure, if it wasn't used we can just remove it. Do you mind to open a pull request for that?

Thanks for the issue ❤️

**Comment by Abduvakilov** [comment]
[#1617](https://github.com/plataformatec/simple_form/pull/1617)

**Comment by feliperenan** [comment]
closes https://github.com/plataformatec/simple_form/pull/1617
