### ISSUE TITLE
Bootstrap custom radio button and check box labels not classed

### ISSUE THREAD

**Issue by Abduvakilov** [plataformatec/simple_form#1618]
## Current behavior
I am using `custom_collection` wrapper for radio_buttons but radio button radios are not displaying. This is because labels are not getting `custom-control-label` class but `collection_radio_buttons` instead. 
So I wondered how `simple_form-bootstrap` repo implemented it and saw this [css workaround](https://github.com/rafaelfranca/simple_form-bootstrap/blob/master/app/assets/stylesheets/simple_form-bootstrap/_form_collection_label.scss).That was basically extending `.collection_radio_buttons` with `.custom-control-label`. After adding the stylesheet from the repo I had radio buttons but as square as in the image
![square radio buttons](https://user-images.githubusercontent.com/24228505/48795044-9128ba00-ed1d-11e8-9afe-4b7c201a4d39.jpeg)

## Expected behavior
Custom radio buttons with no css hacks

Can Simple Form just add class to radio button label, I couldn't find out. Should we have any other css other than bootstrap like [this](https://github.com/rafaelfranca/simple_form-bootstrap/blob/master/app/assets/stylesheets/simple_form-bootstrap/_form_collection_label.scss) for simple form to show properly?

P.S I think this is an issue, that's why didn't post it on stackoverflow

**Comment by feliperenan** [comment]
Hi @Abduvakilov, thanks for the issue.

Passing the `custom-control-label` class to the label, would solve the issue?

I'm not sure if it helps, but you can build this custom collection passing a block. See:

https://github.com/plataformatec/simple_form/blob/ccfb22910f454b8e0c9534e3babaaeae59abe83b/lib/simple_form/form_builder.rb#L367

**Comment by feliperenan** [comment]
Closing it since it hasn't recent activity.
