### ISSUE TITLE
How to update join table in habtm association when creating new item

### ISSUE THREAD

**Issue by louishugens** [plataformatec/simple_form#1620]
Hello,

I have 2 models Item and Provider linked with habtm association via a items_providers join table. When creating the Items i use the f.association helper to select existing providers. The issue is when i create the item the join table is not update. Please help me figure out how properly implement this. Thanks in advance.

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
