### ISSUE TITLE
full_messages for errors

### ISSUE THREAD

**Issue by nir0** [plataformatec/simple_form#1631]
i would love to see an initializer option to nicely display `f.object.errors.full_messages` splitted into list items by default

sometimes error lays outside of the form, so form just silently stops working. this is the only way to see the problem. also it would be nice to see errors summary on very top of the form, just like in old days. 

any clue how can i achieve that? for now i use:

```haml
=simple_form_for @mission do |f|
  =f.error_notification message: @mission.errors.full_messages.to_sentence
```

not very clean, list would be better and i'd wish to include it automatically into all forms by default

**Comment by feliperenan** [comment]
Hi @nir0, thanks for the report.

I don't think we should include this feature at Simple Form since it's simple enough to display all form's errors like you did - just one line of code. If you need something more complex, you can create a helper for that.

Thanks
