### ISSUE TITLE
Simple Form filtering password_reset_token

### ISSUE THREAD

**Issue by ramaboo-deliv** [plataformatec/simple_form#1642]
## Environment

- Ruby 2.6.1
- Rails 5.2.2
- Simple Form 4.1.0

## Current behavior

I am having an issue with simple form and devise https://github.com/plataformatec/devise/issues/5030 but the problem seems to be with simple form.

I built two identical forms on the devise/passwords/edit.html form.
<img width="512" alt="screen shot 2019-02-21 at 6 19 35 pm" src="https://user-images.githubusercontent.com/32721566/53215442-86740e80-3605-11e9-84e9-bd976b6a8397.png">
<img width="924" alt="screen shot 2019-02-21 at 6 19 54 pm" src="https://user-images.githubusercontent.com/32721566/53215453-8bd15900-3605-11e9-8ed2-8c3dbeaa1610.png">

When I go to the url http://localhost:5000/users/password/edit?reset_password_token=yVGwys3__ZzU8Hbyx9Ws I would expect both forms to behave identically but for some reason simple_form does not show the password_reset_token.

The value is set on the resource:
<img width="785" alt="screen shot 2019-02-21 at 5 48 20 pm" src="https://user-images.githubusercontent.com/32721566/53215482-b7544380-3605-11e9-934f-8979485f7424.png">

## Expected behavior
Both forms should show the value

Is it possible simple form is doing something special because of the name of this field (contains password, and token). That's all I can think of but could not find any such code in simple_form.

**Comment by feliperenan** [comment]
Hi @ramaboo-deliv 

If you want to show this value at Simple Form input you must explicit `as: :string` for reset_password_token input:

```Ruby
f.input :reset_password_token, as: :string
```

For some reason, Simple Form can't figure out the correct type for this input automatically.

Thanks for the issue :).

**Comment by ramaboo-deliv** [comment]
Awesome thanks. Don't know why I didn't think of that.
