### ISSUE TITLE
REMOVED: SOLVED

### ISSUE THREAD

**Issue by joshm1204** [plataformatec/simple_form#1645]
REMOVED: SOLVED

**Comment by taylorthurlow** [comment]
@joshm1204 I would suggest not editing your issue the way you did. Even if you might consider your issue "wrong" or "useless", it's undoubtedly even more useless when you replace all the text with "REMOVED". There's always the chance someone made the same mistake you did. Just a note for the future.

**Comment by feliperenan** [comment]
Yeah, I'd suggest the same. Also, would be awesome to share why it's not an issue anymore. It could help others in the future.

Thanks :)

**Comment by joshm1204** [comment]
updated, I hope this is useful.
