### ISSUE TITLE
  @@collection_value_methods = %i[id to_s] (add value)

### ISSUE THREAD

**Issue by joshm1204** [plataformatec/simple_form#1662]
Feature Request:

Please change:

 ` @@collection_value_methods = %i[id to_s]`

to include the :value

 ` @@collection_value_methods = %I[to_value id to_s]`

Better yet, it would be nice to be able to set the:

@@collection_value_methods
@@collection_label_methods

in two different configurable parameters so each user could customize the use.

I tried pushing a new branch with the change for a PR, but I got a 403 error.

**Comment by rafaelfranca** [comment]
Please see https://github.com/plataformatec/simple_form/blob/1411dc3349ea03d4f3e902b9340187e4133067e8/lib/generators/simple_form/templates/config/initializers/simple_form.rb#L94

**Comment by joshm1204** [comment]
LOL- Sorry I missed that! Great!
