### ISSUE TITLE
Inputs are accidentally converted to file inputs after upgrade to 5.0

### ISSUE THREAD

**Issue by fschwahn** [plataformatec/simple_form#1671]
## Environment

- Ruby 2.6
- Rails 5.2
- Simple Form 5.0

## Current behavior

When updating to simple_form 5.0, some of our inputs were accidentally converted to file inputs. This was caused by the new check for file fields, namely the check for `#{attribute_name}_url` (eg. a field `twitter_account`, with an accompanying `twitter_account_url`-method). I can imagine that having a `_url` suffix for attributes is not _that uncommon_, so this could bite more people.

I fixed the issue by explictly setting `as: :string` for these inputs.

## Expected behavior

Maybe it would be possible to replace this check with a more specific one, eg. `remote_#{attribute_name}_url=` - I think that would make accidental false positive much less likely. This check would work for both `simple_form` and `refile`.

**Comment by tegon** [comment]
Hi @fschwahn, thanks for reporting this.

Unfortunately, there will always be the possibility of false positives but it's definitely better if we can mitigate it.

I'll try to find out in which versions of the Gems `remote_#{attribute_name}_url` is present to see if it's viable.

**Comment by Redapted** [comment]
Ran into this problem as well. Maybe a config option could be added allowing folks to specify the gem?

For example:
```ruby
SimpleForm.file_attachment_gem = :paperclip
```

That would allow us to use the new, safer strategy, but skip irrelevant checks. Something along the lines of this may work:

```ruby
    ATTACHMENT_GEM_METHODS = {
      active_storage: ['%s_attachment'],
      refile:         ['%s_attachment', '%s_url', '%s_attacher'],
      shrine:         ['%s_url', '%s_attacher'],
      carrier_wave:   ['%s_url'],
      paperclip:      ['%s_file_name']
    }.freeze

    # ...

    def file_method?(attribute_name)
      possible_methods =
        ATTACHMENT_GEM_METHODS.fetch(
          SimpleForm.file_attachment_gem,
          ATTACHMENT_GEM_METHODS.values.flatten.uniq
        )

      possible_methods.any? do |method|
        formatted_method = format(method, attribute_name)
        @object.respond_to?(formatted_method)
      end
    end
```
This is just a rough illustration; it may or may not actually run as-intended (IIRC, `#values` ordering isn't guaranteed to be stable).

**Comment by tegon** [comment]
@Redapted this is more flexible but I'm not sure if the complexity is worth it. 
I'll write a patch to use `remote_#{attribute_name}_url` instead of `#{attribute_name}_url` as @fschwahn suggested.
