### ISSUE TITLE
Bug in aria-required for select boxes

### ISSUE THREAD

**Issue by kodujeme** [plataformatec/simple_form#1675]
## Environment

- Ruby 2+
- Rails 5+
- Simple Form 4+

## Current behavior
steps to reproduce:
1. add a collection select to a form
`  =f.input :test, label: "Test" , as: :select, collection: @form.test_options, prompt: " --  please select an option --"`
2. set prompt
3. create a validation in model for a presence of the field (ie. make field required due to validation)
4. set browser_validations to true in config/initializers/simple_form.rb
`  config.browser_validations = true`
result:
generated aria-label contains value of prompt, instead of **true**
`<select class="form-control select required" required="required" aria-required="--  please select an option --" name="form[test]" id="form_test">`

## Expected behavior
generated aria-label should contain "true"

## Solution
This line:
https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/inputs/collection_input.rb#L44
should have:
` !!input_options[:prompt] `
or
` input_options[:prompt].present?`
instead of
` input_options[:prompt] `

**Comment by kodujeme** [comment]
@feliperenan hey, you labeled it as needs debugging -  I do not think it needs debugging I wrote the solution and I think the reason is quite obvious.

**Comment by feliperenan** [comment]
@kodujeme Hi 👋 

Just labeled for organization and to check it later. Do you mind to send the pull-request with the proposed solution and tests? One of those seems fine to me as long as we cover it :).

Thanks

**Comment by CarlosAlbertoSantos** [comment]
@feliperenan 👋

I will make this change :)
